# 2. Random over sampling

In [32]:
# 필요 라이브러리 import 
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
import warnings
warnings.filterwarnings(action='ignore') 

In [33]:
from imblearn.combine import SMOTEENN

In [34]:
from imblearn.under_sampling import RandomUnderSampler
from imblearn.over_sampling import RandomOverSampler
from imblearn.over_sampling import SMOTE

from sklearn.datasets import make_classification
from collections import Counter

from matplotlib import pyplot as plt
import seaborn as sns

In [35]:
df = pd.read_csv("./데이터자료/9-2. Std 데이터셋.csv")
feature = pd.read_csv("./데이터자료/8-2. Std feature.csv")
df

회사명   거래소코드        회계년도         상장일 상장폐지일  소속코드  \
0     (주)CMG제약   58820  2011-12-01  2001-08-31   NaN     5   
1     (주)CMG제약   58820  2012-12-01  2001-08-31   NaN     5   
2     (주)CMG제약   58820  2013-12-01  2001-08-31   NaN     5   
3     (주)CMG제약   58820  2014-12-01  2001-08-31   NaN     5   
4     (주)CMG제약   58820  2015-12-01  2001-08-31   NaN     5   
...        ...     ...         ...         ...   ...   ...   
9273   휴마시스(주)  205470  2020-12-01  2014-12-01   NaN     5   
9274     휴젤(주)  145020  2019-12-01  2015-12-24   NaN     5   
9275     휴젤(주)  145020  2020-12-01  2015-12-24   NaN     5   
9276   흥구석유(주)   24060  2019-12-01  1994-12-07   NaN     5   
9277   흥구석유(주)   24060  2020-12-01  1994-12-07   NaN     5   

                     산업명    매출액증가율   유형자산증가율   재고자산증가율  ...      부가가치  \
0       의료용 물질 및 의약품 제조업  1.186494 -0.286555 -0.242712  ... -0.517775   
1       의료용 물질 및 의약품 제조업 -0.465320 -0.266139 -0.145700  ... -0.570848   
2       의료용 물질 및 의약품 제조업  0.399443 -0.034331  0.368591  ... -0.459402   
3       의료용 물질 및 의약품 제조업  0.042989  0.633335 -0.160104  ... -0.458301   
4       의료용 물질 및 의약품 제조업  0.229752 -0.280476 -0.110645  ... -0.503803   
...                  ...       ...       ...       ...  ...       ...   
9273    의료용 물질 및 의약품 제조업  5.662930  1.347455  2.510801  ... -0.151711   
9274    의료용 물질 및 의약품 제조업  0.059296 -0.046260  0.113775  ...  1.299954   
9275    의료용 물질 및 의약품 제조업 -0.170016 -0.100971 -0.437478  ...  1.349171   
9276         도매 및 상품 중개업 -0.488761 -0.299172  0.793390  ... -0.392823   
9277         도매 및 상품 중개업 -0.856425 -0.378544 -0.424663  ... -0.359343   

       총자본투자효율    설비투자효율    기계투자효율     부가가치율   노동소득분배율     자본분배율     이윤분배율  \
0    -0.268715 -0.204982 -0.097181  0.001823  0.167352 -0.034998 -0.128958   
1    -0.965957 -0.239707 -0.097246 -0.455154  7.331845 -8.395971 -8.842764   
2    -0.280668 -0.160693 -0.097092  0.377872 -0.016097  0.127964  0.136844   
3    -0.300589 -0.202938 -0.097179  0.294901  0.063259  0.057470  0.125748   
4    -0.558426 -0.217252 -0.097201 -0.090083  0.704439 -0.512105 -0.358349   
...        ...       ...       ...       ...       ...       ...       ...   
9273  1.140567 -0.125778 -0.096931  0.930074 -0.576239  0.625551  0.569922   
9274 -0.272699 -0.062404 -0.097006  0.914756 -0.434150  0.499330  0.360994   
9275 -0.301727 -0.058107 -0.096969  0.907353 -0.415350  0.482630  0.330828   
9276 -0.500939 -0.145811 -0.095817 -0.354313 -0.106535  0.208302  0.265758   
9277 -0.421255 -0.140271 -0.095169 -0.325975 -0.166101  0.261216  0.306350   

      label   회계년  
0       0.0  2011  
1       0.0  2012  
2       0.0  2013  
3       0.0  2014  
4       0.0  2015  
...     ...   ...  
9273    0.0  2020  
9274    0.0  2019  
9275    0.0  2020  
9276    0.0  2019  
9277    0.0  2020  

[9278 rows x 57 columns]

In [36]:
train = df[df["회계년"] <= 2018].reset_index(drop='index')
test  = df[df["회계년"] > 2018].reset_index(drop='index')
col = df.columns[7:55]

In [37]:
train["label"].value_counts()

0.0    6792
1.0     121
Name: label, dtype: int64

In [38]:
test["label"].value_counts()

0.0    2315
1.0      50
Name: label, dtype: int64

In [39]:
x_train = train[col]
y_train = train["label"]
x_test = test[col]
y_test = test["label"]

In [40]:
x_train, y_train = SMOTEENN(random_state=4).fit_resample(x_train,y_train)
print(x_train.shape)
y_train.value_counts()

(13061, 48)


1.0    6788
0.0    6273
Name: label, dtype: int64

In [41]:
mda_feature=feature["mda_feature"].tolist()
logit_feature=feature["logit_feature"].tolist()
lasso_feature=feature["lasso_feature"].tolist()
ela_feature=feature["ela_feature"].tolist()
same_feature=feature["same_feature"].tolist()

In [42]:
# 성능확인 코드
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score
from sklearn.metrics import f1_score, roc_auc_score, average_precision_score


import warnings

def get_clf_eval(MDA_y_test, pred):
    confusion = confusion_matrix(MDA_y_test, pred)
    accuracy = accuracy_score(MDA_y_test, pred)
    precision = precision_score(MDA_y_test, pred)
    recall = recall_score(MDA_y_test, pred)
    roc_score = roc_auc_score(MDA_y_test, pred)
    pr_score = average_precision_score(MDA_y_test, pred)
    f1 = f1_score(MDA_y_test, pred)
    print('오차행렬')
    print(confusion)
    print('정확도: {0:.4f}, 정밀도 : {1:.4f}, 재현율:{2:.4f},F1 스코어:{3:.4f}'.format(accuracy, precision, recall, f1, roc_score))
    print('ROC 스코어: {0:.4f}, PR score : {1:.4f}'.format(roc_score, pr_score))

In [43]:
# 임계값에 따른 오차행렬및 스코어 -------->#임계값 최적 : 재현율기준(0.1)/f1기준(0.3)
from sklearn.preprocessing import Binarizer
thresholds = [0.1,0.2,0.3,0.4,0.5]

def get_eval_by_threshold(MDA_y_test, pred_proba_c1, thresholds):
    for custom_threshold in thresholds:
        binarizer = Binarizer(threshold=custom_threshold).fit(pred_proba_c1)
        custom_predict = binarizer.transform(pred_proba_c1)
        print("임곗값:", custom_threshold)
        get_clf_eval(MDA_y_test, custom_predict)
        print("---------------------------------------------------------")


In [44]:
# Roc Auc 그래프 값 확인 코드
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score
def roc_curve_plot(MDA_y_test, pred_proba_c1):
    fprs, tprs, thresholds = roc_curve(MDA_y_test, pred_proba_c1)
    
    plt.plot(fprs, tprs, label='ROC')
    plt.plot([0,1],[0,1], 'k--', label = 'Random')
    
    start, end= plt.xlim()
    plt.xticks(np.round(np.arange(start, end, 0.1),2))
    plt.xlim(0,1); plt.ylim(0,1)
    plt.xlabel('FPR(1-Sensitivity)'); plt.ylabel('TPR(Recall)')
    plt.legend()
    plt.show()

In [45]:
mda_x_train = x_train[mda_feature].reset_index(drop='index')
mda_x_test = x_test[mda_feature].reset_index(drop='index')
mda_y_train = y_train
mda_y_test = test["label"]

In [46]:
logit_x_train = x_train[logit_feature].reset_index(drop='index')
logit_x_test = x_test[logit_feature].reset_index(drop='index')
logit_y_train = y_train
logit_y_test = test["label"]

In [47]:
lasso_x_train = x_train[lasso_feature].reset_index(drop='index')
lasso_x_test = x_test[lasso_feature].reset_index(drop='index')
lasso_y_train = y_train
lasso_y_test = test["label"]

In [48]:
ela_x_train = x_train[ela_feature].reset_index(drop='index')
ela_x_test = x_test[ela_feature].reset_index(drop='index')
ela_y_train = y_train
ela_y_test = test["label"]

In [49]:
same_x_train = x_train[same_feature].reset_index(drop='index')
same_x_test = x_test[same_feature].reset_index(drop='index')
same_y_train = y_train
same_y_test = test["label"]

In [50]:
fea_x_train = [mda_x_train, logit_x_train, lasso_x_train, ela_x_train, same_x_train]
fea_y_train = [mda_y_train, logit_y_train, lasso_y_train, ela_y_train, same_y_train]
fea_x_test = [mda_x_test, logit_x_test, lasso_x_test, ela_x_test, same_x_test]
fea_y_test = [mda_y_test, logit_y_test, lasso_y_test, ela_y_test, same_y_test]
fea = ["mda","logit","lasso","ela","same"]

In [51]:
# 1-1 LDA 
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
lda_clf = LinearDiscriminantAnalysis()
for x_train,y_train,x_test,y_test,feature in zip(fea_x_train,fea_y_train,fea_x_test, fea_y_test, fea):
    lda_clf.fit(x_train, y_train)
    lda_pred = lda_clf.predict(x_test)
    lda_pred_proba = lda_clf.predict_proba(x_test)
    print(feature,"lda") 
    get_clf_eval(y_test, lda_pred)
    get_eval_by_threshold(y_test , lda_pred_proba[:,1].reshape(-1,1), thresholds)



mda lda
오차행렬
[[1807  508]
 [  15   35]]
정확도: 0.7789, 정밀도 : 0.0645, 재현율:0.7000,F1 스코어:0.1180
ROC 스코어: 0.7403, PR score : 0.0515
임곗값: 0.1
오차행렬
[[ 455 1860]
 [   5   45]]
정확도: 0.2114, 정밀도 : 0.0236, 재현율:0.9000,F1 스코어:0.0460
ROC 스코어: 0.5483, PR score : 0.0234
---------------------------------------------------------
임곗값: 0.2
오차행렬
[[ 861 1454]
 [   9   41]]
정확도: 0.3814, 정밀도 : 0.0274, 재현율:0.8200,F1 스코어:0.0531
ROC 스코어: 0.5960, PR score : 0.0263
---------------------------------------------------------
임곗값: 0.3
오차행렬
[[1275 1040]
 [  10   40]]
정확도: 0.5560, 정밀도 : 0.0370, 재현율:0.8000,F1 스코어:0.0708
ROC 스코어: 0.6754, PR score : 0.0339
---------------------------------------------------------
임곗값: 0.4
오차행렬
[[1590  725]
 [  13   37]]
정확도: 0.6879, 정밀도 : 0.0486, 재현율:0.7400,F1 스코어:0.0911
ROC 스코어: 0.7134, PR score : 0.0414
---------------------------------------------------------
임곗값: 0.5
오차행렬
[[1807  508]
 [  15   35]]
정확도: 0.7789, 정밀도 : 0.0645, 재현율:0.7000,F1 스코어:0.1180
ROC 스코어: 0.7403, PR score : 0.0515
-

In [52]:
# 1-2 디시전트리 
from sklearn.tree import DecisionTreeClassifier 
dt_clf = DecisionTreeClassifier(random_state=52)
for x_train,y_train,x_test,y_test,feature in zip(fea_x_train,fea_y_train,fea_x_test, fea_y_test, fea):
    dt_clf.fit(x_train, y_train)
    dt_pred = dt_clf.predict(x_test)
    dt_pred_proba = dt_clf.predict_proba(x_test)   
    print(feature,"디시전트리") 
    get_clf_eval(y_test, dt_pred)
    get_eval_by_threshold(y_test , dt_pred_proba[:,1].reshape(-1,1), thresholds)
    


mda 디시전트리
오차행렬
[[2070  245]
 [  29   21]]
정확도: 0.8841, 정밀도 : 0.0789, 재현율:0.4200,F1 스코어:0.1329
ROC 스코어: 0.6571, PR score : 0.0454
임곗값: 0.1
오차행렬
[[2070  245]
 [  29   21]]
정확도: 0.8841, 정밀도 : 0.0789, 재현율:0.4200,F1 스코어:0.1329
ROC 스코어: 0.6571, PR score : 0.0454
---------------------------------------------------------
임곗값: 0.2
오차행렬
[[2070  245]
 [  29   21]]
정확도: 0.8841, 정밀도 : 0.0789, 재현율:0.4200,F1 스코어:0.1329
ROC 스코어: 0.6571, PR score : 0.0454
---------------------------------------------------------
임곗값: 0.3
오차행렬
[[2070  245]
 [  29   21]]
정확도: 0.8841, 정밀도 : 0.0789, 재현율:0.4200,F1 스코어:0.1329
ROC 스코어: 0.6571, PR score : 0.0454
---------------------------------------------------------
임곗값: 0.4
오차행렬
[[2070  245]
 [  29   21]]
정확도: 0.8841, 정밀도 : 0.0789, 재현율:0.4200,F1 스코어:0.1329
ROC 스코어: 0.6571, PR score : 0.0454
---------------------------------------------------------
임곗값: 0.5
오차행렬
[[2070  245]
 [  29   21]]
정확도: 0.8841, 정밀도 : 0.0789, 재현율:0.4200,F1 스코어:0.1329
ROC 스코어: 0.6571, PR score : 0.0454

In [53]:
from sklearn.tree import DecisionTreeClassifier 
dt_clf = DecisionTreeClassifier(random_state=52)
from sklearn.model_selection import GridSearchCV
tree = DecisionTreeClassifier(random_state=52)
for x_train,y_train,x_test,y_test,feature in zip(fea_x_train,fea_y_train,fea_x_test, fea_y_test, fea):
    # key: 하이퍼파라미터 명; value: [후보값들] 을 리스트로 전달
    param_grid = {
      'criterion': ['entropy', 'gini'],
               'max_depth': [2,4,6,8],
               'max_features': ['auto', 'sqrt'],
               'min_samples_leaf': [4,6,8,10],
               'min_samples_split': [4,6,8,10]}
    grid_search = GridSearchCV(tree
                            , param_grid = param_grid
                            , cv = 5 #교차검증시 fold 개수; n번의 교차검증; 데이터들이 돌아가면서 하나씩 검증(validation)에 사용되어 일반화하는 것; 데이터가 많지 않을 때 보통 쓰인다고 함
                            , n_jobs = -1)  #-1: 모든 코어 사용

    grid_search.fit(x_train, y_train)

    # 최선의 결과 출력
    print('피처:{2} 최적 하이퍼 파라미터 :{0}, 최적 평균 정확도 :{1:.3f}'.format(grid_search.best_params_, grid_search.best_score_, feature))
    a = grid_search.best_params_
    keys=list(a.keys())
    values = list(a.values())

    dt_clf_best = DecisionTreeClassifier(random_state=52,criterion = values[0], max_depth = values[1],max_features=values[2], min_samples_leaf=values[3], min_samples_split=values[4])
    dt_clf_best.fit(x_train, y_train)
    dt_best_pred = dt_clf_best.predict(x_test)
    dt_best_pred_proba = dt_clf_best.predict_proba(x_test)   

    print(feature,"디시전트리 파라미터적용") 
    get_clf_eval(y_test, dt_best_pred)
    get_eval_by_threshold(y_test ,dt_best_pred_proba[:,1].reshape(-1,1), thresholds)


피처:mda 최적 하이퍼 파라미터 :{'criterion': 'gini', 'max_depth': 8, 'max_features': 'auto', 'min_samples_leaf': 10, 'min_samples_split': 4}, 최적 평균 정확도 :0.885
mda 디시전트리 파라미터적용
오차행렬
[[1931  384]
 [  23   27]]
정확도: 0.8279, 정밀도 : 0.0657, 재현율:0.5400,F1 스코어:0.1171
ROC 스코어: 0.6871, PR score : 0.0452
임곗값: 0.1
오차행렬
[[1091 1224]
 [  12   38]]
정확도: 0.4774, 정밀도 : 0.0301, 재현율:0.7600,F1 스코어:0.0579
ROC 스코어: 0.6156, PR score : 0.0280
---------------------------------------------------------
임곗값: 0.2
오차행렬
[[1478  837]
 [  14   36]]
정확도: 0.6402, 정밀도 : 0.0412, 재현율:0.7200,F1 스코어:0.0780
ROC 스코어: 0.6792, PR score : 0.0356
---------------------------------------------------------
임곗값: 0.3
오차행렬
[[1830  485]
 [  19   31]]
정확도: 0.7869, 정밀도 : 0.0601, 재현율:0.6200,F1 스코어:0.1095
ROC 스코어: 0.7052, PR score : 0.0453
---------------------------------------------------------
임곗값: 0.4
오차행렬
[[1917  398]
 [  22   28]]
정확도: 0.8224, 정밀도 : 0.0657, 재현율:0.5600,F1 스코어:0.1176
ROC 스코어: 0.6940, PR score : 0.0461
------------------------------

In [54]:
# 1-3 랜덤포레스트 구현 
from sklearn.ensemble import RandomForestClassifier
rf_clf = RandomForestClassifier(random_state=52)    
for x_train,y_train,x_test,y_test,feature in zip(fea_x_train,fea_y_train,fea_x_test, fea_y_test, fea):
    rf_clf.fit(x_train, y_train)
    rf_pred = rf_clf.predict(x_test)
    rf_pred_proba = rf_clf.predict_proba(x_test)
    print(feature,"랜덤포레스트") 
    get_clf_eval(y_test, rf_pred)
    get_eval_by_threshold(y_test , rf_pred_proba[:,1].reshape(-1,1), thresholds)
    


mda 랜덤포레스트
오차행렬
[[2182  133]
 [  27   23]]
정확도: 0.9323, 정밀도 : 0.1474, 재현율:0.4600,F1 스코어:0.2233
ROC 스코어: 0.7013, PR score : 0.0792
임곗값: 0.1
오차행렬
[[1546  769]
 [  11   39]]
정확도: 0.6702, 정밀도 : 0.0483, 재현율:0.7800,F1 스코어:0.0909
ROC 스코어: 0.7239, PR score : 0.0423
---------------------------------------------------------
임곗값: 0.2
오차행렬
[[1860  455]
 [  16   34]]
정확도: 0.8008, 정밀도 : 0.0695, 재현율:0.6800,F1 스코어:0.1262
ROC 스코어: 0.7417, PR score : 0.0540
---------------------------------------------------------
임곗값: 0.3
오차행렬
[[2041  274]
 [  19   31]]
정확도: 0.8761, 정밀도 : 0.1016, 재현율:0.6200,F1 스코어:0.1746
ROC 스코어: 0.7508, PR score : 0.0711
---------------------------------------------------------
임곗값: 0.4
오차행렬
[[2133  182]
 [  22   28]]
정확도: 0.9137, 정밀도 : 0.1333, 재현율:0.5600,F1 스코어:0.2154
ROC 스코어: 0.7407, PR score : 0.0840
---------------------------------------------------------
임곗값: 0.5
오차행렬
[[2182  133]
 [  27   23]]
정확도: 0.9323, 정밀도 : 0.1474, 재현율:0.4600,F1 스코어:0.2233
ROC 스코어: 0.7013, PR score : 0.079

In [55]:
# 하이퍼파라미터 Grid-Search
from sklearn.model_selection import GridSearchCV

    # 탐색 범위 정의
for x_train,y_train,x_test,y_test,feature in zip(fea_x_train,fea_y_train,fea_x_test, fea_y_test, fea):
    grid_search = {'criterion': ['entropy', 'gini'],
                'max_depth': [2,4,6,8],
                'max_features': ['auto', 'sqrt'],
                'min_samples_leaf': [4,6,8,10],
                'min_samples_split': [4,6,8,10],
                'n_estimators': [20,40,60,80,100]}

    model = RandomForestClassifier(random_state=52)
    grid_search = GridSearchCV(estimator = model, param_grid = grid_search, 
                                cv = 5,verbose=0, n_jobs = -1)
    grid_search.fit(x_train,y_train)

    # 최선의 결과 출력
    print('최적 하이퍼 파라미터 :{0}, 최적 평균 정확도 :{1:.3f}'.format(grid_search.best_params_, grid_search.best_score_))
    a = grid_search.best_params_
    keys=list(a.keys())
    values = list(a.values())

    rf_clf_best = RandomForestClassifier(random_state=52,criterion = values[0], max_depth = values[1],max_features=values[2], min_samples_leaf=values[3],  min_samples_split=values[4],n_estimators=values[5])
    rf_clf_best.fit(x_train, y_train)
    rf_best_pred = rf_clf_best.predict(x_test)
    rf_best_pred_proba = rf_clf_best.predict_proba(x_test)   

    print(feature,"디시전트리 파라미터적용") 
    get_clf_eval(y_test, rf_best_pred)
    get_eval_by_threshold(y_test ,rf_best_pred_proba[:,1].reshape(-1,1), thresholds)

최적 하이퍼 파라미터 :{'criterion': 'gini', 'max_depth': 8, 'max_features': 'auto', 'min_samples_leaf': 4, 'min_samples_split': 10, 'n_estimators': 100}, 최적 평균 정확도 :0.900
mda 디시전트리 파라미터적용
오차행렬
[[2035  280]
 [  18   32]]
정확도: 0.8740, 정밀도 : 0.1026, 재현율:0.6400,F1 스코어:0.1768
ROC 스코어: 0.7595, PR score : 0.0733
임곗값: 0.1
오차행렬
[[ 458 1857]
 [   3   47]]
정확도: 0.2135, 정밀도 : 0.0247, 재현율:0.9400,F1 스코어:0.0481
ROC 스코어: 0.5689, PR score : 0.0245
---------------------------------------------------------
임곗값: 0.2
오차행렬
[[1542  773]
 [  11   39]]
정확도: 0.6685, 정밀도 : 0.0480, 재현율:0.7800,F1 스코어:0.0905
ROC 스코어: 0.7230, PR score : 0.0421
---------------------------------------------------------
임곗값: 0.3
오차행렬
[[1786  529]
 [  14   36]]
정확도: 0.7704, 정밀도 : 0.0637, 재현율:0.7200,F1 스코어:0.1171
ROC 스코어: 0.7457, PR score : 0.0518
---------------------------------------------------------
임곗값: 0.4
오차행렬
[[1916  399]
 [  16   34]]
정확도: 0.8245, 정밀도 : 0.0785, 재현율:0.6800,F1 스코어:0.1408
ROC 스코어: 0.7538, PR score : 0.0602
----------------

In [ ]:
# 1-4 로지스틱회귀
from sklearn.linear_model import LogisticRegression
lr_clf = LogisticRegression()
for x_train,y_train,x_test,y_test,feature in zip(fea_x_train,fea_y_train,fea_x_test, fea_y_test, fea):
    lr_clf.fit(x_train, y_train)
    lr_pred = lr_clf.predict(x_test)
    lr_pred_proba = lr_clf.predict_proba(x_test)
    print(feature,"로지스틱회귀") 
    get_clf_eval(y_test, lr_pred)
    get_eval_by_threshold(y_test , lr_pred_proba[:,1].reshape(-1,1), thresholds)
    

mda 로지스틱회귀
오차행렬
[[1812  503]
 [  16   34]]
정확도: 0.7805, 정밀도 : 0.0633, 재현율:0.6800,F1 스코어:0.1158
ROC 스코어: 0.7314, PR score : 0.0498
임곗값: 0.1
오차행렬
[[ 475 1840]
 [   5   45]]
정확도: 0.2199, 정밀도 : 0.0239, 재현율:0.9000,F1 스코어:0.0465
ROC 스코어: 0.5526, PR score : 0.0236
---------------------------------------------------------
임곗값: 0.2
오차행렬
[[ 888 1427]
 [   9   41]]
정확도: 0.3928, 정밀도 : 0.0279, 재현율:0.8200,F1 스코어:0.0540
ROC 스코어: 0.6018, PR score : 0.0267
---------------------------------------------------------
임곗값: 0.3
오차행렬
[[1292 1023]
 [  12   38]]
정확도: 0.5624, 정밀도 : 0.0358, 재현율:0.7600,F1 스코어:0.0684
ROC 스코어: 0.6590, PR score : 0.0323
---------------------------------------------------------
임곗값: 0.4
오차행렬
[[1604  711]
 [  14   36]]
정확도: 0.6934, 정밀도 : 0.0482, 재현율:0.7200,F1 스코어:0.0903
ROC 스코어: 0.7064, PR score : 0.0406
---------------------------------------------------------
임곗값: 0.5
오차행렬
[[1812  503]
 [  16   34]]
정확도: 0.7805, 정밀도 : 0.0633, 재현율:0.6800,F1 스코어:0.1158
ROC 스코어: 0.7314, PR score : 0.049

In [ ]:
#로지스틱 회귀 최적 하이퍼 파라미터
from sklearn.model_selection import GridSearchCV

for x_train,y_train,x_test,y_test,feature in zip(fea_x_train,fea_y_train,fea_x_test, fea_y_test, fea):
    params = {'penalty': ['l2','l1','elasticnet','None'],
            'C':[0.01,0.1,1,3,5,10]}

    grid_search = GridSearchCV(lr_clf, param_grid=params, scoring='accuracy', cv=5)
    grid_search.fit(x_train,y_train)
    print('최적 하이퍼 파라미어:{0}, 최적 평균 정확도:{1:.3f}'.format(grid_search.best_params_, grid_search.best_score_))

    a = grid_search.best_params_
    keys=list(a.keys())
    values = list(a.values())

    lr_clf_best = LogisticRegression(penalty= values[1], C=values[0])
    lr_clf_best.fit(x_train, y_train)
    lr_best_pred = lr_clf_best.predict(x_test)
    lr_best_pred_proba = lr_clf_best.predict_proba(x_test)   

    print(feature,"로지스틱회귀 파라미터적용") 
    get_clf_eval(y_test, lr_best_pred)
    get_eval_by_threshold(y_test ,lr_best_pred_proba[:,1].reshape(-1,1), thresholds)


최적 하이퍼 파라미어:{'C': 0.1, 'penalty': 'l2'}, 최적 평균 정확도:0.810
mda 로지스틱회귀 파라미터적용
오차행렬
[[1811  504]
 [  16   34]]
정확도: 0.7801, 정밀도 : 0.0632, 재현율:0.6800,F1 스코어:0.1156
ROC 스코어: 0.7311, PR score : 0.0497
임곗값: 0.1
오차행렬
[[ 471 1844]
 [   5   45]]
정확도: 0.2182, 정밀도 : 0.0238, 재현율:0.9000,F1 스코어:0.0464
ROC 스코어: 0.5517, PR score : 0.0236
---------------------------------------------------------
임곗값: 0.2
오차행렬
[[ 881 1434]
 [   9   41]]
정확도: 0.3899, 정밀도 : 0.0278, 재현율:0.8200,F1 스코어:0.0538
ROC 스코어: 0.6003, PR score : 0.0266
---------------------------------------------------------
임곗값: 0.3
오차행렬
[[1288 1027]
 [  12   38]]
정확도: 0.5607, 정밀도 : 0.0357, 재현율:0.7600,F1 스코어:0.0682
ROC 스코어: 0.6582, PR score : 0.0322
---------------------------------------------------------
임곗값: 0.4
오차행렬
[[1605  710]
 [  14   36]]
정확도: 0.6939, 정밀도 : 0.0483, 재현율:0.7200,F1 스코어:0.0905
ROC 스코어: 0.7067, PR score : 0.0407
---------------------------------------------------------
임곗값: 0.5
오차행렬
[[1811  504]
 [  16   34]]
정확도: 0.7801, 정밀도 : 0.

In [ ]:
# 1-5 KNN 
from sklearn.neighbors import KNeighborsClassifier
knn_clf = KNeighborsClassifier(n_neighbors=5)
for x_train,y_train,x_test,y_test,feature in zip(fea_x_train,fea_y_train,fea_x_test, fea_y_test, fea):

    knn_clf.fit(x_train, y_train)
    knn_pred = knn_clf.predict(x_test)
    knn_pred_proba = knn_clf.predict_proba(x_test)
    print(feature,"KNN") 
    get_clf_eval(y_test, knn_pred)
    get_eval_by_threshold(y_test , knn_pred_proba[:,1].reshape(-1,1), thresholds)



mda KNN
오차행렬
[[1991  324]
 [  23   27]]
정확도: 0.8533, 정밀도 : 0.0769, 재현율:0.5400,F1 스코어:0.1347
ROC 스코어: 0.7000, PR score : 0.0513
임곗값: 0.1
오차행렬
[[1806  509]
 [  19   31]]
정확도: 0.7767, 정밀도 : 0.0574, 재현율:0.6200,F1 스코어:0.1051
ROC 스코어: 0.7001, PR score : 0.0436
---------------------------------------------------------
임곗값: 0.2
오차행렬
[[1888  427]
 [  20   30]]
정확도: 0.8110, 정밀도 : 0.0656, 재현율:0.6000,F1 스코어:0.1183
ROC 스코어: 0.7078, PR score : 0.0478
---------------------------------------------------------
임곗값: 0.3
오차행렬
[[1888  427]
 [  20   30]]
정확도: 0.8110, 정밀도 : 0.0656, 재현율:0.6000,F1 스코어:0.1183
ROC 스코어: 0.7078, PR score : 0.0478
---------------------------------------------------------
임곗값: 0.4
오차행렬
[[1991  324]
 [  23   27]]
정확도: 0.8533, 정밀도 : 0.0769, 재현율:0.5400,F1 스코어:0.1347
ROC 스코어: 0.7000, PR score : 0.0513
---------------------------------------------------------
임곗값: 0.5
오차행렬
[[1991  324]
 [  23   27]]
정확도: 0.8533, 정밀도 : 0.0769, 재현율:0.5400,F1 스코어:0.1347
ROC 스코어: 0.7000, PR score : 0.0513
-

In [ ]:
# knn 파라미터 구하기
from sklearn.metrics import accuracy_score
acc = []
for x_train,y_train,x_test,y_test,feature in zip(fea_x_train,fea_y_train,fea_x_test, fea_y_test, fea):
    for k in range(1,20):
        knn_clf = KNeighborsClassifier(n_neighbors=k)
        knn_clf.fit(x_train, y_train)
        knn_pred = knn_clf.predict(x_test)
        knn_score=accuracy_score(y_test,knn_pred)

        acc.append(knn_score)
    int = acc.index(max(acc))+1
    print("최적거리")
    print(int)

    knn_clf_best =KNeighborsClassifier(n_neighbors=int)
    knn_clf_best.fit(x_train, y_train)
    knn_best_pred = knn_clf_best.predict(x_test)
    knn_best_pred_proba = knn_clf_best.predict_proba(x_test)   

    print(feature,"KNN 파라미터적용") 
    get_clf_eval(y_test, knn_best_pred)
    get_eval_by_threshold(y_test ,knn_best_pred_proba[:,1].reshape(-1,1), thresholds)      


최적거리
2
mda KNN 파라미터적용
오차행렬
[[2134  181]
 [  30   20]]
정확도: 0.9108, 정밀도 : 0.0995, 재현율:0.4000,F1 스코어:0.1594
ROC 스코어: 0.6609, PR score : 0.0525
임곗값: 0.1
오차행렬
[[2005  310]
 [  23   27]]
정확도: 0.8592, 정밀도 : 0.0801, 재현율:0.5400,F1 스코어:0.1395
ROC 스코어: 0.7030, PR score : 0.0530
---------------------------------------------------------
임곗값: 0.2
오차행렬
[[2005  310]
 [  23   27]]
정확도: 0.8592, 정밀도 : 0.0801, 재현율:0.5400,F1 스코어:0.1395
ROC 스코어: 0.7030, PR score : 0.0530
---------------------------------------------------------
임곗값: 0.3
오차행렬
[[2005  310]
 [  23   27]]
정확도: 0.8592, 정밀도 : 0.0801, 재현율:0.5400,F1 스코어:0.1395
ROC 스코어: 0.7030, PR score : 0.0530
---------------------------------------------------------
임곗값: 0.4
오차행렬
[[2005  310]
 [  23   27]]
정확도: 0.8592, 정밀도 : 0.0801, 재현율:0.5400,F1 스코어:0.1395
ROC 스코어: 0.7030, PR score : 0.0530
---------------------------------------------------------
임곗값: 0.5
오차행렬
[[2134  181]
 [  30   20]]
정확도: 0.9108, 정밀도 : 0.0995, 재현율:0.4000,F1 스코어:0.1594
ROC 스코어: 0.6609, PR sc

In [ ]:
# 1-5 xgboost
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
import xgboost as xgb ## XGBoost 불러오기
from xgboost import plot_importance 

xgb_wrapper = XGBClassifier()
for x_train,y_train,x_test,y_test,feature in zip(fea_x_train,fea_y_train,fea_x_test, fea_y_test, fea):

    xgb_wrapper.fit(x_train, y_train, verbose = True)
    xgb_wrapper.fit(x_train, y_train)
    xgb_pred = xgb_wrapper.predict(x_test)
    xgb_pred_proba = xgb_wrapper.predict_proba(x_test)
    print(feature,"XGB") 
    get_clf_eval(y_test, xgb_pred)
    get_eval_by_threshold(y_test , xgb_pred_proba[:,1].reshape(-1,1), thresholds)

mda XGB
오차행렬
[[2160  155]
 [  24   26]]
정확도: 0.9243, 정밀도 : 0.1436, 재현율:0.5200,F1 스코어:0.2251
ROC 스코어: 0.7265, PR score : 0.0848
임곗값: 0.1
오차행렬
[[1958  357]
 [  17   33]]
정확도: 0.8419, 정밀도 : 0.0846, 재현율:0.6600,F1 스코어:0.1500
ROC 스코어: 0.7529, PR score : 0.0630
---------------------------------------------------------
임곗값: 0.2
오차행렬
[[2035  280]
 [  23   27]]
정확도: 0.8719, 정밀도 : 0.0879, 재현율:0.5400,F1 스코어:0.1513
ROC 스코어: 0.7095, PR score : 0.0572
---------------------------------------------------------
임곗값: 0.3
오차행렬
[[2080  235]
 [  24   26]]
정확도: 0.8905, 정밀도 : 0.0996, 재현율:0.5200,F1 스코어:0.1672
ROC 스코어: 0.7092, PR score : 0.0619
---------------------------------------------------------
임곗값: 0.4
오차행렬
[[2128  187]
 [  24   26]]
정확도: 0.9108, 정밀도 : 0.1221, 재현율:0.5200,F1 스코어:0.1977
ROC 스코어: 0.7196, PR score : 0.0736
---------------------------------------------------------
임곗값: 0.5
오차행렬
[[2160  155]
 [  24   26]]
정확도: 0.9243, 정밀도 : 0.1436, 재현율:0.5200,F1 스코어:0.2251
ROC 스코어: 0.7265, PR score : 0.0848
-

In [ ]:
values[1]

'l2'

In [ ]:
#xgb 최적 하이퍼 파라미터
from sklearn.model_selection import GridSearchCV

xgb_wrapper
for x_train,y_train,x_test,y_test,feature in zip(fea_x_train,fea_y_train,fea_x_test, fea_y_test, fea):
    params = {
            'n_estimators':[40,43,46,50],
            'learning_rate':[0.03,0.05,0.04],
            'max_depth' : [0.8,1,2,3,4]
            }

    grid_clf = GridSearchCV(xgb_wrapper, param_grid=params, scoring='accuracy', cv=5)
    grid_clf.fit(x_train,y_train)
    print('최적 하이퍼 파라미어:{0}, 최적 평균 정확도:{1:.3f}'.format(grid_clf.best_params_, grid_clf.best_score_))

    a = grid_clf.best_params_
    keys=list(a.keys())
    values = list(a.values())
    xgb_clf_best = XGBClassifier( learning_rate=values[0],max_depth=values[1],n_estimators= values[2])
    xgb_clf_best.fit(x_train, y_train)
    xgb_best_pred = xgb_clf_best.predict(x_test)
    xgb_best_pred_proba = xgb_clf_best.predict_proba(x_test)   

    print(feature,"XGB 파라미터적용") 
    get_clf_eval(y_test, xgb_best_pred)
    get_eval_by_threshold(y_test ,xgb_best_pred_proba[:,1].reshape(-1,1), thresholds)

최적 하이퍼 파라미어:{'learning_rate': 0.05, 'max_depth': 4, 'n_estimators': 50}, 최적 평균 정확도:0.876
mda XGB 파라미터적용
오차행렬
[[1893  422]
 [  14   36]]
정확도: 0.8156, 정밀도 : 0.0786, 재현율:0.7200,F1 스코어:0.1417
ROC 스코어: 0.7689, PR score : 0.0625
임곗값: 0.1
오차행렬
[[ 305 2010]
 [   3   47]]
정확도: 0.1488, 정밀도 : 0.0228, 재현율:0.9400,F1 스코어:0.0446
ROC 스코어: 0.5359, PR score : 0.0227
---------------------------------------------------------
임곗값: 0.2
오차행렬
[[1158 1157]
 [   8   42]]
정확도: 0.5074, 정밀도 : 0.0350, 재현율:0.8400,F1 스코어:0.0673
ROC 스코어: 0.6701, PR score : 0.0328
---------------------------------------------------------
임곗값: 0.3
오차행렬
[[1644  671]
 [  12   38]]
정확도: 0.7112, 정밀도 : 0.0536, 재현율:0.7600,F1 스코어:0.1001
ROC 스코어: 0.7351, PR score : 0.0458
---------------------------------------------------------
임곗값: 0.4
오차행렬
[[1798  517]
 [  13   37]]
정확도: 0.7759, 정밀도 : 0.0668, 재현율:0.7400,F1 스코어:0.1225
ROC 스코어: 0.7583, PR score : 0.0549
---------------------------------------------------------
임곗값: 0.5
오차행렬
[[1893  422]
 [  14