# 1. Random Under Sampling


In [47]:
# 필요 라이브러리 import 
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
import warnings
warnings.filterwarnings(action='ignore') 

In [48]:
from imblearn.under_sampling import RandomUnderSampler
from imblearn.over_sampling import RandomOverSampler
from imblearn.over_sampling import SMOTE

from sklearn.datasets import make_classification
from collections import Counter

from matplotlib import pyplot as plt
import seaborn as sns

In [49]:
df = pd.read_csv("./데이터자료/9-2. Std 데이터셋.csv")
feature = pd.read_csv("./데이터자료/8-2. Std feature.csv")
df

회사명   거래소코드        회계년도         상장일 상장폐지일  소속코드  \
0     (주)CMG제약   58820  2011-12-01  2001-08-31   NaN     5   
1     (주)CMG제약   58820  2012-12-01  2001-08-31   NaN     5   
2     (주)CMG제약   58820  2013-12-01  2001-08-31   NaN     5   
3     (주)CMG제약   58820  2014-12-01  2001-08-31   NaN     5   
4     (주)CMG제약   58820  2015-12-01  2001-08-31   NaN     5   
...        ...     ...         ...         ...   ...   ...   
9273   휴마시스(주)  205470  2020-12-01  2014-12-01   NaN     5   
9274     휴젤(주)  145020  2019-12-01  2015-12-24   NaN     5   
9275     휴젤(주)  145020  2020-12-01  2015-12-24   NaN     5   
9276   흥구석유(주)   24060  2019-12-01  1994-12-07   NaN     5   
9277   흥구석유(주)   24060  2020-12-01  1994-12-07   NaN     5   

                     산업명    매출액증가율   유형자산증가율   재고자산증가율  ...      부가가치  \
0       의료용 물질 및 의약품 제조업  1.186494 -0.286555 -0.242712  ... -0.517775   
1       의료용 물질 및 의약품 제조업 -0.465320 -0.266139 -0.145700  ... -0.570848   
2       의료용 물질 및 의약품 제조업  0.399443 -0.034331  0.368591  ... -0.459402   
3       의료용 물질 및 의약품 제조업  0.042989  0.633335 -0.160104  ... -0.458301   
4       의료용 물질 및 의약품 제조업  0.229752 -0.280476 -0.110645  ... -0.503803   
...                  ...       ...       ...       ...  ...       ...   
9273    의료용 물질 및 의약품 제조업  5.662930  1.347455  2.510801  ... -0.151711   
9274    의료용 물질 및 의약품 제조업  0.059296 -0.046260  0.113775  ...  1.299954   
9275    의료용 물질 및 의약품 제조업 -0.170016 -0.100971 -0.437478  ...  1.349171   
9276         도매 및 상품 중개업 -0.488761 -0.299172  0.793390  ... -0.392823   
9277         도매 및 상품 중개업 -0.856425 -0.378544 -0.424663  ... -0.359343   

       총자본투자효율    설비투자효율    기계투자효율     부가가치율   노동소득분배율     자본분배율     이윤분배율  \
0    -0.268715 -0.204982 -0.097181  0.001823  0.167352 -0.034998 -0.128958   
1    -0.965957 -0.239707 -0.097246 -0.455154  7.331845 -8.395971 -8.842764   
2    -0.280668 -0.160693 -0.097092  0.377872 -0.016097  0.127964  0.136844   
3    -0.300589 -0.202938 -0.097179  0.294901  0.063259  0.057470  0.125748   
4    -0.558426 -0.217252 -0.097201 -0.090083  0.704439 -0.512105 -0.358349   
...        ...       ...       ...       ...       ...       ...       ...   
9273  1.140567 -0.125778 -0.096931  0.930074 -0.576239  0.625551  0.569922   
9274 -0.272699 -0.062404 -0.097006  0.914756 -0.434150  0.499330  0.360994   
9275 -0.301727 -0.058107 -0.096969  0.907353 -0.415350  0.482630  0.330828   
9276 -0.500939 -0.145811 -0.095817 -0.354313 -0.106535  0.208302  0.265758   
9277 -0.421255 -0.140271 -0.095169 -0.325975 -0.166101  0.261216  0.306350   

      label   회계년  
0       0.0  2011  
1       0.0  2012  
2       0.0  2013  
3       0.0  2014  
4       0.0  2015  
...     ...   ...  
9273    0.0  2020  
9274    0.0  2019  
9275    0.0  2020  
9276    0.0  2019  
9277    0.0  2020  

[9278 rows x 57 columns]

In [50]:
year = df["회계년"].unique().tolist()
year

[2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020]

In [51]:
col = df.columns[7:55]
x_train = []
y_train = []
x_test = []
y_test = []

In [52]:
# train = df[df["회계년"] == 2017]
# x_train_year = train[col]
# y_train_year = train["label"]
# x_train_year, y_train_year = RandomUnderSampler(random_state=4,sampling_strategy=0.1).fit_resample(x_train_year,y_train_year)
# x_train.append(x_train_year)
# y_train.append(y_train_year)

In [53]:
col = df.columns[7:55]
x_train = []
y_train = []
x_test = []
y_test = []
for i in year:
    if i <= 2018:
        print(i)
        train = df[df["회계년"] == i].reset_index()
        x_train_year = train[col]
        y_train_year = train["label"]
        x_train_year, y_train_year = RandomUnderSampler(random_state=4, sampling_strategy=0.1).fit_resample(x_train_year,y_train_year)
        x_train.append(x_train_year)
        y_train.append(y_train_year)
 
    else:
        test = df[df["회계년"] == i].reset_index()
        x_test_year = test[col]
        y_test_year = test["label"]
        x_test_year, y_test_year = RandomUnderSampler(random_state=4, sampling_strategy=0.1).fit_resample(x_test_year,y_test_year)
        x_test.append(x_test_year)
        y_test.append(y_test_year)

2011
2012
2013
2014
2015
2016
2017
2018


In [54]:
x_train = pd.concat(x_train).reset_index(drop=True)
y_train = pd.concat(y_train).reset_index(drop=True)
x_test = pd.concat(x_test).reset_index(drop=True)
y_test = pd.concat(y_test).reset_index(drop=True)

In [55]:
x_train

매출액증가율   유형자산증가율   재고자산증가율  비유동자산증가율   유동자산증가율   자기자본증가율    총자본증가율  \
0    -0.009752  0.378358  0.085392  0.746764 -0.410100  0.083242  0.614834   
1     0.341605 -0.148572 -0.655755 -0.186907 -0.596106  1.092649 -0.384062   
2     0.968393  0.044124 -0.275544  0.139549 -0.839154 -1.010232 -0.331862   
3     0.046811 -0.432568  1.118634 -0.840229  0.698248 -0.104361 -0.401106   
4    -1.035289 -0.646941  0.149784  0.230322  0.220089 -0.902368  0.474924   
...        ...       ...       ...       ...       ...       ...       ...   
1326  0.300839 -0.125288  0.186640 -0.185466  1.328189  2.121837  0.521087   
1327  2.155467 -0.548758  0.633574 -0.930797 -1.463887 -0.801613 -1.784929   
1328 -0.399839 -0.216130 -0.172919 -0.352193 -0.573042 -0.270947 -0.640799   
1329 -1.253136 -0.581104 -1.236875  0.040130 -1.569539 -3.159782 -1.151432   
1330 -0.805976 -0.285523 -0.502718 -0.504923  5.395523 -0.767616  0.415978   

        순이익증가율   매출액총이익률   매출액순이익률  ...   유동자산회전률   당좌자산회전률      부가가치  \
0    -0.150184  1.164758  0.569152  ... -0.149928  0.113625 -0.040106   
1     6.372437  0.902971  0.427837  ... -0.276835 -0.532542 -0.476213   
2    -0.209128 -0.257369  0.247503  ... -0.794223 -0.890129 -0.502741   
3    -0.209128  0.730234  0.187813  ...  0.484604 -0.030665 -0.409629   
4    -0.209128  0.036068  0.076238  ... -0.774699 -0.670558 -0.382300   
...        ...       ...       ...  ...       ...       ...       ...   
1326  1.279152  1.257564  0.251721  ...  0.074598 -0.212595  2.611798   
1327 -0.209128 -0.073367 -0.283587  ... -1.028512 -0.977957 -0.567785   
1328 -0.209128 -1.234244  0.819721  ... -1.331135 -1.247716 -0.481676   
1329 -0.209128 -1.318466 -5.060652  ... -1.292087 -1.184981 -0.650419   
1330 -0.209128  0.632064  0.453358  ... -0.872319 -0.946590 -0.451354   

       총자본투자효율    설비투자효율    기계투자효율     부가가치율   노동소득분배율     자본분배율     이윤분배율  
0     0.434219 -0.191290 -0.096936  0.707202 -0.327089  0.404225  0.350121  
1    -0.222612 -0.214945 -0.097103  0.163680 -0.394076  0.463732  0.400694  
2     0.121740  0.031776 -0.094583  0.056201 -0.020747  0.132095  0.236708  
3     0.446171  1.799389 -0.097251  0.125896 -0.121377  0.221487  0.158311  
4    -0.548750 -0.181115 -0.096067 -0.032386  0.250270 -0.108656  0.011721  
...        ...       ...       ...       ...       ...       ...       ...  
1326  0.340304 -0.138343 -0.097142  0.462885 -0.411095  0.478850  0.187361  
1327 -0.979617 -0.241824 -0.097250 -0.485024  7.331845 -8.395971 -8.842764  
1328 -0.589162 -0.065669 -0.088050  1.103674 -0.389525  0.459689  0.397125  
1329 -1.545948 -0.270978 -0.097449 -1.486034 -0.721395 -0.124477  0.113258  
1330  0.581066 -0.103544 -0.096482  0.590788 -0.386556  0.457052  0.303730  

[1331 rows x 48 columns]

In [56]:
mda_feature=feature["mda_feature"].tolist()
logit_feature=feature["logit_feature"].tolist()
lasso_feature=feature["lasso_feature"].tolist()
ela_feature=feature["ela_feature"].tolist()
same_feature=feature["same_feature"].tolist()

In [57]:
# 성능확인 코드
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score
from sklearn.metrics import f1_score, roc_auc_score, average_precision_score


import warnings

def get_clf_eval(MDA_y_test, pred):
    confusion = confusion_matrix(MDA_y_test, pred)
    accuracy = accuracy_score(MDA_y_test, pred)
    precision = precision_score(MDA_y_test, pred)
    recall = recall_score(MDA_y_test, pred)
    roc_score = roc_auc_score(MDA_y_test, pred)
    pr_score = average_precision_score(MDA_y_test, pred)
    f1 = f1_score(MDA_y_test, pred)
    print('오차행렬')
    print(confusion)
    print('정확도: {0:.4f}, 정밀도 : {1:.4f}, 재현율:{2:.4f},F1 스코어:{3:.4f}'.format(accuracy, precision, recall, f1, roc_score))
    print('ROC 스코어: {0:.4f}, PR score : {1:.4f}'.format(roc_score, pr_score))

In [58]:
# 임계값에 따른 오차행렬및 스코어 -------->#임계값 최적 : 재현율기준(0.1)/f1기준(0.3)
from sklearn.preprocessing import Binarizer
thresholds = [0.1,0.2,0.3,0.4,0.5]

def get_eval_by_threshold(MDA_y_test, pred_proba_c1, thresholds):
    for custom_threshold in thresholds:
        binarizer = Binarizer(threshold=custom_threshold).fit(pred_proba_c1)
        custom_predict = binarizer.transform(pred_proba_c1)
        print("임곗값:", custom_threshold)
        get_clf_eval(MDA_y_test, custom_predict)
        print("---------------------------------------------------------")


In [59]:
# Roc Auc 그래프 값 확인 코드
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score
def roc_curve_plot(MDA_y_test, pred_proba_c1):
    fprs, tprs, thresholds = roc_curve(MDA_y_test, pred_proba_c1)
    
    plt.plot(fprs, tprs, label='ROC')
    plt.plot([0,1],[0,1], 'k--', label = 'Random')
    
    start, end= plt.xlim()
    plt.xticks(np.round(np.arange(start, end, 0.1),2))
    plt.xlim(0,1); plt.ylim(0,1)
    plt.xlabel('FPR(1-Sensitivity)'); plt.ylabel('TPR(Recall)')
    plt.legend()
    plt.show()

In [60]:
mda_x_train = x_train[mda_feature].reset_index(drop='index')
mda_x_test = x_test[mda_feature].reset_index(drop='index')
mda_y_train = y_train
mda_y_test = y_test 

In [61]:
logit_x_train = x_train[logit_feature].reset_index(drop='index')
logit_x_test = x_test[logit_feature].reset_index(drop='index')
logit_y_train = y_train
logit_y_test = y_test 

In [62]:
lasso_x_train = x_train[lasso_feature].reset_index(drop='index')
lasso_x_test = x_test[lasso_feature].reset_index(drop='index')
lasso_y_train = y_train
lasso_y_test = y_test 

In [63]:
ela_x_train = x_train[ela_feature].reset_index(drop='index')
ela_x_test = x_test[ela_feature].reset_index(drop='index')
ela_y_train = y_train
ela_y_test = y_test 

In [64]:
same_x_train = x_train[same_feature].reset_index(drop='index')
same_x_test = x_test[same_feature].reset_index(drop='index')
same_y_train = y_train
same_y_test = y_test 

In [65]:
fea_x_train = [mda_x_train, logit_x_train, lasso_x_train, ela_x_train, same_x_train]
fea_y_train = [mda_y_train, logit_y_train, lasso_y_train, ela_y_train, same_y_train]
fea_x_test = [mda_x_test, logit_x_test, lasso_x_test, ela_x_test, same_x_test]
fea_y_test = [mda_y_test, logit_y_test, lasso_y_test, ela_y_test, same_y_test]
fea = ["mda","logit","lasso","ela","same"]

In [66]:
# 1-1 LDA 
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
lda_clf = LinearDiscriminantAnalysis()
for x_train,y_train,x_test,y_test,feature in zip(fea_x_train,fea_y_train,fea_x_test, fea_y_test, fea):
    lda_clf.fit(x_train, y_train)
    lda_pred = lda_clf.predict(x_test)
    lda_pred_proba = lda_clf.predict_proba(x_test)
    print(feature,"lda") 
    get_clf_eval(y_test, lda_pred)
    get_eval_by_threshold(y_test , lda_pred_proba[:,1].reshape(-1,1), thresholds)



mda lda
오차행렬
[[483  17]
 [ 27  23]]
정확도: 0.9200, 정밀도 : 0.5750, 재현율:0.4600,F1 스코어:0.5111
ROC 스코어: 0.7130, PR score : 0.3136
임곗값: 0.1
오차행렬
[[436  64]
 [ 20  30]]
정확도: 0.8473, 정밀도 : 0.3191, 재현율:0.6000,F1 스코어:0.4167
ROC 스코어: 0.7360, PR score : 0.2279
---------------------------------------------------------
임곗값: 0.2
오차행렬
[[457  43]
 [ 24  26]]
정확도: 0.8782, 정밀도 : 0.3768, 재현율:0.5200,F1 스코어:0.4370
ROC 스코어: 0.7170, PR score : 0.2396
---------------------------------------------------------
임곗값: 0.3
오차행렬
[[469  31]
 [ 25  25]]
정확도: 0.8982, 정밀도 : 0.4464, 재현율:0.5000,F1 스코어:0.4717
ROC 스코어: 0.7190, PR score : 0.2687
---------------------------------------------------------
임곗값: 0.4
오차행렬
[[478  22]
 [ 26  24]]
정확도: 0.9127, 정밀도 : 0.5217, 재현율:0.4800,F1 스코어:0.5000
ROC 스코어: 0.7180, PR score : 0.2977
---------------------------------------------------------
임곗값: 0.5
오차행렬
[[483  17]
 [ 27  23]]
정확도: 0.9200, 정밀도 : 0.5750, 재현율:0.4600,F1 스코어:0.5111
ROC 스코어: 0.7130, PR score : 0.3136
-------------------------

In [67]:
# 1-2 디시전트리 
from sklearn.tree import DecisionTreeClassifier 
dt_clf = DecisionTreeClassifier(random_state=52)
for x_train,y_train,x_test,y_test,feature in zip(fea_x_train,fea_y_train,fea_x_test, fea_y_test, fea):
    dt_clf.fit(x_train, y_train)
    dt_pred = dt_clf.predict(x_test)
    dt_pred_proba = dt_clf.predict_proba(x_test)   
    print(feature,"디시전트리") 
    get_clf_eval(y_test, dt_pred)
    get_eval_by_threshold(y_test , dt_pred_proba[:,1].reshape(-1,1), thresholds)
    


mda 디시전트리
오차행렬
[[452  48]
 [ 26  24]]
정확도: 0.8655, 정밀도 : 0.3333, 재현율:0.4800,F1 스코어:0.3934
ROC 스코어: 0.6920, PR score : 0.2073
임곗값: 0.1
오차행렬
[[452  48]
 [ 26  24]]
정확도: 0.8655, 정밀도 : 0.3333, 재현율:0.4800,F1 스코어:0.3934
ROC 스코어: 0.6920, PR score : 0.2073
---------------------------------------------------------
임곗값: 0.2
오차행렬
[[452  48]
 [ 26  24]]
정확도: 0.8655, 정밀도 : 0.3333, 재현율:0.4800,F1 스코어:0.3934
ROC 스코어: 0.6920, PR score : 0.2073
---------------------------------------------------------
임곗값: 0.3
오차행렬
[[452  48]
 [ 26  24]]
정확도: 0.8655, 정밀도 : 0.3333, 재현율:0.4800,F1 스코어:0.3934
ROC 스코어: 0.6920, PR score : 0.2073
---------------------------------------------------------
임곗값: 0.4
오차행렬
[[452  48]
 [ 26  24]]
정확도: 0.8655, 정밀도 : 0.3333, 재현율:0.4800,F1 스코어:0.3934
ROC 스코어: 0.6920, PR score : 0.2073
---------------------------------------------------------
임곗값: 0.5
오차행렬
[[452  48]
 [ 26  24]]
정확도: 0.8655, 정밀도 : 0.3333, 재현율:0.4800,F1 스코어:0.3934
ROC 스코어: 0.6920, PR score : 0.2073
-----------------------

In [68]:
from sklearn.tree import DecisionTreeClassifier 
dt_clf = DecisionTreeClassifier(random_state=52)
from sklearn.model_selection import GridSearchCV
tree = DecisionTreeClassifier(random_state=52)
for x_train,y_train,x_test,y_test,feature in zip(fea_x_train,fea_y_train,fea_x_test, fea_y_test, fea):
    # key: 하이퍼파라미터 명; value: [후보값들] 을 리스트로 전달
    param_grid = {
      'criterion': ['entropy', 'gini'],
               'max_depth': [2,4,6,8],
               'max_features': ['auto', 'sqrt'],
               'min_samples_leaf': [4,6,8,10],
               'min_samples_split': [4,6,8,10]}
    grid_search = GridSearchCV(tree
                            , param_grid = param_grid
                            , cv = 5 #교차검증시 fold 개수; n번의 교차검증; 데이터들이 돌아가면서 하나씩 검증(validation)에 사용되어 일반화하는 것; 데이터가 많지 않을 때 보통 쓰인다고 함
                            , n_jobs = -1)  #-1: 모든 코어 사용

    grid_search.fit(x_train, y_train)

    # 최선의 결과 출력
    print('피처:{2} 최적 하이퍼 파라미터 :{0}, 최적 평균 정확도 :{1:.3f}'.format(grid_search.best_params_, grid_search.best_score_, feature))
    a = grid_search.best_params_
    keys=list(a.keys())
    values = list(a.values())

    dt_clf_best = DecisionTreeClassifier(random_state=52,criterion = values[0], max_depth = values[1],max_features=values[2], min_samples_leaf=values[3], min_samples_split=values[4])
    dt_clf_best.fit(x_train, y_train)
    dt_best_pred = dt_clf_best.predict(x_test)
    dt_best_pred_proba = dt_clf_best.predict_proba(x_test)   

    print(feature,"디시전트리 파라미터적용") 
    get_clf_eval(y_test, dt_best_pred)
    get_eval_by_threshold(y_test ,dt_best_pred_proba[:,1].reshape(-1,1), thresholds)


피처:mda 최적 하이퍼 파라미터 :{'criterion': 'entropy', 'max_depth': 4, 'max_features': 'auto', 'min_samples_leaf': 8, 'min_samples_split': 4}, 최적 평균 정확도 :0.928
mda 디시전트리 파라미터적용
오차행렬
[[479  21]
 [ 31  19]]
정확도: 0.9055, 정밀도 : 0.4750, 재현율:0.3800,F1 스코어:0.4222
ROC 스코어: 0.6690, PR score : 0.2369
임곗값: 0.1
오차행렬
[[414  86]
 [ 25  25]]
정확도: 0.7982, 정밀도 : 0.2252, 재현율:0.5000,F1 스코어:0.3106
ROC 스코어: 0.6640, PR score : 0.1581
---------------------------------------------------------
임곗값: 0.2
오차행렬
[[453  47]
 [ 29  21]]
정확도: 0.8618, 정밀도 : 0.3088, 재현율:0.4200,F1 스코어:0.3559
ROC 스코어: 0.6630, PR score : 0.1824
---------------------------------------------------------
임곗값: 0.3
오차행렬
[[479  21]
 [ 31  19]]
정확도: 0.9055, 정밀도 : 0.4750, 재현율:0.3800,F1 스코어:0.4222
ROC 스코어: 0.6690, PR score : 0.2369
---------------------------------------------------------
임곗값: 0.4
오차행렬
[[479  21]
 [ 31  19]]
정확도: 0.9055, 정밀도 : 0.4750, 재현율:0.3800,F1 스코어:0.4222
ROC 스코어: 0.6690, PR score : 0.2369
------------------------------------------------

In [69]:
# 1-3 랜덤포레스트 구현 
from sklearn.ensemble import RandomForestClassifier
rf_clf = RandomForestClassifier(random_state=52)    
for x_train,y_train,x_test,y_test,feature in zip(fea_x_train,fea_y_train,fea_x_test, fea_y_test, fea):
    rf_clf.fit(x_train, y_train)
    rf_pred = rf_clf.predict(x_test)
    rf_pred_proba = rf_clf.predict_proba(x_test)
    print(feature,"랜덤포레스트") 
    get_clf_eval(y_test, rf_pred)
    get_eval_by_threshold(y_test , rf_pred_proba[:,1].reshape(-1,1), thresholds)
    


mda 랜덤포레스트
오차행렬
[[488  12]
 [ 32  18]]
정확도: 0.9200, 정밀도 : 0.6000, 재현율:0.3600,F1 스코어:0.4500
ROC 스코어: 0.6680, PR score : 0.2742
임곗값: 0.1
오차행렬
[[383 117]
 [ 13  37]]
정확도: 0.7636, 정밀도 : 0.2403, 재현율:0.7400,F1 스코어:0.3627
ROC 스코어: 0.7530, PR score : 0.2014
---------------------------------------------------------
임곗값: 0.2
오차행렬
[[436  64]
 [ 17  33]]
정확도: 0.8527, 정밀도 : 0.3402, 재현율:0.6600,F1 스코어:0.4490
ROC 스코어: 0.7660, PR score : 0.2554
---------------------------------------------------------
임곗값: 0.3
오차행렬
[[467  33]
 [ 24  26]]
정확도: 0.8964, 정밀도 : 0.4407, 재현율:0.5200,F1 스코어:0.4771
ROC 스코어: 0.7270, PR score : 0.2728
---------------------------------------------------------
임곗값: 0.4
오차행렬
[[484  16]
 [ 28  22]]
정확도: 0.9200, 정밀도 : 0.5789, 재현율:0.4400,F1 스코어:0.5000
ROC 스코어: 0.7040, PR score : 0.3056
---------------------------------------------------------
임곗값: 0.5
오차행렬
[[488  12]
 [ 32  18]]
정확도: 0.9200, 정밀도 : 0.6000, 재현율:0.3600,F1 스코어:0.4500
ROC 스코어: 0.6680, PR score : 0.2742
----------------------

In [70]:
# 하이퍼파라미터 Grid-Search
from sklearn.model_selection import GridSearchCV

    # 탐색 범위 정의
for x_train,y_train,x_test,y_test,feature in zip(fea_x_train,fea_y_train,fea_x_test, fea_y_test, fea):
    grid_search = {'criterion': ['entropy', 'gini'],
                'max_depth': [2,4,6,8],
                'max_features': ['auto', 'sqrt'],
                'min_samples_leaf': [4,6,8,10],
                'min_samples_split': [4,6,8,10],
                'n_estimators': [20,40,60,80,100]}

    model = RandomForestClassifier(random_state=52)
    grid_search = GridSearchCV(estimator = model, param_grid = grid_search, 
                                cv = 5,verbose=0, n_jobs = -1)
    grid_search.fit(x_train,y_train)

    # 최선의 결과 출력
    print('최적 하이퍼 파라미터 :{0}, 최적 평균 정확도 :{1:.3f}'.format(grid_search.best_params_, grid_search.best_score_))
    a = grid_search.best_params_
    keys=list(a.keys())
    values = list(a.values())

    rf_clf_best = RandomForestClassifier(random_state=52,criterion = values[0], max_depth = values[1],max_features=values[2], min_samples_leaf=values[3],  min_samples_split=values[4],n_estimators=values[5])
    rf_clf_best.fit(x_train, y_train)
    rf_best_pred = rf_clf_best.predict(x_test)
    rf_best_pred_proba = rf_clf_best.predict_proba(x_test)   

    print(feature,"디시전트리 파라미터적용") 
    get_clf_eval(y_test, rf_best_pred)
    get_eval_by_threshold(y_test ,rf_best_pred_proba[:,1].reshape(-1,1), thresholds)

최적 하이퍼 파라미터 :{'criterion': 'entropy', 'max_depth': 8, 'max_features': 'auto', 'min_samples_leaf': 6, 'min_samples_split': 4, 'n_estimators': 60}, 최적 평균 정확도 :0.937
mda 디시전트리 파라미터적용
오차행렬
[[494   6]
 [ 35  15]]
정확도: 0.9255, 정밀도 : 0.7143, 재현율:0.3000,F1 스코어:0.4225
ROC 스코어: 0.6440, PR score : 0.2779
임곗값: 0.1
오차행렬
[[386 114]
 [ 12  38]]
정확도: 0.7709, 정밀도 : 0.2500, 재현율:0.7600,F1 스코어:0.3762
ROC 스코어: 0.7660, PR score : 0.2118
---------------------------------------------------------
임곗값: 0.2
오차행렬
[[442  58]
 [ 18  32]]
정확도: 0.8618, 정밀도 : 0.3556, 재현율:0.6400,F1 스코어:0.4571
ROC 스코어: 0.7620, PR score : 0.2603
---------------------------------------------------------
임곗값: 0.3
오차행렬
[[467  33]
 [ 22  28]]
정확도: 0.9000, 정밀도 : 0.4590, 재현율:0.5600,F1 스코어:0.5045
ROC 스코어: 0.7470, PR score : 0.2970
---------------------------------------------------------
임곗값: 0.4
오차행렬
[[482  18]
 [ 31  19]]
정확도: 0.9109, 정밀도 : 0.5135, 재현율:0.3800,F1 스코어:0.4368
ROC 스코어: 0.6720, PR score : 0.2515
-----------------------------------

In [71]:
# 1-4 로지스틱회귀
from sklearn.linear_model import LogisticRegression
lr_clf = LogisticRegression()
for x_train,y_train,x_test,y_test,feature in zip(fea_x_train,fea_y_train,fea_x_test, fea_y_test, fea):
    lr_clf.fit(x_train, y_train)
    lr_pred = lr_clf.predict(x_test)
    lr_pred_proba = lr_clf.predict_proba(x_test)
    print(feature,"로지스틱회귀") 
    get_clf_eval(y_test, lr_pred)
    get_eval_by_threshold(y_test , lr_pred_proba[:,1].reshape(-1,1), thresholds)
    

mda 로지스틱회귀
오차행렬
[[491   9]
 [ 30  20]]
정확도: 0.9291, 정밀도 : 0.6897, 재현율:0.4000,F1 스코어:0.5063
ROC 스코어: 0.6910, PR score : 0.3304
임곗값: 0.1
오차행렬
[[405  95]
 [ 15  35]]
정확도: 0.8000, 정밀도 : 0.2692, 재현율:0.7000,F1 스코어:0.3889
ROC 스코어: 0.7550, PR score : 0.2157
---------------------------------------------------------
임곗값: 0.2
오차행렬
[[461  39]
 [ 22  28]]
정확도: 0.8891, 정밀도 : 0.4179, 재현율:0.5600,F1 스코어:0.4786
ROC 스코어: 0.7410, PR score : 0.2740
---------------------------------------------------------
임곗값: 0.3
오차행렬
[[482  18]
 [ 25  25]]
정확도: 0.9218, 정밀도 : 0.5814, 재현율:0.5000,F1 스코어:0.5376
ROC 스코어: 0.7320, PR score : 0.3362
---------------------------------------------------------
임곗값: 0.4
오차행렬
[[487  13]
 [ 27  23]]
정확도: 0.9273, 정밀도 : 0.6389, 재현율:0.4600,F1 스코어:0.5349
ROC 스코어: 0.7170, PR score : 0.3430
---------------------------------------------------------
임곗값: 0.5
오차행렬
[[491   9]
 [ 30  20]]
정확도: 0.9291, 정밀도 : 0.6897, 재현율:0.4000,F1 스코어:0.5063
ROC 스코어: 0.6910, PR score : 0.3304
----------------------

In [72]:
#로지스틱 회귀 최적 하이퍼 파라미터
from sklearn.model_selection import GridSearchCV

for x_train,y_train,x_test,y_test,feature in zip(fea_x_train,fea_y_train,fea_x_test, fea_y_test, fea):
    params = {'penalty': ['l2','l1','elasticnet','None'],
            'C':[0.01,0.1,1,3,5,10]}

    grid_search = GridSearchCV(lr_clf, param_grid=params, scoring='accuracy', cv=5)
    grid_search.fit(x_train,y_train)
    print('최적 하이퍼 파라미어:{0}, 최적 평균 정확도:{1:.3f}'.format(grid_search.best_params_, grid_search.best_score_))

    a = grid_search.best_params_
    keys=list(a.keys())
    values = list(a.values())

    lr_clf_best = LogisticRegression(penalty= values[1], C=values[0])
    lr_clf_best.fit(x_train, y_train)
    lr_best_pred = lr_clf_best.predict(x_test)
    lr_best_pred_proba = lr_clf_best.predict_proba(x_test)   

    print(feature,"로지스틱회귀 파라미터적용") 
    get_clf_eval(y_test, lr_best_pred)
    get_eval_by_threshold(y_test ,lr_best_pred_proba[:,1].reshape(-1,1), thresholds)


최적 하이퍼 파라미어:{'C': 0.1, 'penalty': 'l2'}, 최적 평균 정확도:0.929
mda 로지스틱회귀 파라미터적용
오차행렬
[[491   9]
 [ 31  19]]
정확도: 0.9273, 정밀도 : 0.6786, 재현율:0.3800,F1 스코어:0.4872
ROC 스코어: 0.6810, PR score : 0.3142
임곗값: 0.1
오차행렬
[[406  94]
 [ 16  34]]
정확도: 0.8000, 정밀도 : 0.2656, 재현율:0.6800,F1 스코어:0.3820
ROC 스코어: 0.7460, PR score : 0.2097
---------------------------------------------------------
임곗값: 0.2
오차행렬
[[460  40]
 [ 22  28]]
정확도: 0.8873, 정밀도 : 0.4118, 재현율:0.5600,F1 스코어:0.4746
ROC 스코어: 0.7400, PR score : 0.2706
---------------------------------------------------------
임곗값: 0.3
오차행렬
[[485  15]
 [ 25  25]]
정확도: 0.9273, 정밀도 : 0.6250, 재현율:0.5000,F1 스코어:0.5556
ROC 스코어: 0.7350, PR score : 0.3580
---------------------------------------------------------
임곗값: 0.4
오차행렬
[[490  10]
 [ 27  23]]
정확도: 0.9327, 정밀도 : 0.6970, 재현율:0.4600,F1 스코어:0.5542
ROC 스코어: 0.7200, PR score : 0.3697
---------------------------------------------------------
임곗값: 0.5
오차행렬
[[491   9]
 [ 31  19]]
정확도: 0.9273, 정밀도 : 0.6786, 재현율:0.3800,F1 스코어:

In [73]:
# 1-5 KNN 
from sklearn.neighbors import KNeighborsClassifier
knn_clf = KNeighborsClassifier(n_neighbors=5)
for x_train,y_train,x_test,y_test,feature in zip(fea_x_train,fea_y_train,fea_x_test, fea_y_test, fea):

    knn_clf.fit(x_train, y_train)
    knn_pred = knn_clf.predict(x_test)
    knn_pred_proba = knn_clf.predict_proba(x_test)
    print(feature,"KNN") 
    get_clf_eval(y_test, knn_pred)
    get_eval_by_threshold(y_test , knn_pred_proba[:,1].reshape(-1,1), thresholds)



mda KNN
오차행렬
[[491   9]
 [ 33  17]]
정확도: 0.9236, 정밀도 : 0.6538, 재현율:0.3400,F1 스코어:0.4474
ROC 스코어: 0.6610, PR score : 0.2823
임곗값: 0.1
오차행렬
[[395 105]
 [ 20  30]]
정확도: 0.7727, 정밀도 : 0.2222, 재현율:0.6000,F1 스코어:0.3243
ROC 스코어: 0.6950, PR score : 0.1697
---------------------------------------------------------
임곗값: 0.2
오차행렬
[[467  33]
 [ 30  20]]
정확도: 0.8855, 정밀도 : 0.3774, 재현율:0.4000,F1 스코어:0.3883
ROC 스코어: 0.6670, PR score : 0.2055
---------------------------------------------------------
임곗값: 0.3
오차행렬
[[467  33]
 [ 30  20]]
정확도: 0.8855, 정밀도 : 0.3774, 재현율:0.4000,F1 스코어:0.3883
ROC 스코어: 0.6670, PR score : 0.2055
---------------------------------------------------------
임곗값: 0.4
오차행렬
[[491   9]
 [ 33  17]]
정확도: 0.9236, 정밀도 : 0.6538, 재현율:0.3400,F1 스코어:0.4474
ROC 스코어: 0.6610, PR score : 0.2823
---------------------------------------------------------
임곗값: 0.5
오차행렬
[[491   9]
 [ 33  17]]
정확도: 0.9236, 정밀도 : 0.6538, 재현율:0.3400,F1 스코어:0.4474
ROC 스코어: 0.6610, PR score : 0.2823
-------------------------

In [74]:
# knn 파라미터 구하기
from sklearn.metrics import accuracy_score
acc = []
for x_train,y_train,x_test,y_test,feature in zip(fea_x_train,fea_y_train,fea_x_test, fea_y_test, fea):
    for k in range(1,20):
        knn_clf = KNeighborsClassifier(n_neighbors=k)
        knn_clf.fit(x_train, y_train)
        knn_pred = knn_clf.predict(x_test)
        knn_score=accuracy_score(y_test,knn_pred)

        acc.append(knn_score)
    int = acc.index(max(acc))+1
    print("최적거리")
    print(int)

    knn_clf_best =KNeighborsClassifier(n_neighbors=int)
    knn_clf_best.fit(x_train, y_train)
    knn_best_pred = knn_clf_best.predict(x_test)
    knn_best_pred_proba = knn_clf_best.predict_proba(x_test)   

    print(feature,"KNN 파라미터적용") 
    get_clf_eval(y_test, knn_best_pred)
    get_eval_by_threshold(y_test ,knn_best_pred_proba[:,1].reshape(-1,1), thresholds)      


최적거리
4
mda KNN 파라미터적용
오차행렬
[[494   6]
 [ 33  17]]
정확도: 0.9291, 정밀도 : 0.7391, 재현율:0.3400,F1 스코어:0.4658
ROC 스코어: 0.6640, PR score : 0.3113
임곗값: 0.1
오차행렬
[[410  90]
 [ 23  27]]
정확도: 0.7945, 정밀도 : 0.2308, 재현율:0.5400,F1 스코어:0.3234
ROC 스코어: 0.6800, PR score : 0.1664
---------------------------------------------------------
임곗값: 0.2
오차행렬
[[410  90]
 [ 23  27]]
정확도: 0.7945, 정밀도 : 0.2308, 재현율:0.5400,F1 스코어:0.3234
ROC 스코어: 0.6800, PR score : 0.1664
---------------------------------------------------------
임곗값: 0.3
오차행렬
[[476  24]
 [ 31  19]]
정확도: 0.9000, 정밀도 : 0.4419, 재현율:0.3800,F1 스코어:0.4086
ROC 스코어: 0.6660, PR score : 0.2243
---------------------------------------------------------
임곗값: 0.4
오차행렬
[[476  24]
 [ 31  19]]
정확도: 0.9000, 정밀도 : 0.4419, 재현율:0.3800,F1 스코어:0.4086
ROC 스코어: 0.6660, PR score : 0.2243
---------------------------------------------------------
임곗값: 0.5
오차행렬
[[494   6]
 [ 33  17]]
정확도: 0.9291, 정밀도 : 0.7391, 재현율:0.3400,F1 스코어:0.4658
ROC 스코어: 0.6640, PR score : 0.3113
-----------

In [75]:
# 1-5 xgboost
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
import xgboost as xgb ## XGBoost 불러오기
from xgboost import plot_importance 

xgb_wrapper = XGBClassifier()
for x_train,y_train,x_test,y_test,feature in zip(fea_x_train,fea_y_train,fea_x_test, fea_y_test, fea):

    xgb_wrapper.fit(x_train, y_train, verbose = True)
    xgb_wrapper.fit(x_train, y_train)
    xgb_pred = xgb_wrapper.predict(x_test)
    xgb_pred_proba = xgb_wrapper.predict_proba(x_test)
    print(feature,"XGB") 
    get_clf_eval(y_test, xgb_pred)
    get_eval_by_threshold(y_test , xgb_pred_proba[:,1].reshape(-1,1), thresholds)

mda XGB
오차행렬
[[490  10]
 [ 30  20]]
정확도: 0.9273, 정밀도 : 0.6667, 재현율:0.4000,F1 스코어:0.5000
ROC 스코어: 0.6900, PR score : 0.3212
임곗값: 0.1
오차행렬
[[464  36]
 [ 23  27]]
정확도: 0.8927, 정밀도 : 0.4286, 재현율:0.5400,F1 스코어:0.4779
ROC 스코어: 0.7340, PR score : 0.2732
---------------------------------------------------------
임곗값: 0.2
오차행렬
[[475  25]
 [ 24  26]]
정확도: 0.9109, 정밀도 : 0.5098, 재현율:0.5200,F1 스코어:0.5149
ROC 스코어: 0.7350, PR score : 0.3087
---------------------------------------------------------
임곗값: 0.3
오차행렬
[[481  19]
 [ 27  23]]
정확도: 0.9164, 정밀도 : 0.5476, 재현율:0.4600,F1 스코어:0.5000
ROC 스코어: 0.7110, PR score : 0.3010
---------------------------------------------------------
임곗값: 0.4
오차행렬
[[488  12]
 [ 29  21]]
정확도: 0.9255, 정밀도 : 0.6364, 재현율:0.4200,F1 스코어:0.5060
ROC 스코어: 0.6980, PR score : 0.3200
---------------------------------------------------------
임곗값: 0.5
오차행렬
[[490  10]
 [ 30  20]]
정확도: 0.9273, 정밀도 : 0.6667, 재현율:0.4000,F1 스코어:0.5000
ROC 스코어: 0.6900, PR score : 0.3212
-------------------------

In [ ]:
values[1]

'l2'

In [ ]:
#xgb 최적 하이퍼 파라미터
from sklearn.model_selection import GridSearchCV

xgb_wrapper
for x_train,y_train,x_test,y_test,feature in zip(fea_x_train,fea_y_train,fea_x_test, fea_y_test, fea):
    params = {
            'n_estimators':[40,43,46,50],
            'learning_rate':[0.03,0.05,0.04],
            'max_depth' : [0.8,1,2,3,4]
            }

    grid_clf = GridSearchCV(xgb_wrapper, param_grid=params, scoring='accuracy', cv=5)
    grid_clf.fit(x_train,y_train)
    print('최적 하이퍼 파라미어:{0}, 최적 평균 정확도:{1:.3f}'.format(grid_clf.best_params_, grid_clf.best_score_))

    a = grid_clf.best_params_
    keys=list(a.keys())
    values = list(a.values())
    xgb_clf_best = XGBClassifier( learning_rate=values[0],max_depth=values[1],n_estimators= values[2])
    xgb_clf_best.fit(x_train, y_train)
    xgb_best_pred = xgb_clf_best.predict(x_test)
    xgb_best_pred_proba = xgb_clf_best.predict_proba(x_test)   

    print(feature,"XGB 파라미터적용") 
    get_clf_eval(y_test, xgb_best_pred)
    get_eval_by_threshold(y_test ,xgb_best_pred_proba[:,1].reshape(-1,1), thresholds)

최적 하이퍼 파라미어:{'learning_rate': 0.05, 'max_depth': 1, 'n_estimators': 50}, 최적 평균 정확도:0.932
mda XGB 파라미터적용
오차행렬
[[498   2]
 [ 37  13]]
정확도: 0.9291, 정밀도 : 0.8667, 재현율:0.2600,F1 스코어:0.4000
ROC 스코어: 0.6280, PR score : 0.2926
임곗값: 0.1
오차행렬
[[385 115]
 [ 12  38]]
정확도: 0.7691, 정밀도 : 0.2484, 재현율:0.7600,F1 스코어:0.3744
ROC 스코어: 0.7650, PR score : 0.2106
---------------------------------------------------------
임곗값: 0.2
오차행렬
[[458  42]
 [ 20  30]]
정확도: 0.8873, 정밀도 : 0.4167, 재현율:0.6000,F1 스코어:0.4918
ROC 스코어: 0.7580, PR score : 0.2864
---------------------------------------------------------
임곗값: 0.3
오차행렬
[[470  30]
 [ 23  27]]
정확도: 0.9036, 정밀도 : 0.4737, 재현율:0.5400,F1 스코어:0.5047
ROC 스코어: 0.7400, PR score : 0.2976
---------------------------------------------------------
임곗값: 0.4
오차행렬
[[488  12]
 [ 31  19]]
정확도: 0.9218, 정밀도 : 0.6129, 재현율:0.3800,F1 스코어:0.4691
ROC 스코어: 0.6780, PR score : 0.2893
---------------------------------------------------------
임곗값: 0.5
오차행렬
[[498   2]
 [ 37  13]]
정확도: 0.9291, 정밀도