# 2. Tomek link


In [34]:
# 필요 라이브러리 import 
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
import warnings
warnings.filterwarnings(action='ignore') 

In [35]:
from imblearn.under_sampling import RandomUnderSampler, TomekLinks
from imblearn.over_sampling import RandomOverSampler
from imblearn.over_sampling import SMOTE

from sklearn.datasets import make_classification
from collections import Counter

from matplotlib import pyplot as plt
import seaborn as sns

In [36]:
df = pd.read_csv("./데이터자료/9-2. Std 데이터셋.csv")
feature = pd.read_csv("./데이터자료/8-2. Std feature.csv")
df

회사명   거래소코드        회계년도         상장일 상장폐지일  소속코드  \
0     (주)CMG제약   58820  2011-12-01  2001-08-31   NaN     5   
1     (주)CMG제약   58820  2012-12-01  2001-08-31   NaN     5   
2     (주)CMG제약   58820  2013-12-01  2001-08-31   NaN     5   
3     (주)CMG제약   58820  2014-12-01  2001-08-31   NaN     5   
4     (주)CMG제약   58820  2015-12-01  2001-08-31   NaN     5   
...        ...     ...         ...         ...   ...   ...   
9273   휴마시스(주)  205470  2020-12-01  2014-12-01   NaN     5   
9274     휴젤(주)  145020  2019-12-01  2015-12-24   NaN     5   
9275     휴젤(주)  145020  2020-12-01  2015-12-24   NaN     5   
9276   흥구석유(주)   24060  2019-12-01  1994-12-07   NaN     5   
9277   흥구석유(주)   24060  2020-12-01  1994-12-07   NaN     5   

                     산업명    매출액증가율   유형자산증가율   재고자산증가율  ...      부가가치  \
0       의료용 물질 및 의약품 제조업  1.186494 -0.286555 -0.242712  ... -0.517775   
1       의료용 물질 및 의약품 제조업 -0.465320 -0.266139 -0.145700  ... -0.570848   
2       의료용 물질 및 의약품 제조업  0.399443 -0.034331  0.368591  ... -0.459402   
3       의료용 물질 및 의약품 제조업  0.042989  0.633335 -0.160104  ... -0.458301   
4       의료용 물질 및 의약품 제조업  0.229752 -0.280476 -0.110645  ... -0.503803   
...                  ...       ...       ...       ...  ...       ...   
9273    의료용 물질 및 의약품 제조업  5.662930  1.347455  2.510801  ... -0.151711   
9274    의료용 물질 및 의약품 제조업  0.059296 -0.046260  0.113775  ...  1.299954   
9275    의료용 물질 및 의약품 제조업 -0.170016 -0.100971 -0.437478  ...  1.349171   
9276         도매 및 상품 중개업 -0.488761 -0.299172  0.793390  ... -0.392823   
9277         도매 및 상품 중개업 -0.856425 -0.378544 -0.424663  ... -0.359343   

       총자본투자효율    설비투자효율    기계투자효율     부가가치율   노동소득분배율     자본분배율     이윤분배율  \
0    -0.268715 -0.204982 -0.097181  0.001823  0.167352 -0.034998 -0.128958   
1    -0.965957 -0.239707 -0.097246 -0.455154  7.331845 -8.395971 -8.842764   
2    -0.280668 -0.160693 -0.097092  0.377872 -0.016097  0.127964  0.136844   
3    -0.300589 -0.202938 -0.097179  0.294901  0.063259  0.057470  0.125748   
4    -0.558426 -0.217252 -0.097201 -0.090083  0.704439 -0.512105 -0.358349   
...        ...       ...       ...       ...       ...       ...       ...   
9273  1.140567 -0.125778 -0.096931  0.930074 -0.576239  0.625551  0.569922   
9274 -0.272699 -0.062404 -0.097006  0.914756 -0.434150  0.499330  0.360994   
9275 -0.301727 -0.058107 -0.096969  0.907353 -0.415350  0.482630  0.330828   
9276 -0.500939 -0.145811 -0.095817 -0.354313 -0.106535  0.208302  0.265758   
9277 -0.421255 -0.140271 -0.095169 -0.325975 -0.166101  0.261216  0.306350   

      label   회계년  
0       0.0  2011  
1       0.0  2012  
2       0.0  2013  
3       0.0  2014  
4       0.0  2015  
...     ...   ...  
9273    0.0  2020  
9274    0.0  2019  
9275    0.0  2020  
9276    0.0  2019  
9277    0.0  2020  

[9278 rows x 57 columns]

In [37]:
year = df["회계년"].unique().tolist()
year

[2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020]

In [38]:
col = df.columns[7:55]
x_train = []
y_train = []
x_test = []
y_test = []

In [39]:
# train = df[df["회계년"] == 2017]
# x_train_year = train[col]
# y_train_year = train["label"]
# x_train_year, y_train_year = RandomUnderSampler(random_state=4,sampling_strategy=0.1).fit_resample(x_train_year,y_train_year)
# x_train.append(x_train_year)
# y_train.append(y_train_year)

In [40]:
col = df.columns[7:55]
x_train = []
y_train = []
x_test = []
y_test = []
for i in year:
    if i <= 2018:
        print(i)
        train = df[df["회계년"] == i].reset_index()
        x_train_year = train[col]
        y_train_year = train["label"]
        x_train_year, y_train_year = TomekLinks().fit_resample(x_train_year,y_train_year)
        x_train.append(x_train_year)
        y_train.append(y_train_year)
 
    else:
        test = df[df["회계년"] == i].reset_index()
        x_test_year = test[col]
        y_test_year = test["label"]
        x_test.append(x_test_year)
        y_test.append(y_test_year)

2011
2012
2013
2014
2015
2016
2017
2018


In [41]:
x_train = pd.concat(x_train).reset_index(drop=True)
y_train = pd.concat(y_train).reset_index(drop=True)
x_test = pd.concat(x_test).reset_index(drop=True)
y_test = pd.concat(y_test).reset_index(drop=True)

In [42]:
x_train

매출액증가율   유형자산증가율   재고자산증가율  비유동자산증가율   유동자산증가율   자기자본증가율    총자본증가율  \
0     1.186494 -0.286555 -0.242712 -0.566673  0.174207 -0.368612 -0.262973   
1     0.300584  0.100212  0.063575  0.331182 -0.168292 -0.550961  0.120535   
2     0.515628 -0.087322 -0.798943  0.151899  0.324500  0.643577  0.474924   
3     0.209623 -0.020338  0.356835  0.117730  0.335908  0.504498  0.486998   
4    -0.400093 -0.499552 -0.298102 -0.617309  0.557132 -0.190899 -0.204736   
...        ...       ...       ...       ...       ...       ...       ...   
6885 -0.260213 -0.279329 -0.119329 -0.342930 -0.250383 -0.209752 -0.347486   
6886 -0.361110 -0.442661 -0.719830 -0.353428  0.073020 -0.594848  0.102425   
6887 -1.703353 -0.039492 -0.452941 -1.520104 -0.537576 -0.200790 -1.708583   
6888 -0.246199 -0.186996  0.202633  1.035551 -0.243439 -0.018441  0.087866   
6889 -0.075489 -0.223012 -0.715699 -0.344371 -0.788809 -0.275583 -0.542436   

        순이익증가율   매출액총이익률   매출액순이익률  ...   유동자산회전률   당좌자산회전률      부가가치  \
0    -0.209128  1.009724 -0.033017  ... -0.520886 -0.538815 -0.517775   
1    -0.209128  0.263523 -0.043352  ... -0.208501 -0.344338 -0.375733   
2    -0.129845  1.168513  0.426361  ...  0.240553 -0.237689 -0.147989   
3    -0.244702  1.827809  0.529077  ... -0.267073 -0.319244 -0.095262   
4    -0.209128  0.456645  0.190766  ...  0.513890  0.182633 -0.317300   
...        ...       ...       ...  ...       ...       ...       ...   
6885  0.512479 -0.485897  0.231262  ... -0.764937 -0.639190 -0.368877   
6886 -0.209128  0.584320 -0.154294  ... -1.418994 -1.291630 -0.439175   
6887 -0.209128 -0.756267 -1.159737  ... -0.735651 -0.783480 -0.731153   
6888 -0.242948  2.629801  1.021147  ... -1.477566 -1.341818  1.563833   
6889 -0.091240 -0.886624  0.222404  ... -0.159690 -0.407072 -0.338566   

       총자본투자효율    설비투자효율    기계투자효율     부가가치율   노동소득분배율     자본분배율     이윤분배율  
0    -0.268715 -0.204982 -0.097181  0.001823  0.167352 -0.034998 -0.128958  
1     0.242975  0.051314 -0.096631  0.078411  0.467954 -0.302030 -0.108773  
2     1.266925 -0.120122 -0.096515  0.748560 -0.247238  0.333292  0.264922  
3     0.902651 -0.025372 -0.046651  0.361023 -0.421881  0.488431  0.414188  
4     0.906066  1.352783 -0.097251  0.338812 -0.344009  0.419256  0.149166  
...        ...       ...       ...       ...       ...       ...       ...  
6885 -0.328479 -0.172932 -0.097190  0.225461 -0.005114  0.118207  0.192547  
6886 -0.577778  0.155722 -0.096952  0.138150  0.360003 -0.206134 -0.205905  
6887 -2.166921 -0.360156 -0.098877 -1.278735 -0.721395 -0.124477  0.113258  
6888 -0.192445 -0.008700 -0.096966  1.309442 -0.530723  0.585118  0.440060  
6889 -0.377997 -0.117615 -0.095022 -0.272363 -0.263960  0.348147  0.341813  

[6890 rows x 48 columns]

In [43]:
x_test

매출액증가율   유형자산증가율   재고자산증가율  비유동자산증가율   유동자산증가율   자기자본증가율    총자본증가율  \
0     0.196884  0.236131 -0.168682  0.237938  1.846278  1.958032  2.083881   
1     0.499831 -0.058074 -0.409730  0.846183  5.395523 -0.162465  5.396605   
2     0.137008  0.627830  0.125743  0.810985  0.016970  0.256009  0.803391   
3    -1.129307  0.999227 -1.139651  2.593316  0.061363  1.066688  1.628998   
4    -1.536464 -0.559311 -1.055242 -0.056613 -1.669734 -2.096288 -1.742673   
...        ...       ...       ...       ...       ...       ...       ...   
2360 -1.692397 -1.196008 -0.428052 -0.926268 -1.152141 -1.348967 -1.593176   
2361  0.198922  0.532629  0.867102  6.532393  1.386967  4.836049  5.396605   
2362  5.662930  1.347455  2.510801  2.566969  1.351998  5.706995  2.753598   
2363 -0.170016 -0.100971 -0.437478 -0.024296 -0.156884 -0.099416 -0.088619   
2364 -0.856425 -0.378544 -0.424663 -0.470342  0.292507 -0.201717 -0.330797   

        순이익증가율   매출액총이익률   매출액순이익률  ...   유동자산회전률   당좌자산회전률      부가가치  \
0    -0.605466  1.412597  0.255940  ... -1.243277 -1.166161 -0.259920   
1    -0.209128 -0.228401 -0.518127  ... -1.526376 -1.366912 -0.584557   
2     0.137757  1.393822  0.446398  ...  0.016026 -0.350611  1.630055   
3    -0.209128 -1.613513 -8.039437  ... -1.623996 -1.435920 -0.798118   
4    -0.209128 -2.008340 -1.620802  ... -0.921130 -0.977957 -0.981254   
...        ...       ...       ...  ...       ...       ...       ...   
2360 -0.209128 -1.144120 -1.751782  ... -1.575186 -1.398279 -0.648692   
2361 -0.209128 -0.484287  3.443321  ... -1.165181 -1.072059  0.393084   
2362 -0.209128  2.386789  1.112264  ... -0.696603 -0.614097 -0.151711   
2363 -0.255949  2.547724  0.599102  ... -1.428756 -1.297904  1.349171   
2364 -0.545884 -0.973529  0.195406  ...  0.328412 -0.030665 -0.359343   

       총자본투자효율    설비투자효율    기계투자효율     부가가치율   노동소득분배율     자본분배율     이윤분배율  
0    -0.429223 -0.122049 -0.097010  0.331408 -0.003036  0.116361  0.202639  
1    -0.999538 -0.246142 -0.097333 -0.530211 -0.721395 -0.124477  0.113258  
2     2.796304 -0.022402 -0.094158  1.793480 -0.182329  0.275631  0.201691  
3    -1.666045 -0.512212 -0.098989 -6.214345 -0.721395 -0.124477  0.113258  
4    -3.456107 -0.533424 -0.097983 -1.967519 -0.721395 -0.124477  0.113258  
...        ...       ...       ...       ...       ...       ...       ...  
2360 -1.372349 -1.684017 -0.102238 -1.329538 -0.721395 -0.124477  0.113258  
2361  1.457599  0.208847 -0.091435  4.195036 -0.610969  0.656403  0.504294  
2362  1.140567 -0.125778 -0.096931  0.930074 -0.576239  0.625551  0.569922  
2363 -0.301727 -0.058107 -0.096969  0.907353 -0.415350  0.482630  0.330828  
2364 -0.421255 -0.140271 -0.095169 -0.325975 -0.166101  0.261216  0.306350  

[2365 rows x 48 columns]

In [44]:
y_test 

0       0.0
1       0.0
2       0.0
3       0.0
4       0.0
       ... 
2360    0.0
2361    0.0
2362    0.0
2363    0.0
2364    0.0
Name: label, Length: 2365, dtype: float64

In [45]:
mda_feature=feature["mda_feature"].tolist()
logit_feature=feature["logit_feature"].tolist()
lasso_feature=feature["lasso_feature"].tolist()
ela_feature=feature["ela_feature"].tolist()
same_feature=feature["same_feature"].tolist()

In [46]:
# 성능확인 코드
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score
from sklearn.metrics import f1_score, roc_auc_score, average_precision_score


import warnings

def get_clf_eval(MDA_y_test, pred):
    confusion = confusion_matrix(MDA_y_test, pred)
    accuracy = accuracy_score(MDA_y_test, pred)
    precision = precision_score(MDA_y_test, pred)
    recall = recall_score(MDA_y_test, pred)
    roc_score = roc_auc_score(MDA_y_test, pred)
    pr_score = average_precision_score(MDA_y_test, pred)
    f1 = f1_score(MDA_y_test, pred)
    print('오차행렬')
    print(confusion)
    print('정확도: {0:.4f}, 정밀도 : {1:.4f}, 재현율:{2:.4f},F1 스코어:{3:.4f}'.format(accuracy, precision, recall, f1, roc_score))
    print('ROC 스코어: {0:.4f}, PR score : {1:.4f}'.format(roc_score, pr_score))

In [47]:
# 임계값에 따른 오차행렬및 스코어 -------->#임계값 최적 : 재현율기준(0.1)/f1기준(0.3)
from sklearn.preprocessing import Binarizer
thresholds = [0.1,0.2,0.3,0.4,0.5]

def get_eval_by_threshold(MDA_y_test, pred_proba_c1, thresholds):
    for custom_threshold in thresholds:
        binarizer = Binarizer(threshold=custom_threshold).fit(pred_proba_c1)
        custom_predict = binarizer.transform(pred_proba_c1)
        print("임곗값:", custom_threshold)
        get_clf_eval(MDA_y_test, custom_predict)
        print("---------------------------------------------------------")


In [48]:
# Roc Auc 그래프 값 확인 코드
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score
def roc_curve_plot(MDA_y_test, pred_proba_c1):
    fprs, tprs, thresholds = roc_curve(MDA_y_test, pred_proba_c1)
    
    plt.plot(fprs, tprs, label='ROC')
    plt.plot([0,1],[0,1], 'k--', label = 'Random')
    
    start, end= plt.xlim()
    plt.xticks(np.round(np.arange(start, end, 0.1),2))
    plt.xlim(0,1); plt.ylim(0,1)
    plt.xlabel('FPR(1-Sensitivity)'); plt.ylabel('TPR(Recall)')
    plt.legend()
    plt.show()

In [49]:
mda_x_train = x_train[mda_feature].reset_index(drop='index')
mda_x_test = x_test[mda_feature].reset_index(drop='index')
mda_y_train = y_train
mda_y_test = y_test 

In [50]:
logit_x_train = x_train[logit_feature].reset_index(drop='index')
logit_x_test = x_test[logit_feature].reset_index(drop='index')
logit_y_train = y_train
logit_y_test = y_test 

In [51]:
lasso_x_train = x_train[lasso_feature].reset_index(drop='index')
lasso_x_test = x_test[lasso_feature].reset_index(drop='index')
lasso_y_train = y_train
lasso_y_test = y_test 

In [52]:
ela_x_train = x_train[ela_feature].reset_index(drop='index')
ela_x_test = x_test[ela_feature].reset_index(drop='index')
ela_y_train = y_train
ela_y_test = y_test 

In [53]:
same_x_train = x_train[same_feature].reset_index(drop='index')
same_x_test = x_test[same_feature].reset_index(drop='index')
same_y_train = y_train
same_y_test = y_test 

In [54]:
fea_x_train = [mda_x_train, logit_x_train, lasso_x_train, ela_x_train, same_x_train]
fea_y_train = [mda_y_train, logit_y_train, lasso_y_train, ela_y_train, same_y_train]
fea_x_test = [mda_x_test, logit_x_test, lasso_x_test, ela_x_test, same_x_test]
fea_y_test = [mda_y_test, logit_y_test, lasso_y_test, ela_y_test, same_y_test]
fea = ["mda","logit","lasso","ela","same"]

In [55]:
# 1-1 LDA 
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
lda_clf = LinearDiscriminantAnalysis()
for x_train,y_train,x_test,y_test,feature in zip(fea_x_train,fea_y_train,fea_x_test, fea_y_test, fea):
    lda_clf.fit(x_train, y_train)
    lda_pred = lda_clf.predict(x_test)
    lda_pred_proba = lda_clf.predict_proba(x_test)
    print(feature,"lda") 
    get_clf_eval(y_test, lda_pred)
    get_eval_by_threshold(y_test , lda_pred_proba[:,1].reshape(-1,1), thresholds)



mda lda
오차행렬
[[2248   67]
 [  31   19]]
정확도: 0.9586, 정밀도 : 0.2209, 재현율:0.3800,F1 스코어:0.2794
ROC 스코어: 0.6755, PR score : 0.0971
임곗값: 0.1
오차행렬
[[2169  146]
 [  26   24]]
정확도: 0.9273, 정밀도 : 0.1412, 재현율:0.4800,F1 스코어:0.2182
ROC 스코어: 0.7085, PR score : 0.0788
---------------------------------------------------------
임곗값: 0.2
오차행렬
[[2204  111]
 [  26   24]]
정확도: 0.9421, 정밀도 : 0.1778, 재현율:0.4800,F1 스코어:0.2595
ROC 스코어: 0.7160, PR score : 0.0963
---------------------------------------------------------
임곗값: 0.3
오차행렬
[[2225   90]
 [  28   22]]
정확도: 0.9501, 정밀도 : 0.1964, 재현율:0.4400,F1 스코어:0.2716
ROC 스코어: 0.7006, PR score : 0.0983
---------------------------------------------------------
임곗값: 0.4
오차행렬
[[2239   76]
 [  29   21]]
정확도: 0.9556, 정밀도 : 0.2165, 재현율:0.4200,F1 스코어:0.2857
ROC 스코어: 0.6936, PR score : 0.1032
---------------------------------------------------------
임곗값: 0.5
오차행렬
[[2248   67]
 [  31   19]]
정확도: 0.9586, 정밀도 : 0.2209, 재현율:0.3800,F1 스코어:0.2794
ROC 스코어: 0.6755, PR score : 0.0971
-

In [56]:
# 1-2 디시전트리 
from sklearn.tree import DecisionTreeClassifier 
dt_clf = DecisionTreeClassifier(random_state=52)
for x_train,y_train,x_test,y_test,feature in zip(fea_x_train,fea_y_train,fea_x_test, fea_y_test, fea):
    dt_clf.fit(x_train, y_train)
    dt_pred = dt_clf.predict(x_test)
    dt_pred_proba = dt_clf.predict_proba(x_test)   
    print(feature,"디시전트리") 
    get_clf_eval(y_test, dt_pred)
    get_eval_by_threshold(y_test , dt_pred_proba[:,1].reshape(-1,1), thresholds)
    


mda 디시전트리
오차행렬
[[2266   49]
 [  40   10]]
정확도: 0.9624, 정밀도 : 0.1695, 재현율:0.2000,F1 스코어:0.1835
ROC 스코어: 0.5894, PR score : 0.0508
임곗값: 0.1
오차행렬
[[2266   49]
 [  40   10]]
정확도: 0.9624, 정밀도 : 0.1695, 재현율:0.2000,F1 스코어:0.1835
ROC 스코어: 0.5894, PR score : 0.0508
---------------------------------------------------------
임곗값: 0.2
오차행렬
[[2266   49]
 [  40   10]]
정확도: 0.9624, 정밀도 : 0.1695, 재현율:0.2000,F1 스코어:0.1835
ROC 스코어: 0.5894, PR score : 0.0508
---------------------------------------------------------
임곗값: 0.3
오차행렬
[[2266   49]
 [  40   10]]
정확도: 0.9624, 정밀도 : 0.1695, 재현율:0.2000,F1 스코어:0.1835
ROC 스코어: 0.5894, PR score : 0.0508
---------------------------------------------------------
임곗값: 0.4
오차행렬
[[2266   49]
 [  40   10]]
정확도: 0.9624, 정밀도 : 0.1695, 재현율:0.2000,F1 스코어:0.1835
ROC 스코어: 0.5894, PR score : 0.0508
---------------------------------------------------------
임곗값: 0.5
오차행렬
[[2266   49]
 [  40   10]]
정확도: 0.9624, 정밀도 : 0.1695, 재현율:0.2000,F1 스코어:0.1835
ROC 스코어: 0.5894, PR score : 0.0508

In [57]:
from sklearn.tree import DecisionTreeClassifier 
dt_clf = DecisionTreeClassifier(random_state=52)
from sklearn.model_selection import GridSearchCV
tree = DecisionTreeClassifier(random_state=52)
for x_train,y_train,x_test,y_test,feature in zip(fea_x_train,fea_y_train,fea_x_test, fea_y_test, fea):
    # key: 하이퍼파라미터 명; value: [후보값들] 을 리스트로 전달
    param_grid = {
      'criterion': ['entropy', 'gini'],
               'max_depth': [2,4,6,8],
               'max_features': ['auto', 'sqrt'],
               'min_samples_leaf': [4,6,8,10],
               'min_samples_split': [4,6,8,10]}
    grid_search = GridSearchCV(tree
                            , param_grid = param_grid
                            , cv = 5 #교차검증시 fold 개수; n번의 교차검증; 데이터들이 돌아가면서 하나씩 검증(validation)에 사용되어 일반화하는 것; 데이터가 많지 않을 때 보통 쓰인다고 함
                            , n_jobs = -1)  #-1: 모든 코어 사용

    grid_search.fit(x_train, y_train)

    # 최선의 결과 출력
    print('피처:{2} 최적 하이퍼 파라미터 :{0}, 최적 평균 정확도 :{1:.3f}'.format(grid_search.best_params_, grid_search.best_score_, feature))
    a = grid_search.best_params_
    keys=list(a.keys())
    values = list(a.values())

    dt_clf_best = DecisionTreeClassifier(random_state=52,criterion = values[0], max_depth = values[1],max_features=values[2], min_samples_leaf=values[3], min_samples_split=values[4])
    dt_clf_best.fit(x_train, y_train)
    dt_best_pred = dt_clf_best.predict(x_test)
    dt_best_pred_proba = dt_clf_best.predict_proba(x_test)   

    print(feature,"디시전트리 파라미터적용") 
    get_clf_eval(y_test, dt_best_pred)
    get_eval_by_threshold(y_test ,dt_best_pred_proba[:,1].reshape(-1,1), thresholds)


피처:mda 최적 하이퍼 파라미터 :{'criterion': 'entropy', 'max_depth': 4, 'max_features': 'auto', 'min_samples_leaf': 10, 'min_samples_split': 4}, 최적 평균 정확도 :0.983
mda 디시전트리 파라미터적용
오차행렬
[[2306    9]
 [  40   10]]
정확도: 0.9793, 정밀도 : 0.5263, 재현율:0.2000,F1 스코어:0.2899
ROC 스코어: 0.5981, PR score : 0.1222
임곗값: 0.1
오차행렬
[[2202  113]
 [  29   21]]
정확도: 0.9400, 정밀도 : 0.1567, 재현율:0.4200,F1 스코어:0.2283
ROC 스코어: 0.6856, PR score : 0.0781
---------------------------------------------------------
임곗값: 0.2
오차행렬
[[2294   21]
 [  38   12]]
정확도: 0.9751, 정밀도 : 0.3636, 재현율:0.2400,F1 스코어:0.2892
ROC 스코어: 0.6155, PR score : 0.1033
---------------------------------------------------------
임곗값: 0.3
오차행렬
[[2306    9]
 [  40   10]]
정확도: 0.9793, 정밀도 : 0.5263, 재현율:0.2000,F1 스코어:0.2899
ROC 스코어: 0.5981, PR score : 0.1222
---------------------------------------------------------
임곗값: 0.4
오차행렬
[[2306    9]
 [  40   10]]
정확도: 0.9793, 정밀도 : 0.5263, 재현율:0.2000,F1 스코어:0.2899
ROC 스코어: 0.5981, PR score : 0.1222
---------------------------

In [58]:
# 1-3 랜덤포레스트 구현 
from sklearn.ensemble import RandomForestClassifier
rf_clf = RandomForestClassifier(random_state=52)    
for x_train,y_train,x_test,y_test,feature in zip(fea_x_train,fea_y_train,fea_x_test, fea_y_test, fea):
    rf_clf.fit(x_train, y_train)
    rf_pred = rf_clf.predict(x_test)
    rf_pred_proba = rf_clf.predict_proba(x_test)
    print(feature,"랜덤포레스트") 
    get_clf_eval(y_test, rf_pred)
    get_eval_by_threshold(y_test , rf_pred_proba[:,1].reshape(-1,1), thresholds)
    


mda 랜덤포레스트
오차행렬
[[2307    8]
 [  41    9]]
정확도: 0.9793, 정밀도 : 0.5294, 재현율:0.1800,F1 스코어:0.2687
ROC 스코어: 0.5883, PR score : 0.1126
임곗값: 0.1
오차행렬
[[2205  110]
 [  25   25]]
정확도: 0.9429, 정밀도 : 0.1852, 재현율:0.5000,F1 스코어:0.2703
ROC 스코어: 0.7262, PR score : 0.1032
---------------------------------------------------------
임곗값: 0.2
오차행렬
[[2274   41]
 [  32   18]]
정확도: 0.9691, 정밀도 : 0.3051, 재현율:0.3600,F1 스코어:0.3303
ROC 스코어: 0.6711, PR score : 0.1234
---------------------------------------------------------
임곗값: 0.3
오차행렬
[[2292   23]
 [  37   13]]
정확도: 0.9746, 정밀도 : 0.3611, 재현율:0.2600,F1 스코어:0.3023
ROC 스코어: 0.6250, PR score : 0.1095
---------------------------------------------------------
임곗값: 0.4
오차행렬
[[2300   15]
 [  40   10]]
정확도: 0.9767, 정밀도 : 0.4000, 재현율:0.2000,F1 스코어:0.2667
ROC 스코어: 0.5968, PR score : 0.0969
---------------------------------------------------------
임곗값: 0.5
오차행렬
[[2307    8]
 [  41    9]]
정확도: 0.9793, 정밀도 : 0.5294, 재현율:0.1800,F1 스코어:0.2687
ROC 스코어: 0.5883, PR score : 0.112

In [59]:
# 하이퍼파라미터 Grid-Search
from sklearn.model_selection import GridSearchCV

    # 탐색 범위 정의
for x_train,y_train,x_test,y_test,feature in zip(fea_x_train,fea_y_train,fea_x_test, fea_y_test, fea):
    grid_search = {'criterion': ['entropy', 'gini'],
                'max_depth': [2,4,6,8],
                'max_features': ['auto', 'sqrt'],
                'min_samples_leaf': [4,6,8,10],
                'min_samples_split': [4,6,8,10],
                'n_estimators': [20,40,60,80,100]}

    model = RandomForestClassifier(random_state=52)
    grid_search = GridSearchCV(estimator = model, param_grid = grid_search, 
                                cv = 5,verbose=0, n_jobs = -1)
    grid_search.fit(x_train,y_train)

    # 최선의 결과 출력
    print('최적 하이퍼 파라미터 :{0}, 최적 평균 정확도 :{1:.3f}'.format(grid_search.best_params_, grid_search.best_score_))
    a = grid_search.best_params_
    keys=list(a.keys())
    values = list(a.values())

    rf_clf_best = RandomForestClassifier(random_state=52,criterion = values[0], max_depth = values[1],max_features=values[2], min_samples_leaf=values[3],  min_samples_split=values[4],n_estimators=values[5])
    rf_clf_best.fit(x_train, y_train)
    rf_best_pred = rf_clf_best.predict(x_test)
    rf_best_pred_proba = rf_clf_best.predict_proba(x_test)   

    print(feature,"디시전트리 파라미터적용") 
    get_clf_eval(y_test, rf_best_pred)
    get_eval_by_threshold(y_test ,rf_best_pred_proba[:,1].reshape(-1,1), thresholds)

최적 하이퍼 파라미터 :{'criterion': 'entropy', 'max_depth': 6, 'max_features': 'auto', 'min_samples_leaf': 8, 'min_samples_split': 4, 'n_estimators': 100}, 최적 평균 정확도 :0.984
mda 디시전트리 파라미터적용
오차행렬
[[2309    6]
 [  42    8]]
정확도: 0.9797, 정밀도 : 0.5714, 재현율:0.1600,F1 스코어:0.2500
ROC 스코어: 0.5787, PR score : 0.1092
임곗값: 0.1
오차행렬
[[2237   78]
 [  27   23]]
정확도: 0.9556, 정밀도 : 0.2277, 재현율:0.4600,F1 스코어:0.3046
ROC 스코어: 0.7132, PR score : 0.1162
---------------------------------------------------------
임곗값: 0.2
오차행렬
[[2281   34]
 [  36   14]]
정확도: 0.9704, 정밀도 : 0.2917, 재현율:0.2800,F1 스코어:0.2857
ROC 스코어: 0.6327, PR score : 0.0969
---------------------------------------------------------
임곗값: 0.3
오차행렬
[[2301   14]
 [  38   12]]
정확도: 0.9780, 정밀도 : 0.4615, 재현율:0.2400,F1 스코어:0.3158
ROC 스코어: 0.6170, PR score : 0.1268
---------------------------------------------------------
임곗값: 0.4
오차행렬
[[2307    8]
 [  41    9]]
정확도: 0.9793, 정밀도 : 0.5294, 재현율:0.1800,F1 스코어:0.2687
ROC 스코어: 0.5883, PR score : 0.1126
--------------

In [60]:
# 1-4 로지스틱회귀
from sklearn.linear_model import LogisticRegression
lr_clf = LogisticRegression()
for x_train,y_train,x_test,y_test,feature in zip(fea_x_train,fea_y_train,fea_x_test, fea_y_test, fea):
    lr_clf.fit(x_train, y_train)
    lr_pred = lr_clf.predict(x_test)
    lr_pred_proba = lr_clf.predict_proba(x_test)
    print(feature,"로지스틱회귀") 
    get_clf_eval(y_test, lr_pred)
    get_eval_by_threshold(y_test , lr_pred_proba[:,1].reshape(-1,1), thresholds)
    

mda 로지스틱회귀
오차행렬
[[2309    6]
 [  45    5]]
정확도: 0.9784, 정밀도 : 0.4545, 재현율:0.1000,F1 스코어:0.1639
ROC 스코어: 0.5487, PR score : 0.0645
임곗값: 0.1
오차행렬
[[2246   69]
 [  26   24]]
정확도: 0.9598, 정밀도 : 0.2581, 재현율:0.4800,F1 스코어:0.3357
ROC 스코어: 0.7251, PR score : 0.1349
---------------------------------------------------------
임곗값: 0.2
오차행렬
[[2285   30]
 [  33   17]]
정확도: 0.9734, 정밀도 : 0.3617, 재현율:0.3400,F1 스코어:0.3505
ROC 스코어: 0.6635, PR score : 0.1369
---------------------------------------------------------
임곗값: 0.3
오차행렬
[[2301   14]
 [  39   11]]
정확도: 0.9776, 정밀도 : 0.4400, 재현율:0.2200,F1 스코어:0.2933
ROC 스코어: 0.6070, PR score : 0.1133
---------------------------------------------------------
임곗값: 0.4
오차행렬
[[2305   10]
 [  43    7]]
정확도: 0.9776, 정밀도 : 0.4118, 재현율:0.1400,F1 스코어:0.2090
ROC 스코어: 0.5678, PR score : 0.0758
---------------------------------------------------------
임곗값: 0.5
오차행렬
[[2309    6]
 [  45    5]]
정확도: 0.9784, 정밀도 : 0.4545, 재현율:0.1000,F1 스코어:0.1639
ROC 스코어: 0.5487, PR score : 0.064

In [61]:
#로지스틱 회귀 최적 하이퍼 파라미터
from sklearn.model_selection import GridSearchCV

for x_train,y_train,x_test,y_test,feature in zip(fea_x_train,fea_y_train,fea_x_test, fea_y_test, fea):
    params = {'penalty': ['l2','l1','elasticnet','None'],
            'C':[0.01,0.1,1,3,5,10]}

    grid_search = GridSearchCV(lr_clf, param_grid=params, scoring='accuracy', cv=5)
    grid_search.fit(x_train,y_train)
    print('최적 하이퍼 파라미어:{0}, 최적 평균 정확도:{1:.3f}'.format(grid_search.best_params_, grid_search.best_score_))

    a = grid_search.best_params_
    keys=list(a.keys())
    values = list(a.values())

    lr_clf_best = LogisticRegression(penalty= values[1], C=values[0])
    lr_clf_best.fit(x_train, y_train)
    lr_best_pred = lr_clf_best.predict(x_test)
    lr_best_pred_proba = lr_clf_best.predict_proba(x_test)   

    print(feature,"로지스틱회귀 파라미터적용") 
    get_clf_eval(y_test, lr_best_pred)
    get_eval_by_threshold(y_test ,lr_best_pred_proba[:,1].reshape(-1,1), thresholds)


최적 하이퍼 파라미어:{'C': 1, 'penalty': 'l2'}, 최적 평균 정확도:0.983
mda 로지스틱회귀 파라미터적용
오차행렬
[[2309    6]
 [  45    5]]
정확도: 0.9784, 정밀도 : 0.4545, 재현율:0.1000,F1 스코어:0.1639
ROC 스코어: 0.5487, PR score : 0.0645
임곗값: 0.1
오차행렬
[[2246   69]
 [  26   24]]
정확도: 0.9598, 정밀도 : 0.2581, 재현율:0.4800,F1 스코어:0.3357
ROC 스코어: 0.7251, PR score : 0.1349
---------------------------------------------------------
임곗값: 0.2
오차행렬
[[2285   30]
 [  33   17]]
정확도: 0.9734, 정밀도 : 0.3617, 재현율:0.3400,F1 스코어:0.3505
ROC 스코어: 0.6635, PR score : 0.1369
---------------------------------------------------------
임곗값: 0.3
오차행렬
[[2301   14]
 [  39   11]]
정확도: 0.9776, 정밀도 : 0.4400, 재현율:0.2200,F1 스코어:0.2933
ROC 스코어: 0.6070, PR score : 0.1133
---------------------------------------------------------
임곗값: 0.4
오차행렬
[[2305   10]
 [  43    7]]
정확도: 0.9776, 정밀도 : 0.4118, 재현율:0.1400,F1 스코어:0.2090
ROC 스코어: 0.5678, PR score : 0.0758
---------------------------------------------------------
임곗값: 0.5
오차행렬
[[2309    6]
 [  45    5]]
정확도: 0.9784, 정밀도 : 0.45

In [62]:
# 1-5 KNN 
from sklearn.neighbors import KNeighborsClassifier
knn_clf = KNeighborsClassifier(n_neighbors=5)
for x_train,y_train,x_test,y_test,feature in zip(fea_x_train,fea_y_train,fea_x_test, fea_y_test, fea):

    knn_clf.fit(x_train, y_train)
    knn_pred = knn_clf.predict(x_test)
    knn_pred_proba = knn_clf.predict_proba(x_test)
    print(feature,"KNN") 
    get_clf_eval(y_test, knn_pred)
    get_eval_by_threshold(y_test , knn_pred_proba[:,1].reshape(-1,1), thresholds)



mda KNN
오차행렬
[[2311    4]
 [  45    5]]
정확도: 0.9793, 정밀도 : 0.5556, 재현율:0.1000,F1 스코어:0.1695
ROC 스코어: 0.5491, PR score : 0.0746
임곗값: 0.1
오차행렬
[[2185  130]
 [  29   21]]
정확도: 0.9328, 정밀도 : 0.1391, 재현율:0.4200,F1 스코어:0.2090
ROC 스코어: 0.6819, PR score : 0.0707
---------------------------------------------------------
임곗값: 0.2
오차행렬
[[2298   17]
 [  40   10]]
정확도: 0.9759, 정밀도 : 0.3704, 재현율:0.2000,F1 스코어:0.2597
ROC 스코어: 0.5963, PR score : 0.0910
---------------------------------------------------------
임곗값: 0.3
오차행렬
[[2298   17]
 [  40   10]]
정확도: 0.9759, 정밀도 : 0.3704, 재현율:0.2000,F1 스코어:0.2597
ROC 스코어: 0.5963, PR score : 0.0910
---------------------------------------------------------
임곗값: 0.4
오차행렬
[[2311    4]
 [  45    5]]
정확도: 0.9793, 정밀도 : 0.5556, 재현율:0.1000,F1 스코어:0.1695
ROC 스코어: 0.5491, PR score : 0.0746
---------------------------------------------------------
임곗값: 0.5
오차행렬
[[2311    4]
 [  45    5]]
정확도: 0.9793, 정밀도 : 0.5556, 재현율:0.1000,F1 스코어:0.1695
ROC 스코어: 0.5491, PR score : 0.0746
-

In [63]:
# knn 파라미터 구하기
from sklearn.metrics import accuracy_score
acc = []
for x_train,y_train,x_test,y_test,feature in zip(fea_x_train,fea_y_train,fea_x_test, fea_y_test, fea):
    for k in range(1,20):
        knn_clf = KNeighborsClassifier(n_neighbors=k)
        knn_clf.fit(x_train, y_train)
        knn_pred = knn_clf.predict(x_test)
        knn_score=accuracy_score(y_test,knn_pred)

        acc.append(knn_score)
    int = acc.index(max(acc))+1
    print("최적거리")
    print(int)

    knn_clf_best =KNeighborsClassifier(n_neighbors=int)
    knn_clf_best.fit(x_train, y_train)
    knn_best_pred = knn_clf_best.predict(x_test)
    knn_best_pred_proba = knn_clf_best.predict_proba(x_test)   

    print(feature,"KNN 파라미터적용") 
    get_clf_eval(y_test, knn_best_pred)
    get_eval_by_threshold(y_test ,knn_best_pred_proba[:,1].reshape(-1,1), thresholds)      


최적거리
4
mda KNN 파라미터적용
오차행렬
[[2312    3]
 [  45    5]]
정확도: 0.9797, 정밀도 : 0.6250, 재현율:0.1000,F1 스코어:0.1724
ROC 스코어: 0.5494, PR score : 0.0815
임곗값: 0.1
오차행렬
[[2208  107]
 [  30   20]]
정확도: 0.9421, 정밀도 : 0.1575, 재현율:0.4000,F1 스코어:0.2260
ROC 스코어: 0.6769, PR score : 0.0757
---------------------------------------------------------
임곗값: 0.2
오차행렬
[[2208  107]
 [  30   20]]
정확도: 0.9421, 정밀도 : 0.1575, 재현율:0.4000,F1 스코어:0.2260
ROC 스코어: 0.6769, PR score : 0.0757
---------------------------------------------------------
임곗값: 0.3
오차행렬
[[2304   11]
 [  43    7]]
정확도: 0.9772, 정밀도 : 0.3889, 재현율:0.1400,F1 스코어:0.2059
ROC 스코어: 0.5676, PR score : 0.0726
---------------------------------------------------------
임곗값: 0.4
오차행렬
[[2304   11]
 [  43    7]]
정확도: 0.9772, 정밀도 : 0.3889, 재현율:0.1400,F1 스코어:0.2059
ROC 스코어: 0.5676, PR score : 0.0726
---------------------------------------------------------
임곗값: 0.5
오차행렬
[[2312    3]
 [  45    5]]
정확도: 0.9797, 정밀도 : 0.6250, 재현율:0.1000,F1 스코어:0.1724
ROC 스코어: 0.5494, PR sc

In [64]:
# 1-5 xgboost
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
import xgboost as xgb ## XGBoost 불러오기
from xgboost import plot_importance 

xgb_wrapper = XGBClassifier()
for x_train,y_train,x_test,y_test,feature in zip(fea_x_train,fea_y_train,fea_x_test, fea_y_test, fea):

    xgb_wrapper.fit(x_train, y_train, verbose = True)
    xgb_wrapper.fit(x_train, y_train)
    xgb_pred = xgb_wrapper.predict(x_test)
    xgb_pred_proba = xgb_wrapper.predict_proba(x_test)
    print(feature,"XGB") 
    get_clf_eval(y_test, xgb_pred)
    get_eval_by_threshold(y_test , xgb_pred_proba[:,1].reshape(-1,1), thresholds)

In [ ]:
values[1]

'l2'

In [ ]:
#xgb 최적 하이퍼 파라미터
from sklearn.model_selection import GridSearchCV

xgb_wrapper
for x_train,y_train,x_test,y_test,feature in zip(fea_x_train,fea_y_train,fea_x_test, fea_y_test, fea):
    params = {
            'n_estimators':[40,43,46,50],
            'learning_rate':[0.03,0.05,0.04],
            'max_depth' : [0.8,1,2,3,4]
            }

    grid_clf = GridSearchCV(xgb_wrapper, param_grid=params, scoring='accuracy', cv=5)
    grid_clf.fit(x_train,y_train)
    print('최적 하이퍼 파라미어:{0}, 최적 평균 정확도:{1:.3f}'.format(grid_clf.best_params_, grid_clf.best_score_))

    a = grid_clf.best_params_
    keys=list(a.keys())
    values = list(a.values())
    xgb_clf_best = XGBClassifier( learning_rate=values[0],max_depth=values[1],n_estimators= values[2])
    xgb_clf_best.fit(x_train, y_train)
    xgb_best_pred = xgb_clf_best.predict(x_test)
    xgb_best_pred_proba = xgb_clf_best.predict_proba(x_test)   

    print(feature,"XGB 파라미터적용") 
    get_clf_eval(y_test, xgb_best_pred)
    get_eval_by_threshold(y_test ,xgb_best_pred_proba[:,1].reshape(-1,1), thresholds)

최적 하이퍼 파라미어:{'learning_rate': 0.03, 'max_depth': 2, 'n_estimators': 40}, 최적 평균 정확도:0.985
mda XGB 파라미터적용
오차행렬
[[2305   10]
 [  42    8]]
정확도: 0.9780, 정밀도 : 0.4444, 재현율:0.1600,F1 스코어:0.2353
ROC 스코어: 0.5778, PR score : 0.0889
임곗값: 0.1
오차행렬
[[   0 2315]
 [   0   50]]
정확도: 0.0211, 정밀도 : 0.0211, 재현율:1.0000,F1 스코어:0.0414
ROC 스코어: 0.5000, PR score : 0.0211
---------------------------------------------------------
임곗값: 0.2
오차행렬
[[2250   65]
 [  32   18]]
정확도: 0.9590, 정밀도 : 0.2169, 재현율:0.3600,F1 스코어:0.2707
ROC 스코어: 0.6660, PR score : 0.0916
---------------------------------------------------------
임곗값: 0.3
오차행렬
[[2294   21]
 [  38   12]]
정확도: 0.9751, 정밀도 : 0.3636, 재현율:0.2400,F1 스코어:0.2892
ROC 스코어: 0.6155, PR score : 0.1033
---------------------------------------------------------
임곗값: 0.4
오차행렬
[[2304   11]
 [  39   11]]
정확도: 0.9789, 정밀도 : 0.5000, 재현율:0.2200,F1 스코어:0.3056
ROC 스코어: 0.6076, PR score : 0.1265
---------------------------------------------------------
임곗값: 0.5
오차행렬
[[2305   10]
 [  42