# 3. CNN(Condensed Nearest Neighbour)

### CNN 방법은 최근접인 클래스 분포 데이터를 삭제하면서 샘플링하는 방법론

In [33]:
# 필요 라이브러리 import 
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
import warnings
warnings.filterwarnings(action='ignore') 

In [34]:
from imblearn.under_sampling import RandomUnderSampler, TomekLinks,CondensedNearestNeighbour
from imblearn.over_sampling import RandomOverSampler
from imblearn.over_sampling import SMOTE

from sklearn.datasets import make_classification
from collections import Counter

from matplotlib import pyplot as plt
import seaborn as sns

In [35]:
df = pd.read_csv("./데이터자료/9. 데이터셋.csv")
feature = pd.read_csv("./데이터자료/8. feature.csv")

In [36]:
year = df["회계년"].unique().tolist()
year

[2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020]

In [37]:
col = df.columns[7:55]
x_train = []
y_train = []
x_test = []
y_test = []

In [38]:
# train = df[df["회계년"] == 2017]
# x_train_year = train[col]
# y_train_year = train["label"]
# x_train_year, y_train_year = RandomUnderSampler(random_state=4,sampling_strategy=0.1).fit_resample(x_train_year,y_train_year)
# x_train.append(x_train_year)
# y_train.append(y_train_year)

In [39]:
col = df.columns[7:55]
x_train = []
y_train = []
x_test = []
y_test = []
for i in year:
    if i <= 2018:
        print(i)
        train = df[df["회계년"] == i].reset_index()
        x_train_year = train[col]
        y_train_year = train["label"]
        x_train_year, y_train_year = CondensedNearestNeighbour(random_state=4).fit_resample(x_train_year,y_train_year)
        x_train.append(x_train_year)
        y_train.append(y_train_year)
 
    else:
        test = df[df["회계년"] == i].reset_index()
        x_test_year = test[col]
        y_test_year = test["label"]
        x_test_year, y_test_year = CondensedNearestNeighbour(random_state=4).fit_resample(x_test_year,y_test_year)
        x_test.append(x_test_year)
        y_test.append(y_test_year)

2011
2012
2013
2014
2015
2016
2017
2018


In [40]:
x_train = pd.concat(x_train).reset_index(drop=True)
y_train = pd.concat(y_train).reset_index(drop=True)
x_test = pd.concat(x_test).reset_index(drop=True)
y_test = pd.concat(y_test).reset_index(drop=True)

In [41]:
x_train

매출액증가율   유형자산증가율   재고자산증가율  비유동자산증가율   유동자산증가율   자기자본증가율    총자본증가율  \
0    0.410466  0.120512  0.103340  0.200362  0.534773  0.405387  0.468313   
1    0.469198  0.119379  0.123434  0.200663  0.356138  0.332292  0.380327   
2    0.389649  0.141493  0.057639  0.281572  0.374671  0.443531  0.461120   
3    0.281066  0.095738  0.116882  0.194961  0.403358  0.351822  0.386703   
4    0.341037  0.127056  0.088645  0.217535  0.208606  0.349513  0.288103   
..        ...       ...       ...       ...       ...       ...       ...   
552  0.364180  0.137279  0.174221  0.243586  0.498440  0.605992  0.466174   
553  0.584096  0.090276  0.227087  0.159663  0.154138  0.284705  0.213686   
554  0.281096  0.127196  0.131690  0.224813  0.263992  0.343025  0.338958   
555  0.179915  0.086686  0.005838  0.268987  0.141110  0.025543  0.283048   
556  0.232938  0.119494  0.092679  0.207616  1.000000  0.288441  0.454666   

       순이익증가율   매출액총이익률   매출액순이익률  ...   유동자산회전률   당좌자산회전률      부가가치  \
0    1.000000  0.341569  0.735553  ...  0.442831  0.365023  0.036781   
1    0.100370  0.497495  0.697256  ...  0.226860  0.181925  0.024368   
2    0.110359  0.523065  0.737262  ...  0.368421  0.238263  0.040880   
3    0.100370  0.408431  0.716744  ...  0.419238  0.316901  0.033320   
4    0.119584  0.651434  0.728004  ...  0.424682  0.296948  0.086526   
..        ...       ...       ...  ...       ...       ...       ...   
552  0.287875  0.537405  0.722053  ...  0.337568  0.242958  0.164112   
553  0.100370  0.323082  0.675434  ...  0.132486  0.099765  0.022135   
554  0.100370  0.136144  0.771518  ...  0.076225  0.049296  0.025980   
555  0.100370  0.122581  0.259414  ...  0.083485  0.061033  0.018445   
556  0.100370  0.436679  0.739613  ...  0.161525  0.105634  0.027334   

      총자본투자효율    설비투자효율    기계투자효율     부가가치율   노동소득분배율     자본분배율     이윤분배율  
0    0.321303  0.561973  0.006585  0.678743  0.059492  0.960947  0.941649  
1    0.222691  0.551351  0.006567  0.646645  0.110359  0.920868  0.896202  
2    0.322562  0.557403  0.006624  0.709571  0.058878  0.961431  0.936712  
3    0.299093  0.662454  0.006561  0.675042  0.046861  0.970899  0.924807  
4    0.281806  0.554830  0.006573  0.683282  0.053103  0.965981  0.934028  
..        ...       ...       ...       ...       ...       ...       ...  
552  0.262299  0.556104  0.006571  0.685498  0.038531  0.977463  0.928735  
553  0.176458  0.548723  0.006562  0.605619  1.000000  0.000000  0.000000  
554  0.201851  0.561287  0.007345  0.739496  0.041210  0.975352  0.950309  
555  0.139626  0.546644  0.006545  0.521266  0.000000  0.911013  0.921113  
556  0.277957  0.558586  0.006627  0.696276  0.041578  0.975062  0.940703  

[557 rows x 48 columns]

In [42]:
x_test

매출액증가율   유형자산증가율   재고자산증가율  비유동자산증가율   유동자산증가율   자기자본증가율    총자본증가율  \
0    0.284691  0.165975  0.076293  0.609706  0.237904  0.890221  0.591485   
1    0.351854  0.177395  0.132191  0.291260  0.562328  0.587990  0.637286   
2    0.387776  0.144740  0.103678  0.359747  1.000000  0.354947  1.000000   
3    0.194598  0.262095  0.017338  0.556470  0.342223  0.490031  0.587481   
4    0.146319  0.089105  0.027323  0.258094  0.128754  0.142420  0.218313   
..        ...       ...       ...       ...       ...       ...       ...   
249  0.232635  0.125668  0.073963  0.305467  0.210319  0.304168  0.315863   
250  0.108946  0.353669  0.138943  1.000000  0.528534  0.851058  1.000000   
251  0.033385  0.107565  0.036242  0.100818  0.065264  0.339153  0.103927   
252  0.288377  0.134224  0.078460  0.256750  0.314973  0.385755  0.406882   
253  0.035409  0.051955  0.046277  0.125293  0.130925  0.339153  0.185614   

       순이익증가율   매출액총이익률   매출액순이익률  ...   유동자산회전률   당좌자산회전률      부가가치  \
0    0.100370  0.592001  0.742790  ...  0.174229  0.144366  0.040438   
1    0.050436  0.562370  0.722420  ...  0.092559  0.064554  0.035882   
2    0.100370  0.298117  0.655009  ...  0.039927  0.026995  0.021386   
3    0.100370  0.075069  0.000000  ...  0.021779  0.014085  0.011850   
4    0.100370  0.011489  0.558980  ...  0.152450  0.099765  0.003673   
..        ...       ...       ...  ...       ...       ...       ...   
249  0.100370  0.426659  0.663458  ...  0.121597  0.084507  0.022513   
250  0.100370  0.242484  0.562691  ...  0.087114  0.066901  0.020267   
251  0.100370  0.326106  0.000000  ...  0.007260  0.004695  0.000000   
252  0.108379  0.254665  0.724753  ...  0.477314  0.368545  0.061452   
253  0.100370  0.000000  0.360292  ...  0.099819  0.086854  0.013076   

      총자본투자효율    설비투자효율    기계투자효율     부가가치율   노동소득분배율     자본분배율     이윤분배율  
0    0.220322  0.556177  0.006629  0.671450  0.040927  0.975575  0.951158  
1    0.212252  0.557266  0.006582  0.674419  0.089201  0.937539  0.930306  
2    0.175162  0.548415  0.006554  0.601811  0.000000  0.911013  0.921113  
3    0.131816  0.529439  0.006413  0.122819  0.000000  0.911013  0.921113  
4    0.015399  0.527926  0.006499  0.480692  0.000000  0.911013  0.921113  
..        ...       ...       ...       ...       ...       ...       ...  
249  0.181751  0.562585  0.006574  0.611664  0.799457  0.377914  0.454011  
250  0.169165  0.547949  0.006558  0.577265  0.000000  0.911013  0.921113  
251  0.000000  0.500527  0.005899  0.000000  0.000000  0.911013  0.921113  
252  0.321599  0.557245  0.006637  0.702730  0.029869  0.984288  0.929251  
253  0.112863  0.545620  0.006544  0.414668  0.000000  0.911013  0.921113  

[254 rows x 48 columns]

In [43]:
mda_feature=feature["mda_feature"].tolist()
logit_feature=feature["logit_feature"].tolist()
lasso_feature=feature["lasso_feature"].tolist()
ela_feature=feature["ela_feature"].tolist()
same_feature=feature["same_feature"].tolist()

In [44]:
# 성능확인 코드
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score
from sklearn.metrics import f1_score, roc_auc_score, average_precision_score


import warnings

def get_clf_eval(MDA_y_test, pred):
    confusion = confusion_matrix(MDA_y_test, pred)
    accuracy = accuracy_score(MDA_y_test, pred)
    precision = precision_score(MDA_y_test, pred)
    recall = recall_score(MDA_y_test, pred)
    roc_score = roc_auc_score(MDA_y_test, pred)
    pr_score = average_precision_score(MDA_y_test, pred)
    f1 = f1_score(MDA_y_test, pred)
    print('오차행렬')
    print(confusion)
    print('정확도: {0:.4f}, 정밀도 : {1:.4f}, 재현율:{2:.4f},F1 스코어:{3:.4f}'.format(accuracy, precision, recall, f1, roc_score))
    print('ROC 스코어: {0:.4f}, PR score : {1:.4f}'.format(roc_score, pr_score))

In [45]:
# 임계값에 따른 오차행렬및 스코어 -------->#임계값 최적 : 재현율기준(0.1)/f1기준(0.3)
from sklearn.preprocessing import Binarizer
thresholds = [0.1,0.2,0.3,0.4,0.5]

def get_eval_by_threshold(MDA_y_test, pred_proba_c1, thresholds):
    for custom_threshold in thresholds:
        binarizer = Binarizer(threshold=custom_threshold).fit(pred_proba_c1)
        custom_predict = binarizer.transform(pred_proba_c1)
        print("임곗값:", custom_threshold)
        get_clf_eval(MDA_y_test, custom_predict)
        print("---------------------------------------------------------")


In [46]:
# Roc Auc 그래프 값 확인 코드
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score
def roc_curve_plot(MDA_y_test, pred_proba_c1):
    fprs, tprs, thresholds = roc_curve(MDA_y_test, pred_proba_c1)
    
    plt.plot(fprs, tprs, label='ROC')
    plt.plot([0,1],[0,1], 'k--', label = 'Random')
    
    start, end= plt.xlim()
    plt.xticks(np.round(np.arange(start, end, 0.1),2))
    plt.xlim(0,1); plt.ylim(0,1)
    plt.xlabel('FPR(1-Sensitivity)'); plt.ylabel('TPR(Recall)')
    plt.legend()
    plt.show()

In [47]:
mda_x_train = x_train[mda_feature].reset_index(drop='index')
mda_x_test = x_test[mda_feature].reset_index(drop='index')
mda_y_train = y_train
mda_y_test = y_test 

In [48]:
logit_x_train = x_train[logit_feature].reset_index(drop='index')
logit_x_test = x_test[logit_feature].reset_index(drop='index')
logit_y_train = y_train
logit_y_test = y_test 

In [49]:
lasso_x_train = x_train[lasso_feature].reset_index(drop='index')
lasso_x_test = x_test[lasso_feature].reset_index(drop='index')
lasso_y_train = y_train
lasso_y_test = y_test 

In [50]:
ela_x_train = x_train[ela_feature].reset_index(drop='index')
ela_x_test = x_test[ela_feature].reset_index(drop='index')
ela_y_train = y_train
ela_y_test = y_test 

In [51]:
same_x_train = x_train[same_feature].reset_index(drop='index')
same_x_test = x_test[same_feature].reset_index(drop='index')
same_y_train = y_train
same_y_test = y_test 

In [52]:
fea_x_train = [mda_x_train, logit_x_train, lasso_x_train, ela_x_train, same_x_train]
fea_y_train = [mda_y_train, logit_y_train, lasso_y_train, ela_y_train, same_y_train]
fea_x_test = [mda_x_test, logit_x_test, lasso_x_test, ela_x_test, same_x_test]
fea_y_test = [mda_y_test, logit_y_test, lasso_y_test, ela_y_test, same_y_test]
fea = ["mda","logit","lasso","ela","same"]

In [53]:
# 1-1 LDA 
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
lda_clf = LinearDiscriminantAnalysis()
for x_train,y_train,x_test,y_test,feature in zip(fea_x_train,fea_y_train,fea_x_test, fea_y_test, fea):
    lda_clf.fit(x_train, y_train)
    lda_pred = lda_clf.predict(x_test)
    lda_pred_proba = lda_clf.predict_proba(x_test)
    print(feature,"lda") 
    get_clf_eval(y_test, lda_pred)
    get_eval_by_threshold(y_test , lda_pred_proba[:,1].reshape(-1,1), thresholds)



mda lda
오차행렬
[[197   7]
 [ 38  12]]
정확도: 0.8228, 정밀도 : 0.6316, 재현율:0.2400,F1 스코어:0.3478
ROC 스코어: 0.6028, PR score : 0.3012
임곗값: 0.1
오차행렬
[[ 67 137]
 [  7  43]]
정확도: 0.4331, 정밀도 : 0.2389, 재현율:0.8600,F1 스코어:0.3739
ROC 스코어: 0.5942, PR score : 0.2330
---------------------------------------------------------
임곗값: 0.2
오차행렬
[[140  64]
 [ 14  36]]
정확도: 0.6929, 정밀도 : 0.3600, 재현율:0.7200,F1 스코어:0.4800
ROC 스코어: 0.7031, PR score : 0.3143
---------------------------------------------------------
임곗값: 0.3
오차행렬
[[175  29]
 [ 25  25]]
정확도: 0.7874, 정밀도 : 0.4630, 재현율:0.5000,F1 스코어:0.4808
ROC 스코어: 0.6789, PR score : 0.3299
---------------------------------------------------------
임곗값: 0.4
오차행렬
[[190  14]
 [ 33  17]]
정확도: 0.8150, 정밀도 : 0.5484, 재현율:0.3400,F1 스코어:0.4198
ROC 스코어: 0.6357, PR score : 0.3164
---------------------------------------------------------
임곗값: 0.5
오차행렬
[[197   7]
 [ 38  12]]
정확도: 0.8228, 정밀도 : 0.6316, 재현율:0.2400,F1 스코어:0.3478
ROC 스코어: 0.6028, PR score : 0.3012
-------------------------

In [54]:
# 1-2 디시전트리 
from sklearn.tree import DecisionTreeClassifier 
dt_clf = DecisionTreeClassifier(random_state=52)
for x_train,y_train,x_test,y_test,feature in zip(fea_x_train,fea_y_train,fea_x_test, fea_y_test, fea):
    dt_clf.fit(x_train, y_train)
    dt_pred = dt_clf.predict(x_test)
    dt_pred_proba = dt_clf.predict_proba(x_test)   
    print(feature,"디시전트리") 
    get_clf_eval(y_test, dt_pred)
    get_eval_by_threshold(y_test , dt_pred_proba[:,1].reshape(-1,1), thresholds)
    


mda 디시전트리
오차행렬
[[173  31]
 [ 30  20]]
정확도: 0.7598, 정밀도 : 0.3922, 재현율:0.4000,F1 스코어:0.3960
ROC 스코어: 0.6240, PR score : 0.2750
임곗값: 0.1
오차행렬
[[173  31]
 [ 30  20]]
정확도: 0.7598, 정밀도 : 0.3922, 재현율:0.4000,F1 스코어:0.3960
ROC 스코어: 0.6240, PR score : 0.2750
---------------------------------------------------------
임곗값: 0.2
오차행렬
[[173  31]
 [ 30  20]]
정확도: 0.7598, 정밀도 : 0.3922, 재현율:0.4000,F1 스코어:0.3960
ROC 스코어: 0.6240, PR score : 0.2750
---------------------------------------------------------
임곗값: 0.3
오차행렬
[[173  31]
 [ 30  20]]
정확도: 0.7598, 정밀도 : 0.3922, 재현율:0.4000,F1 스코어:0.3960
ROC 스코어: 0.6240, PR score : 0.2750
---------------------------------------------------------
임곗값: 0.4
오차행렬
[[173  31]
 [ 30  20]]
정확도: 0.7598, 정밀도 : 0.3922, 재현율:0.4000,F1 스코어:0.3960
ROC 스코어: 0.6240, PR score : 0.2750
---------------------------------------------------------
임곗값: 0.5
오차행렬
[[173  31]
 [ 30  20]]
정확도: 0.7598, 정밀도 : 0.3922, 재현율:0.4000,F1 스코어:0.3960
ROC 스코어: 0.6240, PR score : 0.2750
-----------------------

In [55]:
from sklearn.tree import DecisionTreeClassifier 
dt_clf = DecisionTreeClassifier(random_state=52)
from sklearn.model_selection import GridSearchCV
tree = DecisionTreeClassifier(random_state=52)
for x_train,y_train,x_test,y_test,feature in zip(fea_x_train,fea_y_train,fea_x_test, fea_y_test, fea):
    # key: 하이퍼파라미터 명; value: [후보값들] 을 리스트로 전달
    param_grid = {
      'criterion': ['entropy', 'gini'],
               'max_depth': [2,4,6,8],
               'max_features': ['auto', 'sqrt'],
               'min_samples_leaf': [4,6,8,10],
               'min_samples_split': [4,6,8,10]}
    grid_search = GridSearchCV(tree
                            , param_grid = param_grid
                            , cv = 5 #교차검증시 fold 개수; n번의 교차검증; 데이터들이 돌아가면서 하나씩 검증(validation)에 사용되어 일반화하는 것; 데이터가 많지 않을 때 보통 쓰인다고 함
                            , n_jobs = -1)  #-1: 모든 코어 사용

    grid_search.fit(x_train, y_train)

    # 최선의 결과 출력
    print('피처:{2} 최적 하이퍼 파라미터 :{0}, 최적 평균 정확도 :{1:.3f}'.format(grid_search.best_params_, grid_search.best_score_, feature))
    a = grid_search.best_params_
    keys=list(a.keys())
    values = list(a.values())

    dt_clf_best = DecisionTreeClassifier(random_state=52,criterion = values[0], max_depth = values[1],max_features=values[2], min_samples_leaf=values[3], min_samples_split=values[4])
    dt_clf_best.fit(x_train, y_train)
    dt_best_pred = dt_clf_best.predict(x_test)
    dt_best_pred_proba = dt_clf_best.predict_proba(x_test)   

    print(feature,"디시전트리 파라미터적용") 
    get_clf_eval(y_test, dt_best_pred)
    get_eval_by_threshold(y_test ,dt_best_pred_proba[:,1].reshape(-1,1), thresholds)


피처:mda 최적 하이퍼 파라미터 :{'criterion': 'gini', 'max_depth': 4, 'max_features': 'auto', 'min_samples_leaf': 4, 'min_samples_split': 4}, 최적 평균 정확도 :0.820
mda 디시전트리 파라미터적용
오차행렬
[[196   8]
 [ 38  12]]
정확도: 0.8189, 정밀도 : 0.6000, 재현율:0.2400,F1 스코어:0.3429
ROC 스코어: 0.6004, PR score : 0.2936
임곗값: 0.1
오차행렬
[[ 63 141]
 [ 12  38]]
정확도: 0.3976, 정밀도 : 0.2123, 재현율:0.7600,F1 스코어:0.3319
ROC 스코어: 0.5344, PR score : 0.2086
---------------------------------------------------------
임곗값: 0.2
오차행렬
[[166  38]
 [ 27  23]]
정확도: 0.7441, 정밀도 : 0.3770, 재현율:0.4600,F1 스코어:0.4144
ROC 스코어: 0.6369, PR score : 0.2797
---------------------------------------------------------
임곗값: 0.3
오차행렬
[[166  38]
 [ 27  23]]
정확도: 0.7441, 정밀도 : 0.3770, 재현율:0.4600,F1 스코어:0.4144
ROC 스코어: 0.6369, PR score : 0.2797
---------------------------------------------------------
임곗값: 0.4
오차행렬
[[193  11]
 [ 35  15]]
정확도: 0.8189, 정밀도 : 0.5769, 재현율:0.3000,F1 스코어:0.3947
ROC 스코어: 0.6230, PR score : 0.3109
---------------------------------------------------

In [56]:
# 1-3 랜덤포레스트 구현 
from sklearn.ensemble import RandomForestClassifier
rf_clf = RandomForestClassifier(random_state=52)    
for x_train,y_train,x_test,y_test,feature in zip(fea_x_train,fea_y_train,fea_x_test, fea_y_test, fea):
    rf_clf.fit(x_train, y_train)
    rf_pred = rf_clf.predict(x_test)
    rf_pred_proba = rf_clf.predict_proba(x_test)
    print(feature,"랜덤포레스트") 
    get_clf_eval(y_test, rf_pred)
    get_eval_by_threshold(y_test , rf_pred_proba[:,1].reshape(-1,1), thresholds)
    


mda 랜덤포레스트
오차행렬
[[194  10]
 [ 36  14]]
정확도: 0.8189, 정밀도 : 0.5833, 재현율:0.2800,F1 스코어:0.3784
ROC 스코어: 0.6155, PR score : 0.3051
임곗값: 0.1
오차행렬
[[ 84 120]
 [  8  42]]
정확도: 0.4961, 정밀도 : 0.2593, 재현율:0.8400,F1 스코어:0.3962
ROC 스코어: 0.6259, PR score : 0.2493
---------------------------------------------------------
임곗값: 0.2
오차행렬
[[149  55]
 [ 17  33]]
정확도: 0.7165, 정밀도 : 0.3750, 재현율:0.6600,F1 스코어:0.4783
ROC 스코어: 0.6952, PR score : 0.3144
---------------------------------------------------------
임곗값: 0.3
오차행렬
[[174  30]
 [ 20  30]]
정확도: 0.8031, 정밀도 : 0.5000, 재현율:0.6000,F1 스코어:0.5455
ROC 스코어: 0.7265, PR score : 0.3787
---------------------------------------------------------
임곗값: 0.4
오차행렬
[[186  18]
 [ 33  17]]
정확도: 0.7992, 정밀도 : 0.4857, 재현율:0.3400,F1 스코어:0.4000
ROC 스코어: 0.6259, PR score : 0.2951
---------------------------------------------------------
임곗값: 0.5
오차행렬
[[194  10]
 [ 36  14]]
정확도: 0.8189, 정밀도 : 0.5833, 재현율:0.2800,F1 스코어:0.3784
ROC 스코어: 0.6155, PR score : 0.3051
----------------------

In [57]:
# 하이퍼파라미터 Grid-Search
from sklearn.model_selection import GridSearchCV

    # 탐색 범위 정의
for x_train,y_train,x_test,y_test,feature in zip(fea_x_train,fea_y_train,fea_x_test, fea_y_test, fea):
    grid_search = {'criterion': ['entropy', 'gini'],
                'max_depth': [2,4,6,8],
                'max_features': ['auto', 'sqrt'],
                'min_samples_leaf': [4,6,8,10],
                'min_samples_split': [4,6,8,10],
                'n_estimators': [20,40,60,80,100]}

    model = RandomForestClassifier(random_state=52)
    grid_search = GridSearchCV(estimator = model, param_grid = grid_search, 
                                cv = 5,verbose=0, n_jobs = -1)
    grid_search.fit(x_train,y_train)

    # 최선의 결과 출력
    print('최적 하이퍼 파라미터 :{0}, 최적 평균 정확도 :{1:.3f}'.format(grid_search.best_params_, grid_search.best_score_))
    a = grid_search.best_params_
    keys=list(a.keys())
    values = list(a.values())

    rf_clf_best = RandomForestClassifier(random_state=52,criterion = values[0], max_depth = values[1],max_features=values[2], min_samples_leaf=values[3],  min_samples_split=values[4],n_estimators=values[5])
    rf_clf_best.fit(x_train, y_train)
    rf_best_pred = rf_clf_best.predict(x_test)
    rf_best_pred_proba = rf_clf_best.predict_proba(x_test)   

    print(feature,"디시전트리 파라미터적용") 
    get_clf_eval(y_test, rf_best_pred)
    get_eval_by_threshold(y_test ,rf_best_pred_proba[:,1].reshape(-1,1), thresholds)

최적 하이퍼 파라미터 :{'criterion': 'entropy', 'max_depth': 4, 'max_features': 'auto', 'min_samples_leaf': 8, 'min_samples_split': 4, 'n_estimators': 40}, 최적 평균 정확도 :0.822
mda 디시전트리 파라미터적용
오차행렬
[[197   7]
 [ 40  10]]
정확도: 0.8150, 정밀도 : 0.5882, 재현율:0.2000,F1 스코어:0.2985
ROC 스코어: 0.5828, PR score : 0.2751
임곗값: 0.1
오차행렬
[[ 77 127]
 [ 10  40]]
정확도: 0.4606, 정밀도 : 0.2395, 재현율:0.8000,F1 스코어:0.3687
ROC 스코어: 0.5887, PR score : 0.2310
---------------------------------------------------------
임곗값: 0.2
오차행렬
[[151  53]
 [ 15  35]]
정확도: 0.7323, 정밀도 : 0.3977, 재현율:0.7000,F1 스코어:0.5072
ROC 스코어: 0.7201, PR score : 0.3375
---------------------------------------------------------
임곗값: 0.3
오차행렬
[[173  31]
 [ 20  30]]
정확도: 0.7992, 정밀도 : 0.4918, 재현율:0.6000,F1 스코어:0.5405
ROC 스코어: 0.7240, PR score : 0.3738
---------------------------------------------------------
임곗값: 0.4
오차행렬
[[188  16]
 [ 33  17]]
정확도: 0.8071, 정밀도 : 0.5152, 재현율:0.3400,F1 스코어:0.4096
ROC 스코어: 0.6308, PR score : 0.3051
-----------------------------------

In [58]:
# 1-4 로지스틱회귀
from sklearn.linear_model import LogisticRegression
lr_clf = LogisticRegression()
for x_train,y_train,x_test,y_test,feature in zip(fea_x_train,fea_y_train,fea_x_test, fea_y_test, fea):
    lr_clf.fit(x_train, y_train)
    lr_pred = lr_clf.predict(x_test)
    lr_pred_proba = lr_clf.predict_proba(x_test)
    print(feature,"로지스틱회귀") 
    get_clf_eval(y_test, lr_pred)
    get_eval_by_threshold(y_test , lr_pred_proba[:,1].reshape(-1,1), thresholds)
    

mda 로지스틱회귀
오차행렬
[[200   4]
 [ 42   8]]
정확도: 0.8189, 정밀도 : 0.6667, 재현율:0.1600,F1 스코어:0.2581
ROC 스코어: 0.5702, PR score : 0.2720
임곗값: 0.1
오차행렬
[[ 40 164]
 [  5  45]]
정확도: 0.3346, 정밀도 : 0.2153, 재현율:0.9000,F1 스코어:0.3475
ROC 스코어: 0.5480, PR score : 0.2135
---------------------------------------------------------
임곗값: 0.2
오차행렬
[[133  71]
 [ 15  35]]
정확도: 0.6614, 정밀도 : 0.3302, 재현율:0.7000,F1 스코어:0.4487
ROC 스코어: 0.6760, PR score : 0.2902
---------------------------------------------------------
임곗값: 0.3
오차행렬
[[176  28]
 [ 26  24]]
정확도: 0.7874, 정밀도 : 0.4615, 재현율:0.4800,F1 스코어:0.4706
ROC 스코어: 0.6714, PR score : 0.3239
---------------------------------------------------------
임곗값: 0.4
오차행렬
[[195   9]
 [ 35  15]]
정확도: 0.8268, 정밀도 : 0.6250, 재현율:0.3000,F1 스코어:0.4054
ROC 스코어: 0.6279, PR score : 0.3253
---------------------------------------------------------
임곗값: 0.5
오차행렬
[[200   4]
 [ 42   8]]
정확도: 0.8189, 정밀도 : 0.6667, 재현율:0.1600,F1 스코어:0.2581
ROC 스코어: 0.5702, PR score : 0.2720
----------------------

In [59]:
#로지스틱 회귀 최적 하이퍼 파라미터
from sklearn.model_selection import GridSearchCV

for x_train,y_train,x_test,y_test,feature in zip(fea_x_train,fea_y_train,fea_x_test, fea_y_test, fea):
    params = {'penalty': ['l2','l1','elasticnet','None'],
            'C':[0.01,0.1,1,3,5,10]}

    grid_search = GridSearchCV(lr_clf, param_grid=params, scoring='accuracy', cv=5)
    grid_search.fit(x_train,y_train)
    print('최적 하이퍼 파라미어:{0}, 최적 평균 정확도:{1:.3f}'.format(grid_search.best_params_, grid_search.best_score_))

    a = grid_search.best_params_
    keys=list(a.keys())
    values = list(a.values())

    lr_clf_best = LogisticRegression(penalty= values[1], C=values[0])
    lr_clf_best.fit(x_train, y_train)
    lr_best_pred = lr_clf_best.predict(x_test)
    lr_best_pred_proba = lr_clf_best.predict_proba(x_test)   

    print(feature,"로지스틱회귀 파라미터적용") 
    get_clf_eval(y_test, lr_best_pred)
    get_eval_by_threshold(y_test ,lr_best_pred_proba[:,1].reshape(-1,1), thresholds)


최적 하이퍼 파라미어:{'C': 10, 'penalty': 'l2'}, 최적 평균 정확도:0.803
mda 로지스틱회귀 파라미터적용
오차행렬
[[198   6]
 [ 38  12]]
정확도: 0.8268, 정밀도 : 0.6667, 재현율:0.2400,F1 스코어:0.3529
ROC 스코어: 0.6053, PR score : 0.3096
임곗값: 0.1
오차행렬
[[ 68 136]
 [  6  44]]
정확도: 0.4409, 정밀도 : 0.2444, 재현율:0.8800,F1 스코어:0.3826
ROC 스코어: 0.6067, PR score : 0.2387
---------------------------------------------------------
임곗값: 0.2
오차행렬
[[135  69]
 [ 15  35]]
정확도: 0.6693, 정밀도 : 0.3365, 재현율:0.7000,F1 스코어:0.4545
ROC 스코어: 0.6809, PR score : 0.2946
---------------------------------------------------------
임곗값: 0.3
오차행렬
[[176  28]
 [ 22  28]]
정확도: 0.8031, 정밀도 : 0.5000, 재현율:0.5600,F1 스코어:0.5283
ROC 스코어: 0.7114, PR score : 0.3666
---------------------------------------------------------
임곗값: 0.4
오차행렬
[[191  13]
 [ 32  18]]
정확도: 0.8228, 정밀도 : 0.5806, 재현율:0.3600,F1 스코어:0.4444
ROC 스코어: 0.6481, PR score : 0.3350
---------------------------------------------------------
임곗값: 0.5
오차행렬
[[198   6]
 [ 38  12]]
정확도: 0.8268, 정밀도 : 0.6667, 재현율:0.2400,F1 스코어:0

In [60]:
# 1-5 KNN 
from sklearn.neighbors import KNeighborsClassifier
knn_clf = KNeighborsClassifier(n_neighbors=5)
for x_train,y_train,x_test,y_test,feature in zip(fea_x_train,fea_y_train,fea_x_test, fea_y_test, fea):

    knn_clf.fit(x_train, y_train)
    knn_pred = knn_clf.predict(x_test)
    knn_pred_proba = knn_clf.predict_proba(x_test)
    print(feature,"KNN") 
    get_clf_eval(y_test, knn_pred)
    get_eval_by_threshold(y_test , knn_pred_proba[:,1].reshape(-1,1), thresholds)



mda KNN
오차행렬
[[189  15]
 [ 35  15]]
정확도: 0.8031, 정밀도 : 0.5000, 재현율:0.3000,F1 스코어:0.3750
ROC 스코어: 0.6132, PR score : 0.2878
임곗값: 0.1
오차행렬
[[ 99 105]
 [ 13  37]]
정확도: 0.5354, 정밀도 : 0.2606, 재현율:0.7400,F1 스코어:0.3854
ROC 스코어: 0.6126, PR score : 0.2440
---------------------------------------------------------
임곗값: 0.2
오차행렬
[[162  42]
 [ 27  23]]
정확도: 0.7283, 정밀도 : 0.3538, 재현율:0.4600,F1 스코어:0.4000
ROC 스코어: 0.6271, PR score : 0.2691
---------------------------------------------------------
임곗값: 0.3
오차행렬
[[162  42]
 [ 27  23]]
정확도: 0.7283, 정밀도 : 0.3538, 재현율:0.4600,F1 스코어:0.4000
ROC 스코어: 0.6271, PR score : 0.2691
---------------------------------------------------------
임곗값: 0.4
오차행렬
[[189  15]
 [ 35  15]]
정확도: 0.8031, 정밀도 : 0.5000, 재현율:0.3000,F1 스코어:0.3750
ROC 스코어: 0.6132, PR score : 0.2878
---------------------------------------------------------
임곗값: 0.5
오차행렬
[[189  15]
 [ 35  15]]
정확도: 0.8031, 정밀도 : 0.5000, 재현율:0.3000,F1 스코어:0.3750
ROC 스코어: 0.6132, PR score : 0.2878
-------------------------

In [61]:
# knn 파라미터 구하기
from sklearn.metrics import accuracy_score
acc = []
for x_train,y_train,x_test,y_test,feature in zip(fea_x_train,fea_y_train,fea_x_test, fea_y_test, fea):
    for k in range(1,20):
        knn_clf = KNeighborsClassifier(n_neighbors=k)
        knn_clf.fit(x_train, y_train)
        knn_pred = knn_clf.predict(x_test)
        knn_score=accuracy_score(y_test,knn_pred)

        acc.append(knn_score)
    int = acc.index(max(acc))+1
    print("최적거리")
    print(int)

    knn_clf_best =KNeighborsClassifier(n_neighbors=int)
    knn_clf_best.fit(x_train, y_train)
    knn_best_pred = knn_clf_best.predict(x_test)
    knn_best_pred_proba = knn_clf_best.predict_proba(x_test)   

    print(feature,"KNN 파라미터적용") 
    get_clf_eval(y_test, knn_best_pred)
    get_eval_by_threshold(y_test ,knn_best_pred_proba[:,1].reshape(-1,1), thresholds)      


최적거리
2
mda KNN 파라미터적용
오차행렬
[[200   4]
 [ 39  11]]
정확도: 0.8307, 정밀도 : 0.7333, 재현율:0.2200,F1 스코어:0.3385
ROC 스코어: 0.6002, PR score : 0.3149
임곗값: 0.1
오차행렬
[[149  55]
 [ 21  29]]
정확도: 0.7008, 정밀도 : 0.3452, 재현율:0.5800,F1 스코어:0.4328
ROC 스코어: 0.6552, PR score : 0.2829
---------------------------------------------------------
임곗값: 0.2
오차행렬
[[149  55]
 [ 21  29]]
정확도: 0.7008, 정밀도 : 0.3452, 재현율:0.5800,F1 스코어:0.4328
ROC 스코어: 0.6552, PR score : 0.2829
---------------------------------------------------------
임곗값: 0.3
오차행렬
[[149  55]
 [ 21  29]]
정확도: 0.7008, 정밀도 : 0.3452, 재현율:0.5800,F1 스코어:0.4328
ROC 스코어: 0.6552, PR score : 0.2829
---------------------------------------------------------
임곗값: 0.4
오차행렬
[[149  55]
 [ 21  29]]
정확도: 0.7008, 정밀도 : 0.3452, 재현율:0.5800,F1 스코어:0.4328
ROC 스코어: 0.6552, PR score : 0.2829
---------------------------------------------------------
임곗값: 0.5
오차행렬
[[200   4]
 [ 39  11]]
정확도: 0.8307, 정밀도 : 0.7333, 재현율:0.2200,F1 스코어:0.3385
ROC 스코어: 0.6002, PR score : 0.3149
-----------

In [62]:
# 1-5 xgboost
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
import xgboost as xgb ## XGBoost 불러오기
from xgboost import plot_importance 

xgb_wrapper = XGBClassifier()
for x_train,y_train,x_test,y_test,feature in zip(fea_x_train,fea_y_train,fea_x_test, fea_y_test, fea):

    xgb_wrapper.fit(x_train, y_train, verbose = True)
    xgb_wrapper.fit(x_train, y_train)
    xgb_pred = xgb_wrapper.predict(x_test)
    xgb_pred_proba = xgb_wrapper.predict_proba(x_test)
    print(feature,"XGB") 
    get_clf_eval(y_test, xgb_pred)
    get_eval_by_threshold(y_test , xgb_pred_proba[:,1].reshape(-1,1), thresholds)

mda XGB
오차행렬
[[191  13]
 [ 31  19]]
정확도: 0.8268, 정밀도 : 0.5938, 재현율:0.3800,F1 스코어:0.4634
ROC 스코어: 0.6581, PR score : 0.3477
임곗값: 0.1
오차행렬
[[164  40]
 [ 23  27]]
정확도: 0.7520, 정밀도 : 0.4030, 재현율:0.5400,F1 스코어:0.4615
ROC 스코어: 0.6720, PR score : 0.3082
---------------------------------------------------------
임곗값: 0.2
오차행렬
[[179  25]
 [ 25  25]]
정확도: 0.8031, 정밀도 : 0.5000, 재현율:0.5000,F1 스코어:0.5000
ROC 스코어: 0.6887, PR score : 0.3484
---------------------------------------------------------
임곗값: 0.3
오차행렬
[[187  17]
 [ 27  23]]
정확도: 0.8268, 정밀도 : 0.5750, 재현율:0.4600,F1 스코어:0.5111
ROC 스코어: 0.6883, PR score : 0.3708
---------------------------------------------------------
임곗값: 0.4
오차행렬
[[190  14]
 [ 29  21]]
정확도: 0.8307, 정밀도 : 0.6000, 재현율:0.4200,F1 스코어:0.4941
ROC 스코어: 0.6757, PR score : 0.3662
---------------------------------------------------------
임곗값: 0.5
오차행렬
[[191  13]
 [ 31  19]]
정확도: 0.8268, 정밀도 : 0.5938, 재현율:0.3800,F1 스코어:0.4634
ROC 스코어: 0.6581, PR score : 0.3477
-------------------------

In [ ]:
values[1]

'l2'

In [ ]:
#xgb 최적 하이퍼 파라미터
from sklearn.model_selection import GridSearchCV

xgb_wrapper
for x_train,y_train,x_test,y_test,feature in zip(fea_x_train,fea_y_train,fea_x_test, fea_y_test, fea):
    params = {
            'n_estimators':[40,43,46,50],
            'learning_rate':[0.03,0.05,0.04],
            'max_depth' : [0.8,1,2,3,4]
            }

    grid_clf = GridSearchCV(xgb_wrapper, param_grid=params, scoring='accuracy', cv=5)
    grid_clf.fit(x_train,y_train)
    print('최적 하이퍼 파라미어:{0}, 최적 평균 정확도:{1:.3f}'.format(grid_clf.best_params_, grid_clf.best_score_))

    a = grid_clf.best_params_
    keys=list(a.keys())
    values = list(a.values())
    xgb_clf_best = XGBClassifier( learning_rate=values[0],max_depth=values[1],n_estimators= values[2])
    xgb_clf_best.fit(x_train, y_train)
    xgb_best_pred = xgb_clf_best.predict(x_test)
    xgb_best_pred_proba = xgb_clf_best.predict_proba(x_test)   

    print(feature,"XGB 파라미터적용") 
    get_clf_eval(y_test, xgb_best_pred)
    get_eval_by_threshold(y_test ,xgb_best_pred_proba[:,1].reshape(-1,1), thresholds)

최적 하이퍼 파라미어:{'learning_rate': 0.04, 'max_depth': 3, 'n_estimators': 50}, 최적 평균 정확도:0.824
mda XGB 파라미터적용
오차행렬
[[190  14]
 [ 33  17]]
정확도: 0.8150, 정밀도 : 0.5484, 재현율:0.3400,F1 스코어:0.4198
ROC 스코어: 0.6357, PR score : 0.3164
임곗값: 0.1
오차행렬
[[  0 204]
 [  0  50]]
정확도: 0.1969, 정밀도 : 0.1969, 재현율:1.0000,F1 스코어:0.3289
ROC 스코어: 0.5000, PR score : 0.1969
---------------------------------------------------------
임곗값: 0.2
오차행렬
[[137  67]
 [ 12  38]]
정확도: 0.6890, 정밀도 : 0.3619, 재현율:0.7600,F1 스코어:0.4903
ROC 스코어: 0.7158, PR score : 0.3223
---------------------------------------------------------
임곗값: 0.3
오차행렬
[[177  27]
 [ 23  27]]
정확도: 0.8031, 정밀도 : 0.5000, 재현율:0.5400,F1 스코어:0.5192
ROC 스코어: 0.7038, PR score : 0.3606
---------------------------------------------------------
임곗값: 0.4
오차행렬
[[186  18]
 [ 31  19]]
정확도: 0.8071, 정밀도 : 0.5135, 재현율:0.3800,F1 스코어:0.4368
ROC 스코어: 0.6459, PR score : 0.3172
---------------------------------------------------------
임곗값: 0.5
오차행렬
[[190  14]
 [ 33  17]]
정확도: 0.8150, 정밀도