In [1]:
# 필요 라이브러리 import 
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_csv("./데이터자료/9-2. Std 데이터셋.csv")
feature = pd.read_csv("./데이터자료/8-2. Std feature.csv")
df

회사명   거래소코드        회계년도         상장일 상장폐지일  소속코드  \
0     (주)CMG제약   58820  2011-12-01  2001-08-31   NaN     5   
1     (주)CMG제약   58820  2012-12-01  2001-08-31   NaN     5   
2     (주)CMG제약   58820  2013-12-01  2001-08-31   NaN     5   
3     (주)CMG제약   58820  2014-12-01  2001-08-31   NaN     5   
4     (주)CMG제약   58820  2015-12-01  2001-08-31   NaN     5   
...        ...     ...         ...         ...   ...   ...   
9273   휴마시스(주)  205470  2020-12-01  2014-12-01   NaN     5   
9274     휴젤(주)  145020  2019-12-01  2015-12-24   NaN     5   
9275     휴젤(주)  145020  2020-12-01  2015-12-24   NaN     5   
9276   흥구석유(주)   24060  2019-12-01  1994-12-07   NaN     5   
9277   흥구석유(주)   24060  2020-12-01  1994-12-07   NaN     5   

                     산업명    매출액증가율   유형자산증가율   재고자산증가율  ...      부가가치  \
0       의료용 물질 및 의약품 제조업  1.186494 -0.286555 -0.242712  ... -0.517775   
1       의료용 물질 및 의약품 제조업 -0.465320 -0.266139 -0.145700  ... -0.570848   
2       의료용 물질 및 의약품 제조업  0.399443 -0.034331  0.368591  ... -0.459402   
3       의료용 물질 및 의약품 제조업  0.042989  0.633335 -0.160104  ... -0.458301   
4       의료용 물질 및 의약품 제조업  0.229752 -0.280476 -0.110645  ... -0.503803   
...                  ...       ...       ...       ...  ...       ...   
9273    의료용 물질 및 의약품 제조업  5.662930  1.347455  2.510801  ... -0.151711   
9274    의료용 물질 및 의약품 제조업  0.059296 -0.046260  0.113775  ...  1.299954   
9275    의료용 물질 및 의약품 제조업 -0.170016 -0.100971 -0.437478  ...  1.349171   
9276         도매 및 상품 중개업 -0.488761 -0.299172  0.793390  ... -0.392823   
9277         도매 및 상품 중개업 -0.856425 -0.378544 -0.424663  ... -0.359343   

       총자본투자효율    설비투자효율    기계투자효율     부가가치율   노동소득분배율     자본분배율     이윤분배율  \
0    -0.268715 -0.204982 -0.097181  0.001823  0.167352 -0.034998 -0.128958   
1    -0.965957 -0.239707 -0.097246 -0.455154  7.331845 -8.395971 -8.842764   
2    -0.280668 -0.160693 -0.097092  0.377872 -0.016097  0.127964  0.136844   
3    -0.300589 -0.202938 -0.097179  0.294901  0.063259  0.057470  0.125748   
4    -0.558426 -0.217252 -0.097201 -0.090083  0.704439 -0.512105 -0.358349   
...        ...       ...       ...       ...       ...       ...       ...   
9273  1.140567 -0.125778 -0.096931  0.930074 -0.576239  0.625551  0.569922   
9274 -0.272699 -0.062404 -0.097006  0.914756 -0.434150  0.499330  0.360994   
9275 -0.301727 -0.058107 -0.096969  0.907353 -0.415350  0.482630  0.330828   
9276 -0.500939 -0.145811 -0.095817 -0.354313 -0.106535  0.208302  0.265758   
9277 -0.421255 -0.140271 -0.095169 -0.325975 -0.166101  0.261216  0.306350   

      label   회계년  
0       0.0  2011  
1       0.0  2012  
2       0.0  2013  
3       0.0  2014  
4       0.0  2015  
...     ...   ...  
9273    0.0  2020  
9274    0.0  2019  
9275    0.0  2020  
9276    0.0  2019  
9277    0.0  2020  

[9278 rows x 57 columns]

In [84]:
feature

mda_feature logit_feature lasso_feature ela_feature same_feature
0     자기자본구성비율        매출액증가율        총자본증가율     자기자본증가율     자기자본구성비율
1      매출액순이익률       유형자산증가율      자기자본순이익률      총자본증가율       자기자본배율
2      순운전자본비율       재고자산증가율      총자본사업이익률     매출액순이익률       총자본증가율
3     순운전자본회전률      비유동자산증가율       총자본순이익률    자기자본순이익률     매출채권회전기간
4      총자본투자효율       유동자산증가율       순운전자본비율    총자본사업이익률      총자본순이익률
5     자기자본순이익률          현금비율      유동자산구성비율     총자본순이익률     총자본사업이익률
6       총자본증가율    이자보상배율이자비용      자기자본구성비율     순운전자본비율      순운전자본비율
7     총자본사업이익률         비유동비율        자기자본배율    자기자본구성비율     순운전자본회전률
8       기계투자효율      자기자본구성비율       매출채권회전률      자기자본배율     자기자본순이익률
9       1주당순이익        자기자본배율      매출채권회전기간    매출채권회전기간      매출액순이익률
10     총자본순이익률       매출채권회전률      순운전자본회전률    순운전자본회전률      매출채권회전률
11      자기자본배율      매출채권회전기간       노동소득분배율       부가가치율        부가가치율

In [3]:
train = df[df["회계년"] <= 2018].reset_index(drop='index')
test  = df[df["회계년"] > 2018].reset_index(drop='index')

In [4]:
x_train = train.drop("label",axis=1)
y_train = train["label"]
x_test =test.drop("label",axis=1)
y_test = test["label"]

In [5]:
mda_feature=feature["mda_feature"].tolist()
logit_feature=feature["logit_feature"].tolist()
lasso_feature=feature["lasso_feature"].tolist()
ela_feature=feature["ela_feature"].tolist()
same_feature=feature["same_feature"].tolist()

In [6]:
# 성능확인 코드
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score
from sklearn.metrics import f1_score, roc_auc_score, average_precision_score


import warnings

def get_clf_eval(MDA_y_test, pred):
    confusion = confusion_matrix(MDA_y_test, pred)
    accuracy = accuracy_score(MDA_y_test, pred)
    precision = precision_score(MDA_y_test, pred)
    recall = recall_score(MDA_y_test, pred)
    roc_score = roc_auc_score(MDA_y_test, pred)
    pr_score = average_precision_score(MDA_y_test, pred)
    f1 = f1_score(MDA_y_test, pred)
    print('오차행렬')
    print(confusion)
    print('정확도: {0:.4f}, 정밀도 : {1:.4f}, 재현율:{2:.4f},F1 스코어:{3:.4f}'.format(accuracy, precision, recall, f1, roc_score))
    print('ROC 스코어: {0:.4f}, PR score : {1:.4f}'.format(roc_score, pr_score))

# 1. mda_feature

In [7]:
mda_x_train = x_train[mda_feature].reset_index(drop='index')
mda_x_test = x_test[mda_feature].reset_index(drop='index')
mda_y_train = train["label"]
mda_y_test = test["label"]

In [8]:
# 1-1 LDA 
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
lda_clf = LinearDiscriminantAnalysis()
lda_clf.fit(mda_x_train, mda_y_train)
lda_pred = lda_clf.predict(mda_x_test)
lda_pred_proba = lda_clf.predict_proba(mda_x_test)

In [9]:
print("lda") 
print(get_clf_eval(mda_y_test, lda_pred))

lda
오차행렬
[[2252   63]
 [  32   18]]
정확도: 0.9598, 정밀도 : 0.2222, 재현율:0.3600,F1 스코어:0.2748
ROC 스코어: 0.6664, PR score : 0.0935
None


In [10]:
# 디시전트리 구현
from sklearn.tree import DecisionTreeClassifier 
dt_clf = DecisionTreeClassifier(random_state=52)     
dt_clf.fit(mda_x_train, mda_y_train)
dt_pred = dt_clf.predict(mda_x_test)
dt_pred_proba = dt_clf.predict_proba(mda_x_test)                                    

In [11]:
print("디시전트리") 
print(get_clf_eval(mda_y_test, dt_pred))

디시전트리
오차행렬
[[2267   48]
 [  41    9]]
정확도: 0.9624, 정밀도 : 0.1579, 재현율:0.1800,F1 스코어:0.1682
ROC 스코어: 0.5796, PR score : 0.0458
None


In [12]:
# 랜덤포레스트 구현
from sklearn.ensemble import RandomForestClassifier
rf_clf = RandomForestClassifier(random_state=52)     
rf_clf.fit(mda_x_train, mda_y_train)
rf_pred = rf_clf.predict(mda_x_test)
rf_pred_proba = rf_clf.predict_proba(mda_x_test)

In [13]:
print("랜덤포레스트") 
get_clf_eval(mda_y_test, rf_pred)

랜덤포레스트
오차행렬
[[2308    7]
 [  41    9]]
정확도: 0.9797, 정밀도 : 0.5625, 재현율:0.1800,F1 스코어:0.2727
ROC 스코어: 0.5885, PR score : 0.1186


In [14]:
# 로지스틱 회귀 모델
from sklearn.linear_model import LogisticRegression
lr_clf = LogisticRegression()
lr_clf.fit(mda_x_train, mda_y_train)
lr_pred = lr_clf.predict(mda_x_test)
lr_pred_proba = lr_clf.predict_proba(mda_x_test)

In [15]:
print("로지스틱") 
get_clf_eval(mda_y_test, lr_pred)

로지스틱
오차행렬
[[2309    6]
 [  46    4]]
정확도: 0.9780, 정밀도 : 0.4000, 재현율:0.0800,F1 스코어:0.1333
ROC 스코어: 0.5387, PR score : 0.0515


In [16]:
# KNN 모형 구현
from sklearn.neighbors import KNeighborsClassifier

knn_clf = KNeighborsClassifier(n_neighbors=5)
knn_clf.fit(mda_x_train, mda_y_train)
knn_pred = knn_clf.predict(mda_x_test)
knn_pred_proba = knn_clf.predict_proba(mda_x_test)

c:\Users\young\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [17]:
print("knn") 
get_clf_eval(mda_y_test, knn_pred)

knn
오차행렬
[[2312    3]
 [  45    5]]
정확도: 0.9797, 정밀도 : 0.6250, 재현율:0.1000,F1 스코어:0.1724
ROC 스코어: 0.5494, PR score : 0.0815


In [18]:
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
import xgboost as xgb ## XGBoost 불러오기
from xgboost import plot_importance 
mda_x_train2 = mda_x_train.copy()
mda_x_test2 = mda_x_test.copy()
mda_y_train2 = mda_y_train.copy()
mda_y_test2 = mda_y_test.copy()
mda_x_train2.columns = [mda_feature]
mda_x_test2.columns =[mda_feature]

xgb_wrapper = XGBClassifier()

xgb_wrapper.fit(mda_x_train2, mda_y_train2, verbose = True)


xgb_pred = xgb_wrapper.predict(mda_x_test)
xgb_pred_proba = xgb_wrapper.predict_proba(mda_x_test)

In [19]:
print("xgb") 
get_clf_eval(mda_y_test, xgb_pred)

xgb
오차행렬
[[2302   13]
 [  40   10]]
정확도: 0.9776, 정밀도 : 0.4348, 재현율:0.2000,F1 스코어:0.2740
ROC 스코어: 0.5972, PR score : 0.1039


In [20]:
class Perceptron(object):
    
    def __init__(self, eta = 0.1, n_iter = 50, random_state = 1): #초기화
        self.eta = eta
        self.n_iter = n_iter
        self.random_state = random_state
        
    
    def fit(self, X, y): #학습
        rgen = np.random.RandomState(self.random_state)
        self.w_ = rgen.normal(loc = 0, scale = 0,
                             size = 1 + X.shape[1])
        
        self.errors_ = []
        for _ in range(self.n_iter):
            errors = 0
            for i in range(len(X)):
                xi = X.iloc[i].values
                target = y[i]
                update = self.eta * (target - self.predict(xi))
                self.w_[1:] += update * xi
                self.w_[0] += update
                errors += int(update != 0.0)
            self.errors_.append(errors)
        return self
    
    def predict(self, X): #추론
        return np.where(self.net_input(X) >= 0.0, 1, 0)
    
    def net_input(self, X):
        return np.dot(X, self.w_[1:]) + self.w_[0]


In [21]:
pc_clf = Perceptron(n_iter = 10)
pc_clf.fit(mda_x_train, mda_y_train)
pc_pred = pc_clf.predict(mda_x_test)

In [22]:
print("퍼셉트론") 
get_clf_eval(mda_y_test, pc_pred)

퍼셉트론
오차행렬
[[2259   56]
 [  34   16]]
정확도: 0.9619, 정밀도 : 0.2222, 재현율:0.3200,F1 스코어:0.2623
ROC 스코어: 0.6479, PR score : 0.0855


# 2. lasso_feature

In [23]:
logit_x_train = x_train[logit_feature].reset_index(drop='index')
logit_x_test = x_test[logit_feature].reset_index(drop='index')
logit_y_train = train["label"]
logit_y_test = test["label"]

In [24]:
# 1-1 LDA 
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
lda_clf = LinearDiscriminantAnalysis()
lda_clf.fit(logit_x_train, logit_y_train)
lda_pred = lda_clf.predict(logit_x_test)
lda_pred_proba = lda_clf.predict_proba(logit_x_test)

In [25]:
print("lda") 
print(get_clf_eval(logit_y_test, lda_pred))

lda
오차행렬
[[2304   11]
 [  45    5]]
정확도: 0.9763, 정밀도 : 0.3125, 재현율:0.1000,F1 스코어:0.1515
ROC 스코어: 0.5476, PR score : 0.0503
None


In [26]:
# 디시전트리 구현
from sklearn.tree import DecisionTreeClassifier 
dt_clf = DecisionTreeClassifier(random_state=52)     
dt_clf.fit(logit_x_train, logit_y_train)
dt_pred = dt_clf.predict(logit_x_test)
dt_pred_proba = dt_clf.predict_proba(logit_x_test)                                    

In [27]:
print("디시전트리") 
print(get_clf_eval(logit_y_test, dt_pred))

디시전트리
오차행렬
[[2256   59]
 [  43    7]]
정확도: 0.9569, 정밀도 : 0.1061, 재현율:0.1400,F1 스코어:0.1207
ROC 스코어: 0.5573, PR score : 0.0330
None


In [28]:
# 랜덤포레스트 구현
from sklearn.ensemble import RandomForestClassifier
rf_clf = RandomForestClassifier(random_state=52)     
rf_clf.fit(logit_x_train, logit_y_train)
rf_pred = rf_clf.predict(logit_x_test)
rf_pred_proba = rf_clf.predict_proba(logit_x_test)

In [29]:
print("랜덤포레스트") 
get_clf_eval(logit_y_test, rf_pred)

랜덤포레스트
오차행렬
[[2304   11]
 [  43    7]]
정확도: 0.9772, 정밀도 : 0.3889, 재현율:0.1400,F1 스코어:0.2059
ROC 스코어: 0.5676, PR score : 0.0726


In [30]:
# 로지스틱 회귀 모델
from sklearn.linear_model import LogisticRegression
lr_clf = LogisticRegression()
lr_clf.fit(logit_x_train, logit_y_train)
lr_pred = lr_clf.predict(logit_x_test)
lr_pred_proba = lr_clf.predict_proba(logit_x_test)

In [31]:
print("로지스틱") 
get_clf_eval(logit_y_test, lr_pred)

로지스틱
오차행렬
[[2311    4]
 [  47    3]]
정확도: 0.9784, 정밀도 : 0.4286, 재현율:0.0600,F1 스코어:0.1053
ROC 스코어: 0.5291, PR score : 0.0456


In [32]:
from sklearn.neighbors import KNeighborsClassifier

knn_clf = KNeighborsClassifier(n_neighbors=5)
knn_clf.fit(logit_x_train, logit_y_train)
knn_pred = knn_clf.predict(logit_x_test)
knn_pred_proba = knn_clf.predict_proba(logit_x_test)

c:\Users\young\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [33]:
print("knn") 
get_clf_eval(logit_y_test, knn_pred)

knn
오차행렬
[[2311    4]
 [  47    3]]
정확도: 0.9784, 정밀도 : 0.4286, 재현율:0.0600,F1 스코어:0.1053
ROC 스코어: 0.5291, PR score : 0.0456


In [34]:
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
import xgboost as xgb ## XGBoost 불러오기
from xgboost import plot_importance 
logit_x_train2 = logit_x_train.copy()
logit_x_test2 = logit_x_test.copy()
logit_y_train2 = logit_y_train.copy()
logit_y_test2 = logit_y_test.copy()
logit_x_train2.columns = [logit_feature]
logit_x_test2.columns =[logit_feature]

xgb_wrapper = XGBClassifier()

xgb_wrapper.fit(logit_x_train2, logit_y_train2, verbose = True)


xgb_pred = xgb_wrapper.predict(logit_x_test)
xgb_pred_proba = xgb_wrapper.predict_proba(logit_x_test)

In [35]:
print("xgb") 
get_clf_eval(logit_y_test, xgb_pred)

xgb
오차행렬
[[2301   14]
 [  43    7]]
정확도: 0.9759, 정밀도 : 0.3333, 재현율:0.1400,F1 스코어:0.1972
ROC 스코어: 0.5670, PR score : 0.0648


In [36]:
class Perceptron(object):
    
    def __init__(self, eta = 0.1, n_iter = 50, random_state = 1): #초기화
        self.eta = eta
        self.n_iter = n_iter
        self.random_state = random_state
        
    
    def fit(self, X, y): #학습
        rgen = np.random.RandomState(self.random_state)
        self.w_ = rgen.normal(loc = 0, scale = 0,
                             size = 1 + X.shape[1])
        
        self.errors_ = []
        for _ in range(self.n_iter):
            errors = 0
            for i in range(len(X)):
                xi = X.iloc[i].values
                target = y[i]
                update = self.eta * (target - self.predict(xi))
                self.w_[1:] += update * xi
                self.w_[0] += update
                errors += int(update != 0.0)
            self.errors_.append(errors)
        return self
    
    def predict(self, X): #추론
        return np.where(self.net_input(X) >= 0.0, 1, 0)
    
    def net_input(self, X):
        return np.dot(X, self.w_[1:]) + self.w_[0]

pc_clf = Perceptron(n_iter = 10)
pc_clf.fit(logit_x_train, logit_y_train)
pc_pred = pc_clf.predict(logit_x_test)

In [37]:
print("퍼셉트론") 
get_clf_eval(logit_y_test, pc_pred)

퍼셉트론
오차행렬
[[2312    3]
 [  47    3]]
정확도: 0.9789, 정밀도 : 0.5000, 재현율:0.0600,F1 스코어:0.1071
ROC 스코어: 0.5294, PR score : 0.0499


# 3. lasso

In [38]:
lasso_x_train = x_train[lasso_feature].reset_index(drop='index')
lasso_x_test = x_test[lasso_feature].reset_index(drop='index')
lasso_y_train = train["label"]
lasso_y_test = test["label"]

In [39]:
# 1-1 LDA 
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
lda_clf = LinearDiscriminantAnalysis()
lda_clf.fit(lasso_x_train, lasso_y_train)
lda_pred = lda_clf.predict(lasso_x_test)
lda_pred_proba = lda_clf.predict_proba(lasso_x_test)

In [40]:
print("lda") 
print(get_clf_eval(lasso_y_test, lda_pred))

lda
오차행렬
[[2264   51]
 [  34   16]]
정확도: 0.9641, 정밀도 : 0.2388, 재현율:0.3200,F1 스코어:0.2735
ROC 스코어: 0.6490, PR score : 0.0908
None


In [41]:
# 디시전트리 구현
from sklearn.tree import DecisionTreeClassifier 
dt_clf = DecisionTreeClassifier(random_state=52)     
dt_clf.fit(lasso_x_train, lasso_y_train)
dt_pred = dt_clf.predict(lasso_x_test)
dt_pred_proba = dt_clf.predict_proba(lasso_x_test)                                    

In [42]:
print("디시전트리") 
print(get_clf_eval(lasso_y_test, dt_pred))

디시전트리
오차행렬
[[2265   50]
 [  40   10]]
정확도: 0.9619, 정밀도 : 0.1667, 재현율:0.2000,F1 스코어:0.1818
ROC 스코어: 0.5892, PR score : 0.0502
None


In [43]:
# 랜덤포레스트 구현
from sklearn.ensemble import RandomForestClassifier
rf_clf = RandomForestClassifier(random_state=52)     
rf_clf.fit(lasso_x_train, lasso_y_train)
rf_pred = rf_clf.predict(lasso_x_test)
rf_pred_proba = rf_clf.predict_proba(lasso_x_test)

In [44]:
print("랜덤포레스트") 
get_clf_eval(lasso_y_test, rf_pred)

랜덤포레스트
오차행렬
[[2307    8]
 [  42    8]]
정확도: 0.9789, 정밀도 : 0.5000, 재현율:0.1600,F1 스코어:0.2424
ROC 스코어: 0.5783, PR score : 0.0978


In [45]:
# 로지스틱 회귀 모델
from sklearn.linear_model import LogisticRegression
lr_clf = LogisticRegression()
lr_clf.fit(lasso_x_train, lasso_y_train)
lr_pred = lr_clf.predict(lasso_x_test)
lr_pred_proba = lr_clf.predict_proba(lasso_x_test)

In [46]:
print("로지스틱") 
get_clf_eval(lasso_y_test, lr_pred)

로지스틱
오차행렬
[[2308    7]
 [  46    4]]
정확도: 0.9776, 정밀도 : 0.3636, 재현율:0.0800,F1 스코어:0.1311
ROC 스코어: 0.5385, PR score : 0.0485


In [47]:
from sklearn.neighbors import KNeighborsClassifier

knn_clf = KNeighborsClassifier(n_neighbors=5)
knn_clf.fit(lasso_x_train, lasso_y_train)
knn_pred = knn_clf.predict(lasso_x_test)
knn_pred_proba = knn_clf.predict_proba(lasso_x_test)

c:\Users\young\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [48]:
print("knn") 
get_clf_eval(lasso_y_test, knn_pred)

knn
오차행렬
[[2312    3]
 [  44    6]]
정확도: 0.9801, 정밀도 : 0.6667, 재현율:0.1200,F1 스코어:0.2034
ROC 스코어: 0.5594, PR score : 0.0986


In [49]:
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
import xgboost as xgb ## XGBoost 불러오기
from xgboost import plot_importance 
lasso_x_train2 = lasso_x_train.copy()
lasso_x_test2 = lasso_x_test.copy()
lasso_y_train2 = lasso_y_train.copy()
lasso_y_test2 = lasso_y_test.copy()
lasso_x_train2.columns = [lasso_feature]
lasso_x_test2.columns =[lasso_feature]

xgb_wrapper = XGBClassifier()

xgb_wrapper.fit(lasso_x_train2, lasso_y_train2, verbose = True)


xgb_pred = xgb_wrapper.predict(lasso_x_test)
xgb_pred_proba = xgb_wrapper.predict_proba(lasso_x_test)

In [50]:
print("xgb") 
get_clf_eval(lasso_y_test, xgb_pred)

xgb
오차행렬
[[2306    9]
 [  41    9]]
정확도: 0.9789, 정밀도 : 0.5000, 재현율:0.1800,F1 스코어:0.2647
ROC 스코어: 0.5881, PR score : 0.1073


In [51]:
class Perceptron(object):
    
    def __init__(self, eta = 0.1, n_iter = 50, random_state = 1): #초기화
        self.eta = eta
        self.n_iter = n_iter
        self.random_state = random_state
        
    
    def fit(self, X, y): #학습
        rgen = np.random.RandomState(self.random_state)
        self.w_ = rgen.normal(loc = 0, scale = 0,
                             size = 1 + X.shape[1])
        
        self.errors_ = []
        for _ in range(self.n_iter):
            errors = 0
            for i in range(len(X)):
                xi = X.iloc[i].values
                target = y[i]
                update = self.eta * (target - self.predict(xi))
                self.w_[1:] += update * xi
                self.w_[0] += update
                errors += int(update != 0.0)
            self.errors_.append(errors)
        return self
    
    def predict(self, X): #추론
        return np.where(self.net_input(X) >= 0.0, 1, 0)
    
    def net_input(self, X):
        return np.dot(X, self.w_[1:]) + self.w_[0]

pc_clf = Perceptron(n_iter = 10)
pc_clf.fit(lasso_x_train, lasso_y_train)
pc_pred = pc_clf.predict(lasso_x_test)

In [52]:
print("퍼셉트론") 
get_clf_eval(lasso_y_test, pc_pred)

퍼셉트론
오차행렬
[[2312    3]
 [  48    2]]
정확도: 0.9784, 정밀도 : 0.4000, 재현율:0.0400,F1 스코어:0.0727
ROC 스코어: 0.5194, PR score : 0.0363


In [53]:
ela_x_train = x_train[ela_feature].reset_index(drop='index')
ela_x_test = x_test[ela_feature].reset_index(drop='index')
ela_y_train = train["label"]
ela_y_test = test["label"]

In [54]:
# 1-1 LDA 
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
lda_clf = LinearDiscriminantAnalysis()
lda_clf.fit(ela_x_train, ela_y_train)
lda_pred = lda_clf.predict(ela_x_test)
lda_pred_proba = lda_clf.predict_proba(ela_x_test)

In [55]:
print("lda") 
print(get_clf_eval(ela_y_test, lda_pred))

lda
오차행렬
[[2254   61]
 [  31   19]]
정확도: 0.9611, 정밀도 : 0.2375, 재현율:0.3800,F1 스코어:0.2923
ROC 스코어: 0.6768, PR score : 0.1034
None


In [56]:
# 디시전트리 구현
from sklearn.tree import DecisionTreeClassifier 
dt_clf = DecisionTreeClassifier(random_state=52)     
dt_clf.fit(ela_x_train, ela_y_train)
dt_pred = dt_clf.predict(ela_x_test)
dt_pred_proba = dt_clf.predict_proba(ela_x_test)                                    

In [57]:
print("디시전트리") 
print(get_clf_eval(ela_y_test, dt_pred))

디시전트리
오차행렬
[[2267   48]
 [  40   10]]
정확도: 0.9628, 정밀도 : 0.1724, 재현율:0.2000,F1 스코어:0.1852
ROC 스코어: 0.5896, PR score : 0.0514
None


In [58]:
# 랜덤포레스트 구현
from sklearn.ensemble import RandomForestClassifier
rf_clf = RandomForestClassifier(random_state=52)     
rf_clf.fit(ela_x_train, ela_y_train)
rf_pred = rf_clf.predict(ela_x_test)
rf_pred_proba = rf_clf.predict_proba(ela_x_test)

In [59]:
print("랜덤포레스트") 
get_clf_eval(ela_y_test, rf_pred)

랜덤포레스트
오차행렬
[[2306    9]
 [  42    8]]
정확도: 0.9784, 정밀도 : 0.4706, 재현율:0.1600,F1 스코어:0.2388
ROC 스코어: 0.5781, PR score : 0.0931


In [60]:
# 로지스틱 회귀 모델
from sklearn.linear_model import LogisticRegression
lr_clf = LogisticRegression()
lr_clf.fit(ela_x_train, ela_y_train)
lr_pred = lr_clf.predict(ela_x_test)
lr_pred_proba = lr_clf.predict_proba(ela_x_test)

In [61]:
print("로지스틱") 
get_clf_eval(ela_y_test, lr_pred)

로지스틱
오차행렬
[[2309    6]
 [  45    5]]
정확도: 0.9784, 정밀도 : 0.4545, 재현율:0.1000,F1 스코어:0.1639
ROC 스코어: 0.5487, PR score : 0.0645


In [62]:
from sklearn.neighbors import KNeighborsClassifier

knn_clf = KNeighborsClassifier(n_neighbors=5)
knn_clf.fit(ela_x_train, ela_y_train)
knn_pred = knn_clf.predict(ela_x_test)
knn_pred_proba = knn_clf.predict_proba(ela_x_test)

c:\Users\young\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [63]:
print("knn") 
get_clf_eval(ela_y_test, knn_pred)

knn
오차행렬
[[2310    5]
 [  46    4]]
정확도: 0.9784, 정밀도 : 0.4444, 재현율:0.0800,F1 스코어:0.1356
ROC 스코어: 0.5389, PR score : 0.0550


In [64]:
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
import xgboost as xgb ## XGBoost 불러오기
from xgboost import plot_importance 
ela_x_train2 = ela_x_train.copy()
ela_x_test2 = ela_x_test.copy()
ela_y_train2 = ela_y_train.copy()
ela_y_test2 = ela_y_test.copy()
ela_x_train2.columns = [ela_feature]
ela_x_test2.columns =[ela_feature]

xgb_wrapper = XGBClassifier()

xgb_wrapper.fit(ela_x_train2, ela_y_train2, verbose = True)


xgb_pred = xgb_wrapper.predict(ela_x_test)
xgb_pred_proba = xgb_wrapper.predict_proba(ela_x_test)

In [65]:
print("xgb") 
get_clf_eval(ela_y_test, xgb_pred)

xgb
오차행렬
[[2300   15]
 [  39   11]]
정확도: 0.9772, 정밀도 : 0.4231, 재현율:0.2200,F1 스코어:0.2895
ROC 스코어: 0.6068, PR score : 0.1096


In [66]:
class Perceptron(object):
    
    def __init__(self, eta = 0.1, n_iter = 50, random_state = 1): #초기화
        self.eta = eta
        self.n_iter = n_iter
        self.random_state = random_state
        
    
    def fit(self, X, y): #학습
        rgen = np.random.RandomState(self.random_state)
        self.w_ = rgen.normal(loc = 0, scale = 0,
                             size = 1 + X.shape[1])
        
        self.errors_ = []
        for _ in range(self.n_iter):
            errors = 0
            for i in range(len(X)):
                xi = X.iloc[i].values
                target = y[i]
                update = self.eta * (target - self.predict(xi))
                self.w_[1:] += update * xi
                self.w_[0] += update
                errors += int(update != 0.0)
            self.errors_.append(errors)
        return self
    
    def predict(self, X): #추론
        return np.where(self.net_input(X) >= 0.0, 1, 0)
    
    def net_input(self, X):
        return np.dot(X, self.w_[1:]) + self.w_[0]

pc_clf = Perceptron(n_iter = 10)
pc_clf.fit(ela_x_train, ela_y_train)
pc_pred = pc_clf.predict(ela_x_test)

In [67]:
print("퍼셉트론") 
get_clf_eval(ela_y_test, pc_pred)

퍼셉트론
오차행렬
[[2248   67]
 [  34   16]]
정확도: 0.9573, 정밀도 : 0.1928, 재현율:0.3200,F1 스코어:0.2406
ROC 스코어: 0.6455, PR score : 0.0761


# 5. 공통

In [68]:
same_x_train = x_train[same_feature].reset_index(drop='index')
same_x_test = x_test[same_feature].reset_index(drop='index')
same_y_train = train["label"]
same_y_test = test["label"]

In [69]:
# 1-1 LDA 
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
lda_clf = LinearDiscriminantAnalysis()
lda_clf.fit(same_x_train, same_y_train)
lda_pred = lda_clf.predict(same_x_test)
lda_pred_proba = lda_clf.predict_proba(same_x_test)

In [70]:
print("lda") 
print(get_clf_eval(same_y_test, lda_pred))

lda
오차행렬
[[2259   56]
 [  31   19]]
정확도: 0.9632, 정밀도 : 0.2533, 재현율:0.3800,F1 스코어:0.3040
ROC 스코어: 0.6779, PR score : 0.1094
None


In [71]:
# 디시전트리 구현
from sklearn.tree import DecisionTreeClassifier 
dt_clf = DecisionTreeClassifier(random_state=52)     
dt_clf.fit(same_x_train, same_y_train)
dt_pred = dt_clf.predict(same_x_test)
dt_pred_proba = dt_clf.predict_proba(same_x_test)                                    

In [72]:
print("디시전트리") 
print(get_clf_eval(same_y_test, dt_pred))

디시전트리
오차행렬
[[2274   41]
 [  41    9]]
정확도: 0.9653, 정밀도 : 0.1800, 재현율:0.1800,F1 스코어:0.1800
ROC 스코어: 0.5811, PR score : 0.0497
None


In [73]:
# 랜덤포레스트 구현
from sklearn.ensemble import RandomForestClassifier
rf_clf = RandomForestClassifier(random_state=52)     
rf_clf.fit(same_x_train, same_y_train)
rf_pred = rf_clf.predict(same_x_test)
rf_pred_proba = rf_clf.predict_proba(same_x_test)

In [74]:
print("랜덤포레스트") 
get_clf_eval(same_y_test, rf_pred)

랜덤포레스트
오차행렬
[[2308    7]
 [  42    8]]
정확도: 0.9793, 정밀도 : 0.5333, 재현율:0.1600,F1 스코어:0.2462
ROC 스코어: 0.5785, PR score : 0.1031


In [75]:
# 로지스틱 회귀 모델
from sklearn.linear_model import LogisticRegression
lr_clf = LogisticRegression()
lr_clf.fit(same_x_train, same_y_train)
lr_pred = lr_clf.predict(same_x_test)
lr_pred_proba = lr_clf.predict_proba(same_x_test)

In [76]:
print("로지스틱") 
get_clf_eval(same_y_test, lr_pred)

로지스틱
오차행렬
[[2308    7]
 [  46    4]]
정확도: 0.9776, 정밀도 : 0.3636, 재현율:0.0800,F1 스코어:0.1311
ROC 스코어: 0.5385, PR score : 0.0485


In [77]:
# KNN 모형 구현
from sklearn.neighbors import KNeighborsClassifier

knn_clf = KNeighborsClassifier(n_neighbors=5)
knn_clf.fit(same_x_train, same_y_train)
knn_pred = knn_clf.predict(same_x_test)
knn_pred_proba = knn_clf.predict_proba(same_x_test)

c:\Users\young\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [78]:
print("knn") 
get_clf_eval(same_y_test, knn_pred)

knn
오차행렬
[[2311    4]
 [  47    3]]
정확도: 0.9784, 정밀도 : 0.4286, 재현율:0.0600,F1 스코어:0.1053
ROC 스코어: 0.5291, PR score : 0.0456


In [79]:
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
import xgboost as xgb ## XGBoost 불러오기
from xgboost import plot_importance 
same_x_train2 = same_x_train.copy()
same_x_test2 = same_x_test.copy()
same_y_train2 = same_y_train.copy()
same_y_test2 = same_y_test.copy()
same_x_train2.columns = [same_feature]
same_x_test2.columns =[same_feature]

xgb_wrapper = XGBClassifier()

xgb_wrapper.fit(same_x_train2, same_y_train2, verbose = True)


xgb_pred = xgb_wrapper.predict(same_x_test)
xgb_pred_proba = xgb_wrapper.predict_proba(same_x_test)

In [80]:
print("xgb") 
get_clf_eval(same_y_test, xgb_pred)

xgb
오차행렬
[[2302   13]
 [  41    9]]
정확도: 0.9772, 정밀도 : 0.4091, 재현율:0.1800,F1 스코어:0.2500
ROC 스코어: 0.5872, PR score : 0.0910


In [81]:
class Perceptron(object):
    
    def __init__(self, eta = 0.1, n_iter = 50, random_state = 1): #초기화
        self.eta = eta
        self.n_iter = n_iter
        self.random_state = random_state
        
    
    def fit(self, X, y): #학습
        rgen = np.random.RandomState(self.random_state)
        self.w_ = rgen.normal(loc = 0, scale = 0,
                             size = 1 + X.shape[1])
        
        self.errors_ = []
        for _ in range(self.n_iter):
            errors = 0
            for i in range(len(X)):
                xi = X.iloc[i].values
                target = y[i]
                update = self.eta * (target - self.predict(xi))
                self.w_[1:] += update * xi
                self.w_[0] += update
                errors += int(update != 0.0)
            self.errors_.append(errors)
        return self
    
    def predict(self, X): #추론
        return np.where(self.net_input(X) >= 0.0, 1, 0)
    
    def net_input(self, X):
        return np.dot(X, self.w_[1:]) + self.w_[0]


In [82]:
pc_clf = Perceptron(n_iter = 10)
pc_clf.fit(same_x_train, same_y_train)
pc_pred = pc_clf.predict(same_x_test)

In [83]:
print("퍼셉트론") 
get_clf_eval(same_y_test, pc_pred)

퍼셉트론
오차행렬
[[2257   58]
 [  34   16]]
정확도: 0.9611, 정밀도 : 0.2162, 재현율:0.3200,F1 스코어:0.2581
ROC 스코어: 0.6475, PR score : 0.0836
