In [72]:
# 필요 라이브러리 import 
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
import warnings
warnings.filterwarnings(action='ignore') 

In [73]:
df = pd.read_csv("./데이터자료/9-1. MinMax 데이터셋.csv")
feature = pd.read_csv("./데이터자료/8-1. MinMAx feature.csv")
feature 


mda_feature logit_feature lasso_feature ela_feature same_feature
0     자기자본구성비율        매출액증가율       자기자본증가율     자기자본증가율       자기자본배율
1      매출액순이익률       유형자산증가율        총자본증가율      총자본증가율     자기자본구성비율
2      순운전자본비율       재고자산증가율       매출액순이익률     매출액순이익률      매출액순이익률
3     순운전자본회전률      비유동자산증가율      자기자본순이익률    자기자본순이익률       총자본증가율
4      총자본투자효율       유동자산증가율       순운전자본비율    총자본사업이익률     매출채권회전기간
5     자기자본순이익률          현금비율      유동자산구성비율     총자본순이익률      순운전자본비율
6       총자본증가율    이자보상배율이자비용        자기자본배율     순운전자본비율     순운전자본회전률
7     총자본사업이익률         비유동비율       매출채권회전률    자기자본구성비율     자기자본순이익률
8       기계투자효율      자기자본구성비율      매입채무회전기간      자기자본배율      총자본투자효율
9       1주당순이익        자기자본배율      매출채권회전기간    매출채권회전기간      매출채권회전률
10     총자본순이익률       매출채권회전률      순운전자본회전률    순운전자본회전률      총자본순이익률
11      자기자본배율      매출채권회전기간       총자본투자효율       부가가치율      자기자본증가율

In [74]:
train = df[df["회계년"] <= 2018].reset_index(drop='index')
test  = df[df["회계년"] > 2018].reset_index(drop='index')

In [75]:
x_train = train.drop("label",axis=1)
y_train = train["label"]
x_test =test.drop("label",axis=1)
y_test = test["label"]

In [76]:
mda_feature=feature["mda_feature"].tolist()
logit_feature=feature["logit_feature"].tolist()
lasso_feature=feature["lasso_feature"].tolist()
ela_feature=feature["ela_feature"].tolist()
same_feature=feature["same_feature"].tolist()

In [77]:
# 성능확인 코드
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score
from sklearn.metrics import f1_score, roc_auc_score, average_precision_score


import warnings

def get_clf_eval(MDA_y_test, pred):
    confusion = confusion_matrix(MDA_y_test, pred)
    accuracy = accuracy_score(MDA_y_test, pred)
    precision = precision_score(MDA_y_test, pred)
    recall = recall_score(MDA_y_test, pred)
    roc_score = roc_auc_score(MDA_y_test, pred)
    pr_score = average_precision_score(MDA_y_test, pred)
    f1 = f1_score(MDA_y_test, pred)
    print('오차행렬')
    print(confusion)
    print('정확도: {0:.4f}, 정밀도 : {1:.4f}, 재현율:{2:.4f},F1 스코어:{3:.4f}'.format(accuracy, precision, recall, f1, roc_score))
    print('ROC 스코어: {0:.4f}, PR score : {1:.4f}'.format(roc_score, pr_score))
    print("---------------------------------------------------------")

In [78]:
# 임계값에 따른 오차행렬및 스코어 -------->#임계값 최적 : 재현율기준(0.1)/f1기준(0.3)
from sklearn.preprocessing import Binarizer
thresholds = [0.1,0.2,0.3,0.4,0.5]

def get_eval_by_threshold(MDA_y_test, pred_proba_c1, thresholds):
    for custom_threshold in thresholds:
        binarizer = Binarizer(threshold=custom_threshold).fit(pred_proba_c1)
        custom_predict = binarizer.transform(pred_proba_c1)
        print("임곗값:", custom_threshold)
        get_clf_eval(MDA_y_test, custom_predict)
        print("---------------------------------------------------------")

In [79]:
# Roc Auc 그래프 값 확인 코드
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score
def roc_curve_plot(MDA_y_test, pred_proba_c1):
    fprs, tprs, thresholds = roc_curve(MDA_y_test, pred_proba_c1)
    
    plt.plot(fprs, tprs, label='ROC')
    plt.plot([0,1],[0,1], 'k--', label = 'Random')
    
    start, end= plt.xlim()
    plt.xticks(np.round(np.arange(start, end, 0.1),2))
    plt.xlim(0,1); plt.ylim(0,1)
    plt.xlabel('FPR(1-Sensitivity)'); plt.ylabel('TPR(Recall)')
    plt.legend()
    plt.show()

# 1. mda_feature

In [80]:
mda_x_train = x_train[mda_feature].reset_index(drop='index')
mda_x_test = x_test[mda_feature].reset_index(drop='index')
mda_y_train = train["label"]
mda_y_test = test["label"]

In [81]:
logit_x_train = x_train[logit_feature].reset_index(drop='index')
logit_x_test = x_test[logit_feature].reset_index(drop='index')
logit_y_train = train["label"]
logit_y_test = test["label"]

In [82]:
lasso_x_train = x_train[lasso_feature].reset_index(drop='index')
lasso_x_test = x_test[lasso_feature].reset_index(drop='index')
lasso_y_train = train["label"]
lasso_y_test = test["label"]

In [83]:
ela_x_train = x_train[ela_feature].reset_index(drop='index')
ela_x_test = x_test[ela_feature].reset_index(drop='index')
ela_y_train = train["label"]
ela_y_test = test["label"]

In [84]:
same_x_train = x_train[same_feature].reset_index(drop='index')
same_x_test = x_test[same_feature].reset_index(drop='index')
same_y_train = train["label"]
same_y_test = test["label"]

In [85]:
fea_x_train = [mda_x_train, logit_x_train, lasso_x_train, ela_x_train, same_x_train]
fea_y_train = [mda_y_train, logit_y_train, lasso_y_train, ela_y_train, same_y_train]
fea_x_test = [mda_x_test, logit_x_test, lasso_x_test, ela_x_test, same_x_test]
fea_y_test = [mda_y_test, logit_y_test, lasso_y_test, ela_y_test, same_y_test]
fea = ["mda","logit","lasso","ela","same"]

In [86]:
# 1-1 LDA 
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
lda_clf = LinearDiscriminantAnalysis()
for x_train,y_train,x_test,y_test,feature in zip(fea_x_train,fea_y_train,fea_x_test, fea_y_test, fea):
    lda_clf.fit(x_train, y_train)
    lda_pred = lda_clf.predict(x_test)
    lda_pred_proba = lda_clf.predict_proba(x_test)
    print(feature,"lda") 
    get_clf_eval(y_test, lda_pred)
    get_eval_by_threshold(y_test , lda_pred_proba[:,1].reshape(-1,1), thresholds)



mda lda
오차행렬
[[2252   63]
 [  32   18]]
정확도: 0.9598, 정밀도 : 0.2222, 재현율:0.3600,F1 스코어:0.2748
ROC 스코어: 0.6664, PR score : 0.0935
---------------------------------------------------------
임곗값: 0.1
오차행렬
[[2171  144]
 [  26   24]]
정확도: 0.9281, 정밀도 : 0.1429, 재현율:0.4800,F1 스코어:0.2202
ROC 스코어: 0.7089, PR score : 0.0796
---------------------------------------------------------
---------------------------------------------------------
임곗값: 0.2
오차행렬
[[2210  105]
 [  27   23]]
정확도: 0.9442, 정밀도 : 0.1797, 재현율:0.4600,F1 스코어:0.2584
ROC 스코어: 0.7073, PR score : 0.0941
---------------------------------------------------------
---------------------------------------------------------
임곗값: 0.3
오차행렬
[[2229   86]
 [  27   23]]
정확도: 0.9522, 정밀도 : 0.2110, 재현율:0.4600,F1 스코어:0.2893
ROC 스코어: 0.7114, PR score : 0.1085
---------------------------------------------------------
---------------------------------------------------------
임곗값: 0.4
오차행렬
[[2243   72]
 [  29   21]]
정확도: 0.9573, 정밀도 : 0.2258, 재현율:0.4200,F1 스

In [87]:
# 1-2 디시전트리 
from sklearn.tree import DecisionTreeClassifier 
dt_clf = DecisionTreeClassifier(random_state=52)
for x_train,y_train,x_test,y_test,feature in zip(fea_x_train,fea_y_train,fea_x_test, fea_y_test, fea):
    dt_clf.fit(x_train, y_train)
    dt_pred = dt_clf.predict(x_test)
    dt_pred_proba = dt_clf.predict_proba(x_test)   
    print(feature,"디시전트리") 
    get_clf_eval(y_test, dt_pred)
    get_eval_by_threshold(y_test , dt_pred_proba[:,1].reshape(-1,1), thresholds)
    


mda 디시전트리
오차행렬
[[2265   50]
 [  42    8]]
정확도: 0.9611, 정밀도 : 0.1379, 재현율:0.1600,F1 스코어:0.1481
ROC 스코어: 0.5692, PR score : 0.0398
---------------------------------------------------------
임곗값: 0.1
오차행렬
[[2265   50]
 [  42    8]]
정확도: 0.9611, 정밀도 : 0.1379, 재현율:0.1600,F1 스코어:0.1481
ROC 스코어: 0.5692, PR score : 0.0398
---------------------------------------------------------
---------------------------------------------------------
임곗값: 0.2
오차행렬
[[2265   50]
 [  42    8]]
정확도: 0.9611, 정밀도 : 0.1379, 재현율:0.1600,F1 스코어:0.1481
ROC 스코어: 0.5692, PR score : 0.0398
---------------------------------------------------------
---------------------------------------------------------
임곗값: 0.3
오차행렬
[[2265   50]
 [  42    8]]
정확도: 0.9611, 정밀도 : 0.1379, 재현율:0.1600,F1 스코어:0.1481
ROC 스코어: 0.5692, PR score : 0.0398
---------------------------------------------------------
---------------------------------------------------------
임곗값: 0.4
오차행렬
[[2265   50]
 [  42    8]]
정확도: 0.9611, 정밀도 : 0.1379, 재현율:0.1600,F1

In [88]:
from sklearn.tree import DecisionTreeClassifier 
dt_clf = DecisionTreeClassifier(random_state=52)
from sklearn.model_selection import GridSearchCV
tree = DecisionTreeClassifier(random_state=52)
for x_train,y_train,x_test,y_test,feature in zip(fea_x_train,fea_y_train,fea_x_test, fea_y_test, fea):
    # key: 하이퍼파라미터 명; value: [후보값들] 을 리스트로 전달
    param_grid = {
      'criterion': ['entropy', 'gini'],
               'max_depth': [2,4,6,8],
               'max_features': ['auto', 'sqrt'],
               'min_samples_leaf': [4,6,8,10],
               'min_samples_split': [4,6,8,10]}
    grid_search = GridSearchCV(tree
                            , param_grid = param_grid
                            , cv = 5 #교차검증시 fold 개수; n번의 교차검증; 데이터들이 돌아가면서 하나씩 검증(validation)에 사용되어 일반화하는 것; 데이터가 많지 않을 때 보통 쓰인다고 함
                            , n_jobs = -1)  #-1: 모든 코어 사용

    grid_search.fit(x_train, y_train)

    # 최선의 결과 출력
    print('피처:{2} 최적 하이퍼 파라미터 :{0}, 최적 평균 정확도 :{1:.3f}'.format(grid_search.best_params_, grid_search.best_score_, feature))
    a = grid_search.best_params_
    keys=list(a.keys())
    values = list(a.values())

    dt_clf_best = DecisionTreeClassifier(random_state=52,criterion = values[0], max_depth = values[1],max_features=values[2], min_samples_leaf=values[3], min_samples_split=values[4])
    dt_clf_best.fit(x_train, y_train)
    dt_best_pred = dt_clf_best.predict(x_test)
    dt_best_pred_proba = dt_clf_best.predict_proba(x_test)   

    print(feature,"디시전트리 파라미터적용") 
    get_clf_eval(y_test, dt_best_pred)
    get_eval_by_threshold(y_test ,dt_best_pred_proba[:,1].reshape(-1,1), thresholds)


피처:mda 최적 하이퍼 파라미터 :{'criterion': 'entropy', 'max_depth': 8, 'max_features': 'auto', 'min_samples_leaf': 8, 'min_samples_split': 4}, 최적 평균 정확도 :0.984
mda 디시전트리 파라미터적용
오차행렬
[[2301   14]
 [  39   11]]
정확도: 0.9776, 정밀도 : 0.4400, 재현율:0.2200,F1 스코어:0.2933
ROC 스코어: 0.6070, PR score : 0.1133
---------------------------------------------------------
임곗값: 0.1
오차행렬
[[2207  108]
 [  27   23]]
정확도: 0.9429, 정밀도 : 0.1756, 재현율:0.4600,F1 스코어:0.2541
ROC 스코어: 0.7067, PR score : 0.0922
---------------------------------------------------------
---------------------------------------------------------
임곗값: 0.2
오차행렬
[[2264   51]
 [  34   16]]
정확도: 0.9641, 정밀도 : 0.2388, 재현율:0.3200,F1 스코어:0.2735
ROC 스코어: 0.6490, PR score : 0.0908
---------------------------------------------------------
---------------------------------------------------------
임곗값: 0.3
오차행렬
[[2287   28]
 [  35   15]]
정확도: 0.9734, 정밀도 : 0.3488, 재현율:0.3000,F1 스코어:0.3226
ROC 스코어: 0.6440, PR score : 0.1195
----------------------------------------

In [89]:
# 1-3 랜덤포레스트 구현 
from sklearn.ensemble import RandomForestClassifier
rf_clf = RandomForestClassifier(random_state=52)    
for x_train,y_train,x_test,y_test,feature in zip(fea_x_train,fea_y_train,fea_x_test, fea_y_test, fea):
    rf_clf.fit(x_train, y_train)
    rf_pred = rf_clf.predict(x_test)
    rf_pred_proba = rf_clf.predict_proba(x_test)
    print(feature,"랜덤포레스트") 
    get_clf_eval(y_test, rf_pred)
    get_eval_by_threshold(y_test , rf_pred_proba[:,1].reshape(-1,1), thresholds)
    


mda 랜덤포레스트
오차행렬
[[2308    7]
 [  41    9]]
정확도: 0.9797, 정밀도 : 0.5625, 재현율:0.1800,F1 스코어:0.2727
ROC 스코어: 0.5885, PR score : 0.1186
---------------------------------------------------------
임곗값: 0.1
오차행렬
[[2208  107]
 [  26   24]]
정확도: 0.9438, 정밀도 : 0.1832, 재현율:0.4800,F1 스코어:0.2652
ROC 스코어: 0.7169, PR score : 0.0989
---------------------------------------------------------
---------------------------------------------------------
임곗값: 0.2
오차행렬
[[2279   36]
 [  36   14]]
정확도: 0.9696, 정밀도 : 0.2800, 재현율:0.2800,F1 스코어:0.2800
ROC 스코어: 0.6322, PR score : 0.0936
---------------------------------------------------------
---------------------------------------------------------
임곗값: 0.3
오차행렬
[[2294   21]
 [  38   12]]
정확도: 0.9751, 정밀도 : 0.3636, 재현율:0.2400,F1 스코어:0.2892
ROC 스코어: 0.6155, PR score : 0.1033
---------------------------------------------------------
---------------------------------------------------------
임곗값: 0.4
오차행렬
[[2300   15]
 [  41    9]]
정확도: 0.9763, 정밀도 : 0.3750, 재현율:0.1800,F

In [98]:
# 하이퍼파라미터 Grid-Search
from sklearn.model_selection import GridSearchCV

    # 탐색 범위 정의
for x_train,y_train,x_test,y_test,feature in zip(fea_x_train,fea_y_train,fea_x_test, fea_y_test, fea):
    grid_search = {'criterion': ['entropy', 'gini'],
                'max_depth': [2,4,6,8],
                'max_features': ['auto', 'sqrt'],
                'min_samples_leaf': [4,6,8,10],
                'min_samples_split': [4,6,8,10],
                'n_estimators': [20,40,60,80,100]}

    model = RandomForestClassifier(random_state=52)
    grid_search = GridSearchCV(estimator = model, param_grid = grid_search, 
                                cv = 5,verbose=0, n_jobs = -1)
    grid_search.fit(x_train,y_train)

    # 최선의 결과 출력
    print('최적 하이퍼 파라미터 :{0}, 최적 평균 정확도 :{1:.3f}'.format(grid_search.best_params_, grid_search.best_score_))
    a = grid_search.best_params_
    keys=list(a.keys())
    values = list(a.values())

    rf_clf_best = RandomForestClassifier(random_state=52,criterion = values[0], max_depth = values[1],max_features=values[2], min_samples_leaf=values[3],  min_samples_split=values[4],n_estimators=values[5])
    rf_clf_best.fit(x_train, y_train)
    rf_best_pred = rf_clf_best.predict(x_test)
    rf_best_pred_proba = rf_clf_best.predict_proba(x_test)   

    print(feature,"랜덤포레스트 파라미터적용") 
    get_clf_eval(y_test, rf_best_pred)
    get_eval_by_threshold(y_test ,rf_best_pred_proba[:,1].reshape(-1,1), thresholds)

KeyboardInterrupt: 

In [91]:
# 1-4 로지스틱회귀
from sklearn.linear_model import LogisticRegression
lr_clf = LogisticRegression()
for x_train,y_train,x_test,y_test,feature in zip(fea_x_train,fea_y_train,fea_x_test, fea_y_test, fea):
    lr_clf.fit(x_train, y_train)
    lr_pred = lr_clf.predict(x_test)
    lr_pred_proba = lr_clf.predict_proba(x_test)
    print(feature,"로지스틱회귀") 
    get_clf_eval(y_test, lr_pred)
    get_eval_by_threshold(y_test , lr_pred_proba[:,1].reshape(-1,1), thresholds)
    

mda 로지스틱회귀
오차행렬
[[2310    5]
 [  50    0]]
정확도: 0.9767, 정밀도 : 0.0000, 재현율:0.0000,F1 스코어:0.0000
ROC 스코어: 0.4989, PR score : 0.0211
---------------------------------------------------------
임곗값: 0.1
오차행렬
[[2259   56]
 [  27   23]]
정확도: 0.9649, 정밀도 : 0.2911, 재현율:0.4600,F1 스코어:0.3566
ROC 스코어: 0.7179, PR score : 0.1453
---------------------------------------------------------
---------------------------------------------------------
임곗값: 0.2
오차행렬
[[2297   18]
 [  39   11]]
정확도: 0.9759, 정밀도 : 0.3793, 재현율:0.2200,F1 스코어:0.2785
ROC 스코어: 0.6061, PR score : 0.0999
---------------------------------------------------------
---------------------------------------------------------
임곗값: 0.3
오차행렬
[[2307    8]
 [  42    8]]
정확도: 0.9789, 정밀도 : 0.5000, 재현율:0.1600,F1 스코어:0.2424
ROC 스코어: 0.5783, PR score : 0.0978
---------------------------------------------------------
---------------------------------------------------------
임곗값: 0.4
오차행렬
[[2309    6]
 [  46    4]]
정확도: 0.9780, 정밀도 : 0.4000, 재현율:0.0800,F

In [ ]:
#로지스틱 회귀 최적 하이퍼 파라미터
from sklearn.model_selection import GridSearchCV

for x_train,y_train,x_test,y_test,feature in zip(fea_x_train,fea_y_train,fea_x_test, fea_y_test, fea):
    params = {'penalty': ['l2','l1','elasticnet','None'],
            'C':[0.01,0.1,1,3,5,10]}

    grid_search = GridSearchCV(lr_clf, param_grid=params, scoring='accuracy', cv=5)
    grid_search.fit(x_train,y_train)
    print('최적 하이퍼 파라미어:{0}, 최적 평균 정확도:{1:.3f}'.format(grid_search.best_params_, grid_search.best_score_))

    a = grid_search.best_params_
    keys=list(a.keys())
    values = list(a.values())

    lr_clf_best = LogisticRegression(penalty= values[1], C=values[0])
    lr_clf_best.fit(x_train, y_train)
    lr_best_pred = lr_clf_best.predict(x_test)
    lr_best_pred_proba = lr_clf_best.predict_proba(x_test)   

    print(feature,"로지스틱회귀 파라미터적용") 
    get_clf_eval(y_test, lr_best_pred)
    get_eval_by_threshold(y_test ,lr_best_pred_proba[:,1].reshape(-1,1), thresholds)


In [93]:
# 1-5 KNN 
from sklearn.neighbors import KNeighborsClassifier
knn_clf = KNeighborsClassifier(n_neighbors=5)
for x_train,y_train,x_test,y_test,feature in zip(fea_x_train,fea_y_train,fea_x_test, fea_y_test, fea):

    knn_clf.fit(x_train, y_train)
    knn_pred = knn_clf.predict(x_test)
    knn_pred_proba = knn_clf.predict_proba(x_test)
    print(feature,"KNN") 
    get_clf_eval(y_test, knn_pred)
    get_eval_by_threshold(y_test , knn_pred_proba[:,1].reshape(-1,1), thresholds)



mda KNN
오차행렬
[[2312    3]
 [  42    8]]
정확도: 0.9810, 정밀도 : 0.7273, 재현율:0.1600,F1 스코어:0.2623
ROC 스코어: 0.5794, PR score : 0.1341
---------------------------------------------------------
임곗값: 0.1
오차행렬
[[2199  116]
 [  30   20]]
정확도: 0.9383, 정밀도 : 0.1471, 재현율:0.4000,F1 스코어:0.2151
ROC 스코어: 0.6749, PR score : 0.0715
---------------------------------------------------------
---------------------------------------------------------
임곗값: 0.2
오차행렬
[[2297   18]
 [  38   12]]
정확도: 0.9763, 정밀도 : 0.4000, 재현율:0.2400,F1 스코어:0.3000
ROC 스코어: 0.6161, PR score : 0.1121
---------------------------------------------------------
---------------------------------------------------------
임곗값: 0.3
오차행렬
[[2297   18]
 [  38   12]]
정확도: 0.9763, 정밀도 : 0.4000, 재현율:0.2400,F1 스코어:0.3000
ROC 스코어: 0.6161, PR score : 0.1121
---------------------------------------------------------
---------------------------------------------------------
임곗값: 0.4
오차행렬
[[2312    3]
 [  42    8]]
정확도: 0.9810, 정밀도 : 0.7273, 재현율:0.1600,F1 스

In [ ]:
# knn 파라미터 구하기
from sklearn.metrics import accuracy_score
acc = []
for x_train,y_train,x_test,y_test,feature in zip(fea_x_train,fea_y_train,fea_x_test, fea_y_test, fea):
    for k in range(1,20):
        knn_clf = KNeighborsClassifier(n_neighbors=k)
        knn_clf.fit(x_train, y_train)
        knn_pred = knn_clf.predict(x_test)
        knn_score=accuracy_score(y_test,knn_pred)

        acc.append(knn_score)
    j = acc.index(max(acc))+1
    print("최적거리")
    print(j)

    knn_clf_best =KNeighborsClassifier(n_neighbors=j)
    knn_clf_best.fit(x_train, y_train)
    knn_best_pred = knn_clf_best.predict(x_test)
    knn_best_pred_proba = knn_clf_best.predict_proba(x_test)   

    print(feature,"KNN 파라미터적용") 
    get_clf_eval(y_test, knn_best_pred)
    get_eval_by_threshold(y_test ,knn_best_pred_proba[:,1].reshape(-1,1), thresholds)      


In [95]:
# 1-5 xgboost
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
import xgboost as xgb ## XGBoost 불러오기
from xgboost import plot_importance 

xgb_wrapper = XGBClassifier()
for x_train,y_train,x_test,y_test,feature in zip(fea_x_train,fea_y_train,fea_x_test, fea_y_test, fea):

    xgb_wrapper.fit(x_train, y_train, verbose = True)
    xgb_wrapper.fit(x_train, y_train)
    xgb_pred = xgb_wrapper.predict(x_test)
    xgb_pred_proba = xgb_wrapper.predict_proba(x_test)
    print(feature,"XGB") 
    get_clf_eval(y_test, xgb_pred)
    get_eval_by_threshold(y_test , xgb_pred_proba[:,1].reshape(-1,1), thresholds)

mda XGB
오차행렬
[[2302   13]
 [  40   10]]
정확도: 0.9776, 정밀도 : 0.4348, 재현율:0.2000,F1 스코어:0.2740
ROC 스코어: 0.5972, PR score : 0.1039
---------------------------------------------------------
임곗값: 0.1
오차행렬
[[2279   36]
 [  38   12]]
정확도: 0.9687, 정밀도 : 0.2500, 재현율:0.2400,F1 스코어:0.2449
ROC 스코어: 0.6122, PR score : 0.0761
---------------------------------------------------------
---------------------------------------------------------
임곗값: 0.2
오차행렬
[[2290   25]
 [  38   12]]
정확도: 0.9734, 정밀도 : 0.3243, 재현율:0.2400,F1 스코어:0.2759
ROC 스코어: 0.6146, PR score : 0.0939
---------------------------------------------------------
---------------------------------------------------------
임곗값: 0.3
오차행렬
[[2297   18]
 [  39   11]]
정확도: 0.9759, 정밀도 : 0.3793, 재현율:0.2200,F1 스코어:0.2785
ROC 스코어: 0.6061, PR score : 0.0999
---------------------------------------------------------
---------------------------------------------------------
임곗값: 0.4
오차행렬
[[2302   13]
 [  40   10]]
정확도: 0.9776, 정밀도 : 0.4348, 재현율:0.2000,F1 스

In [ ]:
#xgb 최적 하이퍼 파라미터
from sklearn.model_selection import GridSearchCV

xgb_wrapper
for x_train,y_train,x_test,y_test,feature in zip(fea_x_train,fea_y_train,fea_x_test, fea_y_test, fea):
    params = {
            'n_estimators':[40,43,46,50],
            'learning_rate':[0.03,0.05,0.04],
            'max_depth' : [0.8,1,2,3,4]
            }

    grid_clf = GridSearchCV(xgb_wrapper, param_grid=params, scoring='accuracy', cv=5)
    grid_clf.fit(x_train,y_train)
    print('최적 하이퍼 파라미어:{0}, 최적 평균 정확도:{1:.3f}'.format(grid_clf.best_params_, grid_clf.best_score_))

    a = grid_clf.best_params_
    keys=list(a.keys())
    values = list(a.values())
    xgb_clf_best = XGBClassifier( learning_rate=values[0],max_depth=values[1],n_estimators= values[2])
    xgb_clf_best.fit(x_train, y_train)
    xgb_best_pred = xgb_clf_best.predict(x_test)
    xgb_best_pred_proba = xgb_clf_best.predict_proba(x_test)   

    print(feature,"XGB 파라미터적용") 
    get_clf_eval(y_test, xgb_best_pred)
    get_eval_by_threshold(y_test ,xgb_best_pred_proba[:,1].reshape(-1,1), thresholds)